
<div class="row">
    <div class="col-md-12">
       <ul class="menu-links">
	   <?php if($this->role == 1){ ?>
	       <li><a href="<?php echo $this->baseUrl(); ?>/admin/user/new" title="Create new user">Add New User</a></li>
		   <?php } ?>
       </ul>
    </div>
</div>
			
<div class="row">        
                    <div class="col-md-12">     
		
        <div id="msg">
			<?php echo $this->msg ?>
		</div>
		
                     <div class="table-responsive">
													<table class="table table-striped table-bordered table-hover" id="dataTables-example">
														<thead>
														<tr>
																<th class="grid-head"> Name</th>
																<th class="grid-head"> Email</th>
                                                                <th class="grid-head"> Role</th>
																<!-- th class="grid-head">Status </th -->
																<th class="grid-head">Edit </th>
																<th class="grid-head">Change Status</th>
                                                        	</tr>
														</thead>		
														<tbody> 
                                          
														<?php if (count($this->data)){ 
														  foreach ($this->data as $item): ?>
														<tr class="odd gradeX">
															<td style="text-align:center;">
															<?php echo $item['user_name'] ?>
															</td> 
                                                            <td style="text-align:center;">
															     <?php echo $item['email']?>
															</td>
															<td style="text-align:center;">
															<?php if($item['role_id'] == 1){
																  ?>
													       <p>Administrator</p> 
														     <?php
														     }
		elseif($item['role_id'] == 2){
																  ?>
													       <p>Editor</p> 
														     <?php
														     }
		elseif($item['role_id'] == 3){
																  ?>
													       <p>Author</p> 
														     <?php
														     }
		elseif($item['role_id'] == 4){
																  ?>
													       <p>Contributor</p> 
														     <?php
														     }												   else{
															  ?>
															<p>Subscriber</p>
														     <?php 	
															}
															?>
															</td>

	<!-- td style="text-align:center;">
															<?php //if($item['is_active'] == 1){
																  ?>
													       <p>Active</p> 
														     <?php
														    // }
		//else{
															  ?>
															<p>Block</p>
		<?php 	//}														?>	 </td -->                                                       <td style="text-align:center;"><a class="btn btn-sm btn-warning float-right" href="<?php echo $this->baseUrl()?>/admin/user/edit/id/<?php echo $item['user_id']?>">Edit</a></td>
															
	<td style="text-align:center;">														<?php if($item['is_active']== 1){?>
															<a class="btn btn-sm btn-primary" href="#" onclick="return confirmBlock(<?php echo $item['user_id'] ?> )" >Block</a><?php }else{ ?>
															<a class="btn btn-sm btn-danger" href="#" onclick="return confirmActive(<?php echo $item['user_id'] ?> )" >Activate</a> <?php } ?> </td>
														</tr>  
															<?php endforeach; } ?> 
														</tbody>

						 								</table>
                    </div><!-- div responsive end-->												
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->

  <script language="Javascript" type="text/javascript">
 window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('#msg').hide();
			
		<?php  } else{
		?>
			$('#msg').show().delay(3000).hide('slow');
		<?php } ?>
        
        $('#dataTables-example').dataTable(
           {
		      "aaSorting": [[ 0, "asc" ]],
              "iDisplayLength": 50,
              "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
              "aoColumnDefs": [{'bSortable': false, 'aTargets': [3,4]}]
	       }
        );
 }
 
function confirmActive(id){
	var r = confirm("Are you sure to Active this User! " );
	if (r == true) {
	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/user/active-user/id/" + id);    
	} else {
	return false;
	}
	}
	
  function confirmBlock(id){
	var r = confirm("Are you sure to Block this User! " );
	if (r == true) {
	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/user/block-user/id/" + id);    
	} else {
	return false;
	}
	}
 </script>