
 <div class="row">
    <div class="col-md-12">
	<ul class="menu-links">
	  <?php if($this->role == 1){ ?>   
    <li><a href="<?php echo $this->baseUrl(); ?>/admin/user" title="View users list">Users List</a></li> <?php } ?>    
    </ul>
    
	</div>
</div>
 
            <div class="row">
            <div class="col-md-10">
                <div id='msg'><?php echo $this->msg; ?></div>
            
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" >
                    
               <table class="table space-mangead">

<tr><td><strong>Name</strong></td></tr>
  <?php echo $this->form->user_name; ?>
<tr><td><strong>Email</strong></td></tr>
  <?php echo $this->form->email; ?>
<tr><td><strong>Password</strong></td></tr>
  <?php echo $this->form->password; ?>
<tr><td><strong>Select Role</strong></td></tr>
  <?php echo $this->form->role; ?>
  
<tr><td> <?php echo $this->form->submit?></td></tr>
</table>
                 </form>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>

<script language="Javascript" type="text/javascript">
window.onload = function () {
 <?php if(!isset($this->msg)){ ?>
      $('#msg').hide();

    <?php  } else{
    ?>
      $('#msg').show().delay(3000).hide('slow');

    <?php } ?>
           
 }
 </script>