 <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title><?php echo $this->escape($this->title); ?></title>
    <!-- Bootstrap -->
    <link href="<?php echo $this->baseUrl(); ?>/css/admin/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="<?php echo $this->baseUrl(); ?>/css/admin/sb-admin.css" rel="stylesheet" />
    <!-- Morris Charts CSS -->
    <link href="<?php echo $this->baseUrl(); ?>/css/admin/plugins/morris.css" rel="stylesheet" />
    <!-- Custom Fonts -->
    <link href="<?php echo $this->baseUrl(); ?>/css/admin/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- DataTables CSS -->
    <link href="<?php echo $this->baseUrl(); ?>/css/admin/plugins/dataTables.bootstrap.css" rel="stylesheet" />
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  <link href="<?php echo $this->baseUrl(); ?>/css/admin/admin.css" rel="stylesheet">
  <!-- jQuery -->
    <script src="<?php echo $this->baseUrl(); ?>/js/admin/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->baseUrl(); ?>/js/admin/bootstrap.min.js"></script>
  </head>
  <body>
 <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>/admin/index">Netefct Admin Setting</a>
            </div>
        <!-- Top menu -->
          <?php echo $this->render("/setting/header.phtml"); ?>
            <!-- Left Navigation Panel -->
           <?php echo $this->render("/setting/left-panel.phtml"); ?>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">
               <?php echo $this->layout()->content; ?>
            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->


   <!--
   Morris Charts JavaScript
   -->
   <script src="<?php echo $this->baseUrl(); ?>/js/admin/plugins/morris/raphael.min.js"></script>
   <script src="<?php echo $this->baseUrl(); ?>/js/admin/plugins/morris/morris.min.js"></script>
   <script src="<?php echo $this->baseUrl(); ?>/js/admin/plugins/morris/morris-data.js"></script>
   
   <!-- Page-Level Plugin Scripts - Tables -->
   <script src="<?php echo $this->baseUrl()?>/js/admin/plugins/dataTables/jquery.dataTables.js"></script>
   <script src="<?php echo $this->baseUrl()?>/js/admin/plugins/dataTables/dataTables.bootstrap.js"></script>
<script>

/*$(function(){
alert("Jquery is working");

});
*/
</script>

  </body>
</html>