<div class="row">
    <div class="col-md-12">
	<ul class="menu-links">
	<li><a href="<?php echo $this->baseUrl(); ?>/admin/posts/new-post" title="Create new post"> New Post</a></li>              
	<li><a href="<?php echo $this->baseUrl(); ?>/admin/posts/index" title="View list">Posts List</a></li>       
    <li><strong><a href="<?php echo $this->baseUrl(); ?>/admin/post-category/index" title="Post Category List">Post Category List</a></strong></li>       
	</ul>
	</div>
</div>

<div id="msg"><?php echo $this->msg;?></div>
<div class="row">        
    <div class="col-md-6 col-md-offset-3">
        <form method="POST" action="" class="form-horizontal">
                <div class="form-group">
                    <?php echo $this->form->name; ?>
                </div>
                <div class="form-group">
                    <?php echo html_entity_decode($this->form->parent_id); ?>
                </div>
                <div class="form-group">
                    <input type="submit" value="Update Category" class="btn btn-primary pull-right" />
                </div>
        </form>        
    </div>
</div>

<script type="text/javascript">
    $(function(){
        <?php if(!isset($this->msg)){ ?>
			$('#msg').hide();			
		<?php  } else{		?>
			$('#msg').show().delay(3000).hide('slow');
		<?php } ?>
    }); 
</script>