<div class="row">
    <div class="col-md-12">
	<ul class="menu-links">
	<li><a href="<?php echo $this->baseUrl(); ?>/admin/posts/new-post" title="Create new post"> New Post</a></li>              
	<li><a href="<?php echo $this->baseUrl(); ?>/admin/posts/index" title="View list">Posts List</a></li>       
    <li><strong><a href="<?php echo $this->baseUrl(); ?>/admin/post-category/index" title="Post Category List">Post Category List</a></strong></li>
	</ul>
	</div>
</div>

<div id="msg"><?php echo $this->msg;?></div>
<div class="row">        
    <div class="col-md-12">
        
        <div class="row">    
                
            <form method="POST" action="<?php echo $this->baseUrl();?>/admin/post-category/index">
                <div class="col-md-4">
                    <?php echo $this->form->name; ?>
                </div>
                <div class="col-md-4">
                    <?php echo html_entity_decode($this->form->parent_id); ?>
                </div>
                <div class="col-md-2">
                    <!--span><?php //echo $this->form->submit; ?></span-->
                    <input type="submit" value="Add New Category" class="btn btn-primary pull-right" />
                </div>
            </form>        
        </div>
        <br />
        <div class="table-responsive">
            <form method="post" action="<?php echo $this->baseUrl();?>/admin/post-category/delete">
                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead>
    				    <tr>
                           <th class="grid-head">Category Name</th>
    					   <th class="grid-head">Edit </th>
                           <th class="grid-head">Delete</th>
                           <th class="grid-head">
    					   <?php if($this->role != 2 && $this->role != 3 && $this->role != 4){ ?>
                           <input type="submit" name="submit" class="btn btn-sm btn-danger" id="bulk-delete" value="Delete"/>
                           <?php } else { ?>
                           <a href="javascript:void(0);" class="btn btn-sm btn-danger" onclick="showMsg(); retrun;">Delete</a>
                           <?php } ?>
                           <label><input type="checkbox" name="allbox" id="allbox" value="0" onclick="checkAll(this.value);" /> All</label>
                           </th>   
                        </tr>  
                    </thead>		
                    <tbody>
                        <?php $counter =0; foreach($this->paginator as $item): ?>
                                <tr>
                                <td style="vertical-align: middle;"><?php echo $item['name'] ?></td>
                                <td style="text-align:center; vertical-align: middle;">
                                <?php if($item['name']=='Uncategorized'){ ?>
                                &nbsp;
                                <?php } else { ?>
                                    <a class="btn btn-sm btn-warning float-right" href="<?php echo $this->baseUrl(); ?>/admin/post-category/edit/id/<?php echo $item['category_id'] ?>">Edit</a>
                                <?php } ?>                                
                                </td>
                            	<td  style="text-align:center; vertical-align: middle;">
                                <?php if($item['name']=='Uncategorized'){ ?>
                                &nbsp;
                                <?php } else { 
                                if($this->role != 2 && $this->role != 3 && $this->role != 4) { ?>
                                    <a class="btn btn-sm btn-danger" href="javascript:void(0);" onclick="return confirmDelete(<?php echo $item['category_id'] ?> )">Delete </a>
                                <?php } else { ?>
                               <a href="javascript:void(0);" class="btn btn-sm btn-danger" onclick="showMsg(); retrun;">Delete</a>
                               
                                <?php } } ?>
                                </td> 
                            	<td  style="text-align:center; vertical-align: middle;">
                                <?php if($item['name']=='Uncategorized'){ ?>
                                &nbsp;
                                <?php } else { ?>                                
                                    <input type="checkbox" name="bulkdata[]" id="check_<?php echo $counter++;?>" class="form-control" value="<?php echo $item['category_id'] ?>"/>
                                <?php } ?>                                
                                </td>
                                </tr>  
                        <?php endforeach; ?>
                        <tr>
                            <td colspan="4" style="padding: 0; margin: 0;">
                                <?php echo $this->paginationControl($this->paginator, 'Sliding', 'list_pagination.phtml'); ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </form>
        </div>
    </div> <!-- 2nd col end -->
</div> <!-- row end -->

<script type="text/javascript">
    $(function(){
        <?php if(!isset($this->msg)){ ?>
			$('#msg').hide();			
		<?php  } else{		?>
			$('#msg').show().delay(5000).hide('slow');
		<?php } ?>
                
        $('#bulk-delete').click(function() {    		
    		var count_checked = $("input[name='bulkdata[]']:checked").length; // count checked items
    		if(count_checked == 0) {
    			alert("Please select a category to delete.");
    			return false;
    		} 
            else {
    			return confirm("Do you really want to delete these category?");	
            }
    	});
    }); // ready function end
    
    function confirmDelete(id){
    	var r = confirm("Do you really want to delete this category?");
    	if (r == true) {
    	   window.location.assign("<?php echo $this->baseUrl(); ?>/admin/post-category/delete/id/" + id);    
    	} else {
    	   return false;
    	}
	}
    
    function checkAll(a)
	{
	    var total = $('#dataTables-example tr:not(:has(th))').length;
        
		if(a == 0)
		{
			for(q=0;q<total;q++)
			{
                $('#check_'+q).prop('checked', true);
			}
            $('#allbox').val(1);
		}

		if(a == 1)
		{
			for(q=0;q<total;q++)
			{
                $('#check_'+q).prop('checked', false);
			}

            $('#allbox').val(0);
		}
	}
    
    function showMsg(){
        $('#msg').html('<div class="alert alert-danger">You do not have permission to delete categories.</div>').show().delay(5000).hide('slow');
    }
</script>