<div class="w-container">
<div class="post-section">
<div class="w-row">
<div class="w-col w-col-12">  
			<div class="post-head">
			<h1><?php echo $this->page_data['title'];?></h1>
			</div><!--post-heading end-->
			
	<div class="w-row">
<div class="w-col w-col-9 set-summary">
	<img src="<?php echo $this->baseUrl();?>/images/user/image-blocks/<?php echo $this->image_block[10]['block']?>" alt="page image" />
			<!--<div  style="position: relative; width: 800px; height: 450px">
<img style="max-width:100%; max-height: 100%" class="img-responsive" src="<?php echo $this->baseUrl(); ?>/images/posts/800/" alt="" />
</div>-->

<p><?php echo $this->page_data['contents'];?>&#8230; </p>
</div>
</div>
<!--
 <div class="row">
  <div class="col-md-7 job-social-media">
  <ul class="social-icons icon-circle list-unstyled">
  <li class="set-all-icons">Share this on:</li> 
  <li class="set-all-icons"><a href="https://www.facebook.com/sharer/sharer.php?u=http://aliinfotech.com/colinkr/blog/post/id/<?php echo $this->list['page_id']?>" onclick="window.open(this.href, 'newwindow', 'width=500, height=300'); return false;"><i class="fa fa-facebook"></i></a> </li>
					        <li class="set-all-icons"><a onclick="window.open(this.href, 'newwindow', 'width=500, height=300'); return false;" href="https://plus.google.com/share?url=http://aliinfotech.com/colinkr/pages/page/id/<?php echo $this->list['page_id']?>"><i class="fa fa-google-plus"></i></a> </li>     
	    					<li class="set-all-icons"> <a onclick="window.open(this.href, 'newwindow', 'width=500, height=300'); return false;" href="http://www.linkedin.com/shareArticle?mini=true&url=http://aliinfotech.com/colinkr/pages/page/id/<?php echo $this->list['page_id']?>"><i class="fa fa-linkedin"></i></a> </li>
							<li class="set-all-icons"> <a onclick="window.open(this.href, 'newwindow', 'width=500, height=300'); return false;" href="https://twitter.com/intent/tweet?text=<?php echo $this->list['title']?>&url=http://aliinfotech.com/colinkr/pages/page/id/<?php echo $this->list['page_id']?>&summary=<?php echo $this->list['description']?>"><i class="fa fa-twitter"></i></a> </li> 
                            <li class="set-all-icons"> <a onclick="window.open(this.href, 'newwindow', 'width=500, height=300'); return false;" href="https://pinterest.com/pin/create/button/?url=http://aliinfotech.com/colinkr/pages/page/id/<?php echo $this->list['page_id']?>&media=http://aliinfotech.com/colinkr/images/nhot-image/logo.png&description=<?php echo $this->list['description']?>"><i class="fa fa-pinterest"></i></a> </li> 
                            
                            </ul>
                           </div>
  </div>-->

<?php $page_id= $this->page_data['page_id'];?>
			<!-- veiw approved comment-->
			
			<div class="w-row">
			<div class="w-col w-col-10 set-head"> 
			<h2> <i class="fa fa-comments fa-2x"></i> Comments</h2>
			<?php 

foreach ($this->comment as $items):
?>
			<div class="w-row">
	<div class="w-col w-col-9 set-summary">
			<h4> <i class="fa fa-user" ></i> &nbsp <?php echo $items['name'] ?> &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp <i class="fa fa-clock-o" ></i> &nbsp <?php echo $items['comment_date'] ?> </h4>
			<p class="set-comment">
			<?php echo $items['comment'] ?>
			</p>
			


			</div>
			</div>
				<?php  endforeach;?>
			</div>
			</div>
		<!-- end approved comment -->
<div class="w-row">
<div class="w-col w-col-10 set-head"> 
  
			<form id="frm" method="post">
             	 <?php echo $this->form->csrf ?>
				 <h3>Leave a Reply</h3>
				 <div class="msg">
            		</div>
        <input type="hidden" name="page_id" value="<?php echo $page_id; ?>" />       	  
		<h3> * Name:</h3>
	    <?php echo $this->form->name; ?>
		<span id="name-error"></span>
        <h3> * Email:</h3>
	    <?php echo $this->form->email; ?>
		<span id="email-error"></span>
		<h3>* Comment:</h3>
		<?php echo $this->form->comment; ?>
		<span id="comment-error"></span>  &nbsp
	<b>Toatl Charecters:</b>2000/<span id="count"></span>
		<?php echo $this->form->submit?>
            </form>
 
 </div><!--col-10 end-->
 </div><!--row end-->
 
  </div><!--col-md-10 end-->
  </div>
  </div>
  </div>
  
  <script type="text/javascript">
  
  $('#comment').keyup(function() {
    var cs = $(this).val().length;
    $('#count').text(cs);
});
  
    function isValidEmailAddress(emailAddress) {
    var pattern = new RegExp(/^[+a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/i);
     //alert( pattern.test(emailAddress) );
    return pattern.test(emailAddress);
};
    
   $(function(){
   
   $("#first_name").keyup(function(){ 
        var txt = $(this);
        
        if (txt.val() == '' || txt.length == 0)
        {
            $(this).css({"border-color": "red", 
                     "border-width":"1px", 
                     "border-style":"solid"});
            $('#name-error').css('color', 'red').text('Name is required.').show();
        }
        else
        {
            $(this).css({"border-color": "#CCCCCC", 
                     "border-width":"1px", 
                     "border-style":"solid"});
            $('#name-error').hide();
        }
    });
    
    $("#email").keyup(function(){ 
        var txt = $(this);
        
        if (txt.val() == '' || txt.length == 0)
        {
            $(this).css({"border-color": "red", 
                     "border-width":"1px", 
                     "border-style":"solid"});
            $('#email-error').css('color', 'red').text('Eamil is required.').show();
        }
        else if(txt.val() != '' && !isValidEmailAddress(txt.val()))
        {
            $(this).css({"border-color": "red", 
                     "border-width":"1px", 
                     "border-style":"solid"});
            $('#email-error').css('color', 'red').val('Eamil address is not valid.').show();
        }
        else
        {
            $(this).css({"border-color": "#CCCCCC", 
                     "border-width":"1px", 
                     "border-style":"solid"});
            $('#email-error').hide();
        }
    });
    
    $("#comment").keyup(function(){ 
        var txt = $(this);
        
        if (txt.val() == '' || txt.length == 0)
        {
            $(this).css({"border-color": "red", 
                     "border-width":"1px", 
                     "border-style":"solid"});
            $('#comment-error').css('color', 'red').text('Comment is required.').show();
        }        
        else
        {
            $(this).css({"border-color": "#CCCCCC", 
                     "border-width":"1px", 
                     "border-style":"solid"});
            $('#comment-error').hide();
        }
    });
   
    //function saveComments()
    $('#frm').submit(function(e) 
    {    
        var name = $('#first_name');
        if(name.val() == '' || name.length == 0)
        {
            name.css({"border-color": "red", 
                     "border-width":"1px", 
                     "border-style":"solid"});
            name.focus();
            return false;
        }
        
        var email = $('#email');
        if(email.val() == '' || email.length == 0)
        {
            email.css({"border-color": "red", 
                     "border-width":"1px", 
                     "border-style":"solid"});
            email.focus();
            return false;
        }
        
        var comment = $('#comment');
        if(comment.val() == '' || comment.length == 0)
        {
            comment.css({"border-color": "red", 
                     "border-width":"1px", 
                     "border-style":"solid"});
            comment.focus();
            return false;
        }
        
       $.ajax({
             type: 'POST',
             url: "<?php echo $this->baseUrl()?>/pages/save-page-comments",
             data: $(this).serialize(),
                success: function(result) {
               console.log('success : '+ result);
                    if(result == 'success')
                    {
                        $('.msg').html("<div class='alert alert-success'>Comments Added Successfully!</div>").show().delay(5000).fadeOut(1000);
                        name.val('');
                        email.val('');
                        comment.val('');
                    }
				},
                error: function(result)
                {
                     console.log('error : '+ result);
                     if(result == 'error')
                     {
                        $('.msg').html("<div class='alert alert-danger'>Some error in saving record</div>").show().delay(5000).fadeOut(1000);
                        }
                }
        }); //ajax end
             
            //return false;
            e.preventDefault();
    });
  });
 </script>
 