<style>
    footer {
        background-color: #2e2e2e;
        padding: 20px 0;
    }
    footer h5 {
        color: #fff !important;
        font-weight: bolder;
    }
    h6 {
        color: #FFF;
        font-weight: bold;
        font-style: italic;
    }
    .btn-sbsl {
        color: #ffffff;
        background-color: #4EC435;
        border-color: #4EC435;
        border-radius: 0px;
        margin: 5px 0 !important;
    }
    .btn-sbsl:hover {
        color: #1B1C52;
    }
    
    footer p {
        color: #fff !important;
        text-align: center;
    }
    .headline {
        border-bottom: 1px dotted #e4e9f0;
        margin: 20px 0 15px;
    }
    footer ul {
        margin: 0px !important;
        padding: 0px !important;
        
    }
    footer a{
        color: #fff;
    }
    
    footer a:hover{
        color: #4EC435;
    }
    footer i{
        font-size: 18px!important;
    }
</style>
<footer>
    <div class="container"> <!-- /container -->
        <div class="row">
           <div class="col-md-6 col-md-offset-3 ">
		     <div class="resource text-center">
		      <div class="headline">
               <h5><a href="<?php echo $this->baseUrl(); ?>/">Pageiz.com</a></h5>
              </div>			   
              
			  <ul class="list-unstyled">  
              <li><a href="#"><span>Create a Page</span> </a></li>
              <li><a href="#"><span>Become online Marketer</span> </a></li>
              </ul> 
			   </div> </br> <!--resource div end-->
              </div>    <!--col-md-2 end-->
         </div><!--row end-->
            
              <hr/>
              
              <div class="fineprint row">
              
              <p class="text-center">&copy; Copyright 2016. Design and Develop by: <a href="http://aliinfotech.com" target="_blank">aliinfotech.com</a></p>
              
        </div><!--fineprint row ends-->        
    
    </div> <!-- /container -->
</footer>

	
	