<!-- Modal HTML -->
<div id="login-modal" class="modal fade">
    <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title">Login</h4>
                        </div>
                        <div class="modal-body" style="background-color: #FcFcFc; color:#606060; padding: 40px;">
                            <form id="login-frm" action="<?php echo $this->baseUrl(); ?>/index/ajax-login" method="post">
                                
                                <input type="hidden" name="page_id" value="<?php echo $this->list['page_id']; ?>" />
                                <input type="hidden" name="redirect_to" value="<?php echo $this->list['url_slug']; ?>" />
                                <input type="hidden" id="activity" name="activity" />
                                
                                <div class="form-group">
                                    <label>Email: </label>
                                    <input type="email" name="email" required="" class="form-control" placeholder="Enter email address" />
                                </div>
                                <div class="form-group">    
                                    <label>Password: </label>
                                    <input type="password" name="password" required="" class="form-control" placeholder="Enter password" />
                                </div>  
                            
                        </div>
                        <div class="modal-footer">
                            <span id="ajax-loader" class="pull-left" style="display:none;"><img src="<?php echo $this->baseUrl(); ?>/images/admin/ajax-loader.gif" style="width:150px;" /></span>
                            <!--a href="javascript:void(0);" class="pull-left" data-toggle="modal" data-target="#registration-modal" data-dismiss="modal">Get Register</a-->
                            <input type="submit" class="btn btn-lg btn-primary" value="Log In"/>
                            <button type="button" class="btn btn-lg btn-default" data-dismiss="modal">CLOSE</button>
                            </form>
                        </div>
                    </div>
    </div>
</div>

<div id="registration-modal" class="modal fade">
    <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title">Registration</h4>
                        </div>
                        <div class="modal-body" style="background-color: #FcFcFc; color:#606060; padding: 40px;">
                            <div id="reg-msg" style="display: none;"></div>
                            <form id="registration-frm" action="" method="post">
                                <input type="hidden" name="redirect_to" value="<?php echo $this->list['url_slug']; ?>" />
                                <div class="form-group">
                                    <label>First Name: </label>
                                    <input type="text" name="first_name" required="" class="form-control" placeholder="Enter email address" />
                                </div>
                                <div class="form-group">
                                    <label>Last Name: </label>
                                    <input type="text" name="last_name" required="" class="form-control" placeholder="Enter email address" />
                                </div>
                                <div class="form-group">
                                    <label>Email: </label>
                                    <input type="email" name="email" required="" class="form-control" placeholder="Enter email address" />
                                </div>
                                
                        </div>
                        <div class="modal-footer">
                            <span id="reg-ajax-loader" class="pull-left" style="display:none;"><img src="<?php echo $this->baseUrl(); ?>/images/admin/ajax-loader.gif" style="width:150px;" /></span>
                            <input type="submit" class="btn btn-lg btn-primary" value="Submit"/>
                            <button type="button" class="btn btn-lg btn-default" data-dismiss="modal">CLOSE</button>
                            </form>
                        </div>
                    </div>
    </div>
</div>