<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
<style>
.products_details{
	display:none;
}
body{
	background:#E9EBEE;
}
.thumbnail{
	margin-bottom:0;
	border:0;
	border-radius:0;
}
.col-md-12.thumbnail{
	// box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);
}
.col-md-12.thumbnail.comment{
	// height:200px;
	margin-bottom: 15px;
	    padding: 0 15px 0 15px;
		border:0;
		background:#F6F7F9;
		display:none;
}
::-webkit-input-placeholder { /* WebKit, Blink, Edge */
    color:    lightgray !important;
	font-size:12px !important;
}
:-moz-placeholder { /* Mozilla Firefox 4 to 18 */
   color:    lightgray !important; font-size:12px !important;
}
::-moz-placeholder { /* Mozilla Firefox 19+ */
   color:    lightgray !important; font-size:12px !important;
   
}
:-ms-input-placeholder { /* Internet Explorer 10-11 */
   color:    lightgray !important; font-size:12px !important;
}
#comment_btn > button{
	margin-top:10px;margin-bottom:10px;border: 1px solid #365899; background: transparent; color: white;
	transition: all 0.5s ease-out;border-radius:0;background:#365899;
}

.col-md-12.thumbnail {
    padding-left: 10px;
    padding-bottom: 10px;
    border-top: 1px solid lightgray;
    border-bottom: 1px solid lightgray;
    padding-top: 10px;
}
hr {
    margin-top: 48px;
    margin-bottom: 4px; 
    border: 0;
    border-top: 1px solid #eee;
}
.textarea.form-control {
    width:200px;
    resize:none;
    overflow:hidden;
    font-size:18px;
    height:1.1em;
    padding:2px;
}

/* Loader Overlay */
.loader-overlay {
  position: fixed;
  top: 0;
  bottom: 0;
  right: 0;
  left: 0;
  background-color: #783393;
  opacity:0.8;
  z-index: 1;
  
}
/* Loader */
.loader {
  position: fixed;
  top: 50%;
  right: 0;
  left: 0;
  width: 350px;
  height: 100px;
  margin: 0 auto;
  z-index: 2;
  text-align: center;
  font-size: 250%; 
  line-height: 0.9;
  color: white;
  font-family: 'Open Sans', sans-serif;
  font-weight: 300;
  text-transform: uppercase;
  -webkit-animation: loader-enter 0.3s 1 cubic-bezier(0.47, -0.02, 0.05, 0.91);
}
.loader .loader-stripe {
  display: block;
  position: relative;
  width: 50%;
  margin: 1px auto 0 auto;
}
.loader .loader-stripe:after {
  content: '';
  display: block;
  position: absolute;
  box-shadow: 1px 2px 0 rgba(255, 255, 255, 0.8);
  width: 20%;
  height: 2px;
  -webkit-animation: loader-stripe 0.17s infinite alternate linear;
}
@-webkit-keyframes loader-stripe {
  0% {
    left: 0px;
  }
  100% {
    left: 80%;
  }
}
@-webkit-keyframes loader-enter {
  0% {
    opacity: 0;
    letter-spacing: 22px;
  }
  100% {
    letter-spacing: initial;
  }
}
.navbr {
  margin-top:10px;
  position: relative;
  margin-bottom:10px;
}

.dropdown-toggle {
  padding: .5em 1em;
  background: #777;
  border-radius: .2em .2em 0 0;
  color:white;
  text-decoration:none;
}
.dropdown-toggle:hover {
	text-decoration:none;
	color:white;
}
.dropdown-toggle:focus {
	text-decoration:none;
	color:white;
}
ul.dropdown {
  display: none;
  position: absolute;
  top: 100%;
  margin-top: 1.5em;
  background: #777;
  min-width: 12em;
  padding: 0;
  border-radius: 0 0 .2em .2em;
  z-index: 1;
}
ul.dropdown.dropdown-menu-right:before {
	content: "";
    position: absolute;
    right: 7px;
    top: -14px;
    width: 0;
    height: 0;
    border: 7px solid #777777;
    /* border-style: solid; */
    border-color: transparent transparent #777777 transparent;
    z-index: 9999;
}

ul.dropdown li {
  list-style-type: none;
}
ul.dropdown li a {
  text-decoration: none;
  padding: .5em 1em;
  display: block;
}
ul.dropdown li a:hover {
  color:white;
}
.sort_link{
	text-decoration:none;
	color:white;
}
</style>

<div class="loader-overlay">
  <div class="loader">
    Sorting
    <span class="loader-stripe"></span>
  </div>
</div>
	<div class="col-md-6 col-md-offset-3">
		<nav class="navbr pull-right">
			<a class="dropdown-toggle" href="#" title="Menu">Sort by:</a>
			<ul class="dropdown dropdown-menu-right">
			  <li><a onclick="sorting('210','2')" class="sort_link" href="#">Social</a></li>
			  <li><a onclick="sorting('210','3')" class="sort_link" href="#">Service</a></li>
			  <li><a onclick="sorting('210','1')" class="sort_link" href="#">Products</a></li>
			</ul>
		</nav>
		<div id="sorting_result"></div>
		
	</div>
	
<script>
	$(document).ready(function(){
		$('.loader-overlay').hide();
		// Dropdown toggle
		$('.dropdown-toggle').click(function(){
		  $(this).next('.dropdown').toggle();
		});

		$(document).click(function(e) {
		  var target = e.target;
		  if (!$(target).is('.dropdown-toggle') && !$(target).parents().is('.dropdown-toggle')) {
			$('.dropdown').hide();
		  }
		});
	});
	function sorting(page_id,type){
		// alert(page_id+' '+ type);
		$('.loader-overlay').show();
		$.ajax({
             type: 'POST',
             url: "<?php echo $this->baseUrl()?>/pages/sorting",
             data: { 
			 page_id: page_id,
			 type:type 
			},
                success: function(result) {
					var result = JSON.parse(result);
					// console.log(result);
					// var result1 = JSON.parse(result);
					$('#sorting_result').html(result);
					$('.loader-overlay').hide();
					// var result = $.trim(result);
                    
				},
                error: function(result)
                {
                     alert('error');
                }
            }); //ajax end
	}
	function opencomment(id){
		$('#comments_'+id).toggle();
	}
</script>
