<div id="page-wrapper" style="min-height: 500px;">
    
        <?php
        if (isset($_SESSION["token"])) { ?>
        <div class="row">
            <a href="<?php echo $this->baseUrl(); ?>/admin/gd/index?logout=1"><button type="button" class="btn btn-md btn-primary pull-right">Log Out</button></a>         
        </div>
        <br />
    <div class="row">
       <div class="col-lg-12">
            <div class="page-title"><strong>Visitors Information</strong></div>            
       <br />
       <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover dataTables-example">
		<thead>
            <tr>
    			<th style="text-align:center;">User Type</th>
    			<th style="text-align:center;">Count of Sessions</th>
                <th style="text-align:center;">Browser</th>
                <th style="text-align:center;">Country</th>
                <th style="text-align:center;">Region</th>
                <th style="text-align:center;">Users</th>
            </tr>
		</thead>
        <tbody>
    		<?php	 	
    		//printing each row.
            if($this->by_user_type->getRows() != null){
        		foreach ($this->by_user_type->getRows() as $row) { 	 	
        			echo "<tr><td>".$row[0]."</td><td style="."text-align:center;".">".$row[1]."</td><td>".$row[2]."</td><td>".$row[3]."</td><td>".$row[4]."</td><td style="."text-align:center;".">".$row[5]."</td></tr>"; 	 
        		}
            }
            ?>
        </tbody>	 
        </table>
       </div>
       </div>
      </div>
      <br />
      <div class="row">
       <div class="col-lg-12">
       <div class="page-title"><strong>Pageviews</strong></div>
       <br />
       <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover dataTables-example">	 
		<thead>
            <tr>
                <th style="text-align:center;">Date</th>
    			<th style="text-align:center;">Page</th>
                <th style="text-align:center;">Operating System</th>
                <th style="text-align:center;">User Type</th>
                <th style="text-align:center;">Source</th>
                <th style="text-align:center;">Pageviews</th>
    	   </tr>
        </thead>
        <tbody>	 	
    		<?php	 	
    		//printing each row.
            if($this->by_pageviews->getRows() != null){
        		foreach ($this->by_pageviews->getRows() as $row) { 	 	
        			echo "<tr><td style="."text-align:center;".">".date('m/d/Y', strtotime($row[0].''))."</td><td>".$row[1]."</td><td>".$row[2]."</td><td>".$row[3]."</td><td>".$row[4]."</td><td style="."text-align:center;".">".$row[5]."</td></tr>";
        		}	 
            }
        ?>
        </tbody>	 	
        </table>
       </div>
       </div>
    </div>
    <br />
    <div class="row">
        <div class="col-lg-12">
       <div class="page-title"><strong>Traffic Sources</strong></div>
       <br />
       <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover dataTables-example">	 
		<thead>
            <tr>
                <th style="text-align:center;">Full Referrer</th>
    			<th style="text-align:center;">Source / Medium</th>
                <th style="text-align:center;">Social Network</th>
                <th style="text-align:center;">Organic Searches</th>
    	   </tr>
        </thead>
        <tbody>	 	
    		<?php	 
            if($this->by_search->getRows() != null){	
    		  foreach($this->by_search->getRows() as $row)
                {
                    echo "<tr><td style="."text-align:center;".">".$row[0]."</td><td style="."text-align:center;".">".$row[1]."</td><td style="."text-align:center;".">".$row[2]."</td><td style="."text-align:center;".">".$row[3]."</td></tr>";
                }	 
            }
        ?>
        </tbody>	 	
        </table>
       </div>
       </div>
    </div>
    <br />
    <div class="row">
        <div class="col-lg-12">
       <div class="page-title"><strong>Social Interactions</strong></div>
       <br />
       <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover dataTables-example">	 
		<thead>
            <tr>
                <th style="text-align:center;">Social Source</th>
    			<th style="text-align:center;">Social Action</th>
                <th style="text-align:center;">Social Entity</th>
                <th style="text-align:center;">Social Actions</th>
    	   </tr>
        </thead>
        <tbody>	 	
    		<?php	 
            if($this->by_social_interactions->getRows() != null){	
    		  foreach($this->by_social_interactions->getRows() as $row)
                {
                    echo "<tr><td style="."text-align:center;".">".$row[0]."</td><td style="."text-align:center;".">".$row[1]."</td><td style="."text-align:center;".">".$row[2]."</td><td style="."text-align:center;".">".$row[3]."</td></tr>";
                }	 
            }
        ?>
        </tbody>	 	
        </table>
       </div>
       </div>
    </div>
    <?php } else {?>
    <div class="row">
        <div class="col-md-12">
            <div class="page-title"><h1>Press the button to connect with your google analytics account</h1></div>
            <p style="text-align: center;">
                <a href="<?php echo $this->authUrl; ?>"><button type="button" class="btn btn-md btn-primary">Connect</button></a>
            </p>
        </div>
    </div>
    <?php } ?>
</div>

<script type="text/javascript">
 $(function () { 
        $('.dataTables-example').dataTable();
 });
 </script>