<script src="<?php echo $this->baseUrl();?>/js/admin/ckeditor/ckeditor.js"></script>
<style>
#heading{
	font-size: 24px;	
}
.labels{
color: #444444;	
}
</style>

<div class="row">
    <div class="col-md-12">
	<ul class="menu-links">
    <li><a href="<?php echo $this->baseUrl(); ?>/admin/post-category/index" title="New Post Category">New Post Category</a></li>
	<li><strong><a href="<?php echo $this->baseUrl(); ?>/admin/posts/new-post" title="Create new post"> New Post</a></strong></li>       
    <li><a href="<?php echo $this->baseUrl(); ?>/admin/posts/index" title="View list"> List</a></li>       
	<li><a href="<?php echo $this->baseUrl(); ?>/admin/post-comments" title="View Recent Comments"> Recent Comments</a></li>       
	</ul>
	</div>
</div>

<div class="row">
<div class="col-md-12">
     <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" >	

<div class="row">	 
 <div class="col-md-8">
 <div id="msg">
	<?php echo $this->msg ?> 
</div>
</div>
</div>
			<!-- row1 start-->
  <div class="row">   
  	<div class="col-md-9">
  <?php echo $this->form->heading;?>
	<div class="row">
	  <div class="col-md-8">
	  <span class="set-parma" style="font-size:11px"><strong>Parmalink:</strong>
       <span id="p_link" style="font-size: 11x"></span>
	  </span>
	  <input type="text" name="url" id="url"  style="font-size: 0px"/>
		  </div>
	 </div>
	
	</div>
	
	<div class="col-md-3">
		   <button class="btn btn-md btn-primary set-save" value="1" name="submit" type="submit">Save as Draft   </button>
	<?php if($this->role!=4){ ?>
        <button class="btn btn-md btn-primary"  value="0" name="submit" type="submit">Publish</button>
    <?php }?>
    </div>
  </div> <!-- row1 end-->
  
  <div class="col-md-9" style="padding: 0;">
  <!-- row 2 start-->
  <div class="row">
	<div class="col-md-12">
	 <div class="set-ck">
	<?php echo $this->form->contents ?>
	</div>
	</div> 
    <br />
    <div class="col-md-12">
        <div class="col-md-4">
		<?php echo $this->form->tags; ?>
    	</div>
    	<div class="col-md-5">
    		<?php echo $this->form->keyword_content; ?>
    	</div>
    	<div class="col-md-3">
    		<label for="is_comment" style="text-align:center;">No Comments
            </label>
    		
    		<?php echo $this->form->is_comment; ?>
    	</div>
    </div>
    <br />
	<div class="col-md-12">
	 <div class="set-ck">
		<?php echo $this->form->description_content; ?>
	 </div>
	</div>
    </div><!-- row 2 end-->
    </div>
    
    <div class="col-md-3">
		<?php echo $this->form->image;?>
		<br/>
			<img src="<?php echo $this->baseUrl();?>/images/user/posts/200X200/placeholder.png" alt="placeholder" width="160" />
    
    <div class="panel panel-default" style="margin-top: 15px;">
			<div class="panel-heading">
				<h3 class="panel-title">
					Categories
				</h3>
			</div>
            <div class="panel-body" style="height: 250px; overflow: scroll;">
                <div id="chk-list" style="margin-left: -40px;">
                    <?php foreach($this->chk_list as $item): 
                         echo $item['name'];
                    endforeach;?>
                </div>
			</div>
	</div>
	</div> <!-- right col end -->
    
		</form>
        <div class="row">
            <div class="col-md-9"></div>
            <div class="col-md-3">
                <form method="POST" action="<?php echo $this->baseUrl();?>/admin/posts/new-category" style="margin-right: 15px;">
                    <div class="form-group">
                        <?php echo $this->cat_form->name; ?>
                    </div>
                    <div class="form-group">
                        <?php echo html_entity_decode($this->cat_form->parent_id); ?>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Add New Category" class="btn btn-primary pull-right" />
                    </div>
                </form>
            </div>
        </div>
    </div><!--main col-md-12 end-->
	</div><!--main row end-->
	
<script type="text/javascript">
$(function(){
   $('#chk-list>ul').attr('id','tree');
   $('#chk-list>ul#tree').checktree(); 
});
     window.onload = function () { 
  $('#url').hide();
     
 <?php if(!isset($this->msg)){ ?>
      $('#msg').hide();
    <?php  } else{
    ?>
      $('#msg').show().delay(10000).hide('slow');

    <?php } ?>
    
   <?php if(isset($this->errorSlug)){ ?>
  var url = "<?php echo $this->site_url;?>/blog/post/";  	       
		   $("#url").val('<?php echo $this->errorSlug ?>');  
            $("#p_link").text(url).append('<?php echo $this->errorSlug ?>');  
	//alert("<?php echo $this->errorSlug ?>");
   <?php  } ?>
    
	//wysiwyg settings 
	var roxyFileman = '<?php echo $this->baseUrl(); ?>/js/admin/fileman/index.html';
         
            CKEDITOR.replace( 'contents',
            {
                filebrowserBrowseUrl:roxyFileman,
                filebrowserImageBrowseUrl:roxyFileman+'?type=image',
                removeDialogTabs: 'link:upload;image:upload',
                enterMode	: Number(2)
            });   
            
           // $("#p_link").text(url);         
    }
    
    var delay = (function(){
      var timer = 0;
      return function(callback, ms){
        clearTimeout (timer);
        timer = setTimeout(callback, ms);
      };
    })();
    
     var url = "<?php echo $this->site_url;?>/blog/post/";
     
     // make slug from title
	     $("#heading").keyup(function(){ 
            var Text = $(this).val();
            Text = Text.toLowerCase();
            var outputString = Text.replace(/([~!@#$%^&*()_+=`{}\[\]\|\\:;'<>,.\/? ])+/g, '-').replace(/^(-)+|(-)+$/g,'');
            $("#url").val(outputString);  
            $("#p_link").text(url).append(outputString);      
    });
     
	 /*
      // make custom slug
    $("#url").keyup(function(){ 
            var Text = $(this).val();
            Text = Text.toLowerCase();
           
           var outputString = Text.replace(/([~!@#$%^&*()_+=`{}\[\]\|\\:;'<>,.\/? ])+/g, '-').replace(/^(-)+|(-)+$/g,'');
           // var regExp = /\s+/g;
            //Text = Text.replace(regExp,'-');
            
            delay(function(){
                $("#url").val(outputString);
                $("#p_link").text(url).append(outputString);
            }, 1000 );
    });
    
	
    $("#tags").blur(function(){
        var result = setCommaSeparetedValues($(this));
        $(this).val(result);
    });
    
    $("#keyword_content").blur(function(){
        var result = setCommaSeparetedValues($(this));
        $(this).val(result);
    });

	
    function setCommaSeparetedValues(id)
    {
        var data = $(id).val();
         data = data.toLowerCase();
        var outputString = data.replace(/([~!@#$%^&*()_+=`{}\[\]\|\\:;'<>.\/? ])+/g, ', ').replace(/^(-)+|(-)+$/g,'');
        data = outputString.split(/[ ,]+/).filter(function(v){return v!==''}).join(', ');
        return data;
    }*/
    </script>