<div class="row">
    <div class="col-md-12">
	<ul class="menu-links">
	<li><a href="<?php echo $this->baseUrl(); ?>/admin/posts/new-post" title="Create new post"> New Post</a></li>       
    <li><strong><a href="<?php echo $this->baseUrl(); ?>/admin/posts/index" title="View posts">Posts List</a></strong></li>       
	</ul>
	</div>
</div>
								
<div class="row">
	<div class="col-md-12">
		<div id="msg">
			<?php echo $this->msg ?>
		</div>
		<div class="clearfix">
		</div>
		
		<div class="table-responsive">
			<table class="table table-striped table-bordered table-hover" id="dataTables-example">
	 			
	<thead>
				 										<tr>													<!--<th class="grid-head"> Post Title</th>-->
																<th class="grid-head">Name </th>
																<th class="grid-head">Email </th>
																<th class="grid-head">Comment </th>
																<th class="grid-head">Date </th>
																<th class="grid-head">Status </th>
																<th class="grid-head">Action</th>
																<th class="grid-head">Edit</th>
																<th class="grid-head">Delete</th>
                                                        	</tr>
														</thead>		
														<tbody> 
                                          
														<?php if (count($this->data)) {
                                                        foreach ($this->data as $item): ?>
														<tr class="odd gradeX">
															<!--<td> <?php echo $item['heading'] ?> </td> -->
															<td style="text-align:center;"> <?php echo $item['name'] ?> </td> 
															<td style="text-align:center;"> <?php echo $item['email'] ?> </td> 
															<td> <?php echo $item['comment'] ?> </td> 
															<td style="text-align:center;"> <?php echo date('m/d/Y h:i A', strtotime($item['comment_date'])) ?> </td> 
															<td style="text-align:center;">
															<?php if($item['status']== 1){?>
															Pending<?php }elseif($item['status']== 3){ ?>
															Rejected<?php }else{ ?>
															Approved<?php } ?>
															</td>
															<td style="text-align:center;">
															<?php if($item['status']== 1){?>
															<a class="btn btn-sm btn-primary" href="#" onclick="return confirmApprove(<?php echo $item['pc_id'] ?> )" >Approve</a><?php }elseif($item['status']== 3){ ?>
															<a class="btn btn-sm btn-primary" href="#" onclick="return confirmApprove(<?php echo $item['pc_id'] ?> )" >Approve</a> <?php }else{ ?>
															<a class="btn btn-sm btn-danger" href="#" onclick="return confirmReject(<?php echo $item['pc_id'] ?> )" >Reject</a> <?php } ?> </td>
                                                            <td style="text-align:center;"><a class="btn btn-sm btn-warning" href="<?php echo $this->baseUrl(); ?>/admin/post-comments/edit/id/<?php echo $item['pc_id'] ?>">Edit</a></td>
                                                            <td style="text-align:center;"><a class="btn btn-sm btn-danger" href="#" onclick="return confirmDelete(<?php echo $item['pc_id'] ?> )" >Delete</a></td>
														</tr>  
															<?php endforeach; }?> 
														</tbody>

						 								</table>
														</div><!-- div responsive end-->
												</div>

                                </div>  

  <script language="Javascript" type="text/javascript">
 window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('#msg').hide();
			
		<?php  } else{
		?>
			$('#msg').show();
		<?php } ?>
        
        $('#dataTables-example').dataTable(
           {
		      "aaSorting": [[ 4, "desc" ]] // 4th index or 5th column in descending order
	       }
        );
 }
 
 function confirmDelete(id){
	var r = confirm("Are you sure to Delete this Comment! " );
	if (r == true) {
	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/post-comments/delete-post-comment/id/" + id);    
	} else {
	return false;
	}
	}
	
  function confirmApprove(id){

	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/post-comments/approve-post-comment/id/" + id);    

	}
	
  function confirmReject(id){

	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/post-comments/reject-post-comment/id/" + id);    

	}

 </script>