<div class="row">
    <div class="col-md-12">
    	<ul class="menu-links">       
    	   <li><a href="<?php echo $this->baseUrl(); ?>/admin/post-comments" title="Post Comments List">Back to list</a></li>       
    	</ul>
	</div>
</div>

<div class="row">
    <div class="col-md-12">
    <div id="msg">
			<?php echo $this->msg ?>
		</div>
        
        <form class="form-horizontal" action="" method="post">
            
            <input type="hidden" name="pc_id" value="<?php echo $this->pc_id ?>" />
            
            <div class="row form-group">
                <div class="col-md-6">
				<tr><td><strong>Name</strong></td></tr>
                    <?php echo $this->form->name; ?>
                </div>
                <div class="col-md-6">
				<tr><td><strong>Email</strong></td></tr>
                    <?php echo $this->form->email; ?>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-12">
				<tr><td><strong>Description</strong></td></tr>
                    <?php echo $this->form->comment; ?>
                </div>
            </div>
            <div class="row form-group">                
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary pull-right">Save</button>
			   </div>
            </div>
        </form>		
    </div>
 </div>
 
 <script type="text/javascript">
    window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('#msg').hide();
			
		<?php  } else{
		?>
			$('#msg').show().delay(3000).hide('slow');
		<?php } ?>
 
 }
 </script>