<div class="row">
    <div class="col-md-12">
	<ul class="menu-links">
	<li><a href="<?php echo $this->baseUrl(); ?>/admin/posts/new-post" title="Create new post"> New Post</a></li>       
    <li><strong><a href="<?php echo $this->baseUrl(); ?>/admin/posts/index" title="View posts">List</a></strong></li>       
	</ul>
	</div>
</div>
								
<div class="row">
	<div class="col-md-12">
		<div id="msg">
			<?php echo $this->msg ?>
		</div>
		<div class="clearfix">
		</div>
		
		<div class="table-responsive">
        <form method="post" name="data_table">
			<table class="table table-striped table-bordered table-hover" id="dataTables-example">
														<thead>
														<tr>
																<th class="grid-head"> Post Title</th>
																<th class="grid-head">Name </th>
																<th class="grid-head">Email </th>
																<th class="grid-head">Comment </th>
																<th class="grid-head">Date </th>
																<th class="grid-head">Status </th>
																<th class="grid-head">Action</th>
																<th class="grid-head">Edit</th>
																<th class="grid-head">Delete</th>
                                                                <th class="grid-head">
                                                                <input type="submit" name="submit" class="btn btn-danger btn-sm" id="submit" value="Delete"/>
                                                                <label><input type="checkbox" name="allbox" id="allbox" value="0" onclick="checkAll(this.value);" /> All</label>
                                                                </th>
                                                        	</tr>
														</thead>		
														<tbody> 
                                          
														<?php if (count($this->data)) {
                                                        $counter=0; foreach ($this->data as $item): ?>
														<tr class="odd gradeX">
															<td> <?php echo $item['heading'] ?> </td> 
															<td style="text-align:center;"> <?php echo $item['name'] ?> </td> 
															<td style="text-align:center;"> <?php echo $item['email'] ?> </td> 
															<td> <?php echo $item['comment'] ?> </td> 
															<td style="text-align:center;"> <?php echo date('m/d/Y h:i A', strtotime($item['comment_date'])) ?> </td> 
															<td style="text-align:center;">
															<?php if($item['status']== 1){?>
															Pending<?php }elseif($item['status']== 3){ ?>
															Rejected<?php }else{ ?>
															Approved<?php } ?>
															</td>
															<td style="text-align:center;">
															<?php if($item['status']== 1){?>
															<a class="btn btn-sm btn-primary" href="#" onclick="return confirmApprove(<?php echo $item['pc_id'] ?> )" >Approve</a><?php }elseif($item['status']== 3){ ?>
															<a class="btn btn-sm btn-primary" href="#" onclick="return confirmApprove(<?php echo $item['pc_id'] ?> )" >Approve</a> <?php }else{ ?>
															<a class="btn btn-sm btn-danger" href="#" onclick="return confirmReject(<?php echo $item['pc_id'] ?> )" >Reject</a> <?php } ?> </td>
                                                            <td style="text-align:center;"><a class="btn btn-sm btn-warning" href="<?php echo $this->baseUrl(); ?>/admin/post-comments/edit/id/<?php echo $item['pc_id'] ?>">Edit</a></td>
                                                            <td style="text-align:center;"><a class="btn btn-sm btn-danger" href="#" onclick="return confirmDelete(<?php echo $item['pc_id'] ?> )" >Delete</a></td>
														<td  style="text-align:center;"><input type="checkbox" name="bulkdata[]" id="check_<?php echo $counter++;?>" class="form-control" value="<?php echo $item['pc_id'] ?>"/></td>
                                                        </tr>  
															<?php endforeach; }?> 
														</tbody>

						 								</table>
                                                        </form>
														</div><!-- div responsive end-->
												</div>

                                </div>

  <script language="Javascript" type="text/javascript">
 window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('#msg').hide();
			
		<?php  } else{
		?>
			$('#msg').show();
		<?php } ?>
        
        $('#dataTables-example').dataTable(
           {
		      "aaSorting": [[ 4, "desc" ]],
              "iDisplayLength": 50,
              "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
              "aoColumnDefs": [{'bSortable': false, 'aTargets': [7,8,9]}]
	       }
        );
 }
 
    function confirmDelete(id){
	var r = confirm("Are you sure to Delete this Comment?" );
	if (r == true) {
	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/post-comments/delete-comment/id/" + id);    
	} else {
	return false;
	}
	}
	
    function checkAll(a)
	{
	    var total = $('#dataTables-example tr:not(:has(th))').length;
        
		if(a == 0)
		{
			for(q=0;q<total;q++)
			{
                $('#check_'+q).prop('checked', true);
			}
            $('#allbox').val(1);
		}

		if(a == 1)
		{
			for(q=0;q<total;q++)
			{
                $('#check_'+q).prop('checked', false);
			}

            $('#allbox').val(0);
		}
	}
    
  function confirmApprove(id){
	
	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/post-comments/approve-comment/id/" + id);    
	}
	
  function confirmReject(id){
	
	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/post-comments/reject-comment/id/" + id);    
	}

    jQuery(function($) {
	
	$("form input[id='submit']").click(function() {  // triggred submit
    		
    		var count_checked = $("[name='bulkdata[]']:checked").length; // count the checked
    		if(count_checked == 0) {
    			alert("Please select a Posts to delete.");
    			return false;
    		} 
    		 else {
    			return confirm("Are you sure you want to delete these posts?");	
    		  }		
    	});
     }); // jquery end
 </script>