<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#tab1">Mail Chimp</a></li>
  <li><a data-toggle="tab" href="#tab2"></a></li>
</ul>

<div class="tab-content">
  <div id="tab1" class="tab-pane fade in active">
    <h3>Integrate Email Marketing Software (Mail Chimp)</h3>
    <br />
    <div id="msg"><?php echo $this->msg; ?></div>
    
        <form class="form-horizontal" method="POST" action="">
            <div class="row col-md-10 col-md-offset-1">
                <div class="form-group">
                    <?php echo $this->form->api_key; ?>            
                </div>
            
                <div class="form-group">
                    <?php echo $this->form->list_id; ?>
                    <span></span>
                </div>
                <div class="form-group">
                    <?php //echo $this->form->submit; ?>
                    <input type="submit" value="Save" class="btn btn-lg btn-success pull-right" />
                </div>
            </div>
        </form>
    
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-info">
                <strong>Note:</strong>
                <br />
                <div>- To get API Key go to your Mail Chimp <strong>Account Settings->Extras->API Keys</strong> and Click on <strong>Create a Key</strong> button.</div>
                <br />
                <div>- To get List ID go to Lists section, Create a new List or select an existing List and find <strong>Settings->List name &amp; defaults.</strong> Then you will find <strong>List ID</strong>.</div>
            </div>
        </div>
    </div>    
  </div>

  <div id="tab2" class="tab-pane fade">
    <h3></h3>
  </div>
</div>

<script type="text/javascript">
    $(function(){
        <?php if(!isset($this->msg)){ ?>
        $('#msg').hide();
        <?php  } else{ ?>
          $('#msg').show().delay(10000).hide('slow');   
        <?php } ?>
    });
</script>