 <form  action=" " method="post">
									<?php //echo $this->form->csrf ?>
                                       	<table class="table-responsive table table-striped table-bordered table-hover space-mangead">
                                    	<tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
										<tr ><td colspan="2"><strong><a href="#">Basic Information</a></strong></td></tr> 
         												
                                       <?php echo $this->form->url_video; ?>
								                       <tr><td>&nbsp;</td><td>
                                        <?php echo $this->form->submit?>
										</td></tr>   
                                        </table>
                                   </form>