<style>
.table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
    border-top: none !important;
	}
.jumbotron.btn {
    font-size: 18px !important;
}
</style>
<div class="container panel-entry">
 <div class="row" style="margin-top:40px;">
  <div class="col-lg-13">

   <div class="window flat shadow">
    <!--<div class="caption">
        <span class="icon icon-windows"></span>
        <div class="title">Join Us</div>
      <button class="btn-min"></button> 
        <button class="btn-max"></button> 
        <button class="btn-close"></button> 
  
			          		</div>
-->    <div class="content">
<div class="join-2">

<div class="row">
   
   <div class="col-md-10 col-md-offset-1 clearfix">
   
   <div class="panel panel-default">
           <div class="panel-heading colr" style="color:white; background-color:#428BCA;">
           <h4 class="panel-title">Recover Your Password</h4>
           </div>
          <div class="panel-body">
		    
   <div class="col-md-12 clearfix">
<form name="recover-password" id="recover-password" method="<?php echo $this->escape($this->form->getMethod()) ?>" 
action="<?php echo $this->escape($this->form->getAction()) ?>">    
<table class="table table-hover table-responsive">
	<tr><td colspan="2"><?php echo $this->msg ?></td></tr>
  <tr><td><div class="input-control text" data-role="input-control"><?php echo $this->form->email ?></div></td>
</tr>
<tr><td colspan="2">
<?php echo $this->form->submit ?></td></tr>

</table>
</form>
</div>
	 </div>
	   </div>
		
 <!-- ./ content -->
        </div>
        </div> <!--row div end-->
		
		
		</div>  <!--join-us-div closed-->
		</div>
<!-- ./ window -->
</div>

<!-- ./ lg--->
</div>
<!-- ./ row-->
</div>


<!-- ./ container -->
</div>