<style>
 .set-table{
 float:left;
}
</style>    
    <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                         <div class="col-lg-12 col-md-26">
                         <h3></h3>
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-2">
                                    <i class="fa fa-video-camera fa-5x"></i>
                                </div>
								
						 <!-- <div class="col-xs-7">
                             <form action="<?php echo $this->baseUrl()?>/admin/video-list" action="post">
                                <div class="input-group custom-search-form col-xs-6 text-right" style="padding-top:20px">
                                <input type="text" name="query_string" id="query_string" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            </form>
                          </div>-->
								
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Testimonials List</div>
                            
                                </div>
                            </div>
                        </div>
						
						 <div class="panel-body">
                                
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                <div class="table-responsive">
													<table cellpadding="0" cellspacing="0" border="0" class="responsive dynamicTable display table table-bordered  set-table" width="100%">
														<thead>
														
															<?php 

if($this->msg == 1){
$this->msg = "<div class='alert alert-success'>Testimonial Deleted</div>";	
} 

if($this->msg == 3){
$this->msg = "<div class='alert alert-success'>You cant' delete all testimonial must keep at least one Featured Testimonial </div>";	
} 

if($this->msg == 2){
$this->msg = "<div class='alert alert-success'>Please try again!</div>";	
} 
if(isset($this->msg)){

?>														<tr id='msg'><td colspan='5'><?php echo $this->msg ?></td></tr>
<?php } ?>
													  		
															<tr> 
																<th style="text-align:center;">Name</th>
															    <th style="text-align:center;">Email</th>
																<th style="text-align:center;">Featured</th>
																<th style="text-align:center;">Edit </th>
																<th style="text-align:center;">Delete</th>
                                                        	</tr> 
														</thead>		
														<tbody>
                                          
														<?php if (count($this->paginator)){ ?>
													
														<?php foreach ($this->paginator as $item): ?>
														<tr class="odd gradeX">
															<td style="text-align:center;">
															<?php echo $item['first_name'] ?>&nbsp;<?php echo $item['last_name'] ?>
															</td>
                                                             <!--<td style="text-align:center;">
															<?php echo $item['last_name'] ?>
															</td> -->
															<td style="text-align:center;">
															<?php echo $item['email'] ?>
															</td> 
															<!--<td style="text-align:center;">
															<?php echo $item['is_featured'] ?>
															</td>-->

														<td style="text-align:center;">
														 <?php 
																if($item['is_featured'] == 1) { ?>
															   <i>Yes</i> 
																<?php
																}else{
																	?>
																<i> No</i>
																										   
																<?php 	
																} ?></td>															
															
                                                            <td style="text-align:center;"><a class="btn btn-sm btn-warning float-right" href="<?php echo $this->baseUrl(); ?>/admin/index/edit-testimonial/id/<?php echo $item['test_id'] ?>">Edit</a></td>
															 <td  style="text-align:center;"><a class="btn btn-danger" href="#" onclick="return confirmDelete(<?php echo $item['test_id'] ?> )" href="">Delete </a></td>
														</tr>
															<?php endforeach; ?>
															<tr><td colspan='9' style="text-align:center;">
															<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>
															</td>
															</tr><?php }else{ ?>
											
															<tr><td colspan="7"><h4>There are no Testimonials in List!</h4></td></tr>
															<?php } ?>
														</tbody>

						 								</table>
														</div><!-- div responsive end-->
												</div>

                               
                                
                                
                                </div>
				 		
                        <a href="#">
                            <div class="panel-footer">
                                
								 </a>
                            </div>
                       
                    </div>
                </div>
                
                
          
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



  <script language="Javascript" type="text/javascript">
 
 function confirmDelete(id){
	var r = confirm("Are you sure to Delete this Testimonial! " );
	if (r == true) {
	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/index/delete-testimonial/id/" + id);    
	} else {
	return false;
	}
	}
 </script>