<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="<?php echo $this->layout()->metadata['description']; ?>"/>
    <meta name="keywords" content="<?php echo $this->layout()->metadata['keywords']; ?>"/>
    <title>pageiz.com</title>
	<link href="<?php echo $this->baseUrl();?>/css/default/bootstrap-3.3.6-dist/css/bootstrap.min.css" rel="stylesheet" >
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
   
	<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="<?php echo $this->baseUrl();?>/css/default/bootstrap-3.3.6-dist/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
	
	    <!-- Custom styles for this template -->
    <link href="<?php echo $this->baseUrl();?>/css/default/navbar-fixed-top.css" rel="stylesheet">

	 <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	
	<link rel="shortcut icon" href="<?php echo $this->baseUrl();?>/images/favicon.ico">
	
	<link href="<?php echo $this->baseUrl();?>/css/default/style.css" rel="stylesheet" media="all" />
	<script src="<?php echo $this->baseUrl();?>/js/default/jquery-min.js"></script>
	<script src="<?php echo $this->baseUrl();?>/slider/jssor/js/jssor.slider.mini.js"></script>
</head><!--/head-->


  <body>

    <?php echo $this->render("header.phtml"); ?>      
    <?php echo $this->layout()->content; ?>
    <?php echo $this->render("footer.phtml"); ?>
    <script src="<?php echo $this->baseUrl();?>/css/default/bootstrap-3.3.6-dist/js/bootstrap.min.js"></script>
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="<?php echo $this->baseUrl();?>/css/default/bootstrap-3.3.6-dist/js/ie10-viewport-bug-workaround.js"></script>
      <!-- Script to Activate the Carousel -->
<script>
    jQuery(document).ready(function ($) {
        var options = { $AutoPlay: true };
        var jssor_slider1 = new $JssorSlider$('myCarousel', options);
    });
</script>
   </body>
</html>