<style>
.set-log{
	padding-right: 0px;
	}
.navbar-toggle {
    position: relative;
    float: right;
    padding: 9px 10px;
    margin-top: 46px !important;   
    margin-right: 15px;
    margin-bottom: 8px;
    background-color: transparent;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 4px;
}
@media(max-width:768px) {
    #wrapper {
		padding-top: 90px; 
    }
	.set-log{
		float: right !important;
		    padding-right: 0px;
	}
	.side-nav {
    position: fixed;
    top: 27px !important;
    left: 225px;
    width: 225px;
    margin-left: -225px;
    border: none;
    border-radius: 0;
    overflow-y: auto;
    background-color: #222;
    bottom: 0;
    overflow-x: hidden;
    padding-bottom: 40px;
}
}
@media(min-width:769px) {
    #wrapper {
        padding-left: 180px !important;
    }

    #page-wrapper {
        padding: 10px !important;
    }
}
</style>   
   <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" >
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <?php if($this->role==6){?>
                    <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>/admin/members"><img src="<?php echo $this->baseUrl(); ?>/images/admin/logo1.png" class="img-responsive"></a>
                <?php } else { ?>
                    <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>/admin/index"><img src="<?php echo $this->baseUrl(); ?>/images/admin/logo1.png" class="img-responsive"></a>
                <?php } ?>
                				
                <a class="set-home" href="<?php echo $this->baseUrl(); ?>"><li class="fa fa-home"></li>&nbsp;&nbsp;<span><?php echo $this->baseUrl(); ?></span></a> 
				 <!--
				 <ul class="nav set-home set-menu top-nav">
                				<li class="dropdown">
                    <a href="<?php echo $this->baseUrl(); ?>/admin/posts/new-post" class="dropdown-toggle" data-toggle="dropdown" style="font-size:13px"><i class="fa fa-plus"></i>&nbsp;&nbsp;New</a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?php echo $this->baseUrl(); ?>/admin/posts/new-post"><i class="fa fa-thumb-tack fa-fw"></i>New Post</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->baseUrl(); ?>/admin/page/new-page"><i class="fa fa-file-o fa-fw"></i>New Page</a>
                        </li>
                    </ul>
                </li>
            </ul>-->
				
            </div>
			<!-- Top Menu Items -->	
            <ul class="nav navbar-right set-log top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="admin-set"><?php echo $this->name ?></span>&nbsp;&nbsp;<i class="fa fa-user"></i><b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <?php if($this->role==6){?>
                            <a href="<?php echo $this->baseUrl()?>/admin/user/update-password/id/<?php echo $this->logged_user_id; ?>"><i class="fa fa-fw fa-key"></i> Change Password</a>
                            <?php } else { ?>
                                <a href="<?php echo $this->baseUrl()?>/admin/user/edit/id/<?php echo $this->logged_user_id; ?>"><i class="fa fa-fw fa-user"></i> Profile</a>
                            <?php } ?>
                        </li>
                      
                        <li class="divider"></li>
                        <li>
                            <a href="<?php echo $this->baseUrl(); ?>/admin/login/logout"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
			
            <?php if($this->role!=6){?>
			<ul class="nav navbar-right set-log top-nav">
                				<li class="dropdown">
                    <a href="<?php echo $this->baseUrl(); ?>/admin/posts/new-post" class="dropdown-toggle" data-toggle="dropdown" style="font-size:16px"><i class="fa fa-files-o fa-fw"></i></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?php echo $this->baseUrl(); ?>/admin/posts/new-post"><i class="fa fa-thumb-tack fa-fw"></i>&nbsp;&nbsp;New Post</a>
                        </li>
                        <?php if($this->role != 2 && $this->role != 3 && $this->role != 4){ ?>
                        <li>
                            <a href="<?php echo $this->baseUrl(); ?>/admin/page/new-page"><i class="fa fa-file-o fa-fw"></i>&nbsp;&nbsp;New Page</a>
                        </li>
                        <?php }?>
                    </ul>
                </li>
            </ul>
            
			<?php if($this->role != 2 && $this->role != 3 && $this->role != 4){ ?>
			<ul class="nav navbar-right set-log top-nav">
                				<li class="dropdown">
                    <a href="<?php echo $this->baseUrl(); ?>/admin/gallery/new-photo" class="dropdown-toggle" data-toggle="dropdown" style="font-size:16px"><i class="fa fa-picture-o fa-fw"></i></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?php echo $this->baseUrl(); ?>/admin/gallery/new-photo"><i class="fa fa-picture-o fa-fw"></i>&nbsp;&nbsp;Add Photo</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->baseUrl(); ?>/admin/videos/new"><i class="fa  fa-video-camera fa-fw"></i>&nbsp;&nbsp;Add Video</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <?php } }?>