<!-- See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination-->
<?php if ($this->pageCount): ?>
    <ul class="pagination pull-right" style="margin-right: 10px;"><!-- Previous page link --> 
<!--?php if (isset($this->previous)): ?>
    <li><a href="<?php //echo $this->url(array('page' => $this->previous)); ?>">&lt;Previous</a>
<?php //else: ?> 
    <span class="disabled">&lt;Previous</span></li>
<?php //endif; ?>-->
<?php foreach ($this->pagesInRange as $page): ?>
<?php if ($page != $this->current): ?> 
<li><a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>
<?php else: ?> 
<li><a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>
<?php endif; ?>
<?php endforeach; ?> <!-- Next page link -->
<!--?php if (isset($this->next)): ?> 
<li><a href="<?php //echo $this->url(array('page' => $this->next)); ?>">Next&gt;</a>
<?php //else:?>
<span class="">Next&gt;</span></li>
<?php //endif; ?>-->
</ul>
<?php endif;?>