<div class="about-us container-fluid text-center" style="background:url('/images/newlanding/about.png'); background-repeat:no-repeat; background-size:cover;">
	<h1>About Pageiz</h1>
	<h4>We are a multinational team of tech geeks. Among us, you’ll find experts in various fields who stay creative and open to new knowledge and experiences.</h4>
</div>
<div class="about-us2 container-fluid text-center">
	<div class="wwa-row row">
		<div class="col-md-8">
			<img src="/images/newlanding/wwa.jpg"  class="img-responsive" style="box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);">
		</div>
		<div class="who-we-are col-md-4 text-left">
			<h3>Who We Are</h3>
			<p>
				We're a dynamic software company that creates simple, beautiful landing pages that allow businesses to grow large and devoted audiences. We believe compelling online marketing doesn't need to be time consuming and tedious.
			</p>
			<p>
				Our differentiating features include Marketing Automation, Landing Pages, Image Editor, Responsive Design, Forms, Webinars and Perfect Timing. Our dedicated team of experts provides five-star customer support via email, phone, and chat 24/7.	
			</p>
		</div>
	</div>
	<div class="wwd-row row">
		<div class="what-we-do col-md-4 text-left">
			<h3>What We Do</h3>
			<p>
				We offer a complete suite of simple-yet-powerful solutions, scaled and customized for small and large companies. Our tools are designed for organizations that want to implement effective, high-impact campaigns that drive marketing ROI.
			</p>
			<p>
				Pageiz email marketing and online campaign management platform helps entrepreneurs build targeted subscriber lists and send high-impact newsletters, video emails, and follow-up campaigns. It offers marketing automation, responsive email design, hundreds of ready-to-use email templates, and landing page creator.
			</p>
		</div>
		<div class="col-md-8 text-left">
			<img src="/images/newlanding/wwd.jpg" class="img-responsive" style="box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);">
		</div>
	</div>
</div>