<div class="contact-us container-fluid text-center" style="background:url('/images/newlanding/contact.png');background-repeat:no-repeat;backround-size:cover;">
	<h1>Contact Pageiz</h1>
	<h3>Questions? This contact form is the best way to get in touch with us.</h3>
</div>
<div class="contact-us2 container text-center">
	<h4>Drop us a note and we'll get back to you asap!</h4>
	<div class="sub-contact2 col-md-8 col-md-offset-2 text-left">
		<form id="contact_form" action="" method="POST">
			<div class="form-group">
				<label for="pwd">Name</label>
				<input type="text" class="form-control" id="cf_name" name="cf_name" placeholder="Name" required>
			</div>
			<div class="form-group">
				<label for="email">Email address:</label>
				<input type="email" class="form-control" id="email" placeholder="Email Address" required>
			</div>
			<div class="form-group">
				<label for="message">Message</label>
				<textarea type="email" class="form-control" id="cf_message" name="cf_message" style=" resize: none;" rows="6" placeholder="Your Message" required></textarea>
			</div>
			<div class="form-group">
				<button class="btn btn-primary pull-left" type="submit">Send Message</button>
			</div>
		</form>
	</div>
</div>