 
        <div class="col-md-12">
          <h2 class=" text-center">Start promoting your business!</h2>
		  <div style="background-color: #8cbbcc"> 
  <center><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/business1.png" /></center>
 </div>
 <hr/>
 <p>
				Every business is looking for growth in their surrounding. Small and medium size businesses are facing great issues of every day sales 
				and growth. There are new types of challenges after the fast spread of internet, young people have opened new online businesses and 
				traditional business owner are unable to cop with the new trends. More and more people in Malaysia are buying online as companies have 
				created trust of their services, delivery and payment. There are web services which are helping businesses and people to
				promote and sell online but there is still need of more customized services and we are introducing one. Pageiz.com can help your business in 
				reaching to clients and customers nearby locations and nations wide, we are creating an active community of
				marketers/sales executive, graphics designers, content writers and many other types, who will help business marketing and sales promotions. 
				Our services are highly affordable for everyone in these tough times. Please have a look at the following features of our
				services.  
				<ul>
				<li>Create a business page on pageiz.com to give more clear idea of what you do.</li>
				<li>Get a human readable address as pageiz.com/your-business-name.</li>
				<li>Get know how many people like your page/pages everyday.</li> 
				<li>Share your pages on Facebook and other social media.</li> 
				<li>As friends and family to share your banner page or get our marketing services.</li>
				<li>You have full control on your page banner, contents and comments management.</li>
				<li>Get more businesses queries by getting comments on your pages. </li>
				<li>Get help of the marketers network which can really boost your business in your localities. (Coming soon)</li>
</ul>			
</p>         
	 <p><a class="btn btn-default" href="<?php echo $this->baseUrl()?>/index/packages" role="button">Create a Page Now &raquo;</a></p>
       </div>
     
        <div class="col-md-12">
          <h2 class=" text-center"> Become an Internet Marketer</h2>
		  <div style="background-color: #ff9205"> 
  <center><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/marketers1.png" /></center>
 </div>
 <hr/>
 <p>
				Becoming a marketer at pageiz.com will help you in converting your online time into money. If you are an experience online marketer
we welcome you on-board or if you are very new to online marketing we can help you in understanding it, we have great tutorials and online help for making you a great marketer and salesman. Registration for marketers is fully free. By joining our network you will be able to do following things.
<ul>
<li> We will offer you a share in our Pay Per Click model where local businesses are adverting with us.</li>
<li> We will bring marketing jobs to you from our clients, as SEO, eMail marketing and business development.</li>
<li> You will be able to create your groups for more effective representation of your expertise.</li>
<li> You will find a lot of tutorial and help guides in one place. </li>
<li> We are good at development and we have developed special CMS, email marketing and analytic tools for your help.</li>
<li> If you banner or web designing you will get jobs for it. </li>
</ul>			
</p>         
		 <p><a class="btn btn-default" href="<?php echo $this->baseUrl()?>/index/m-reg" role="button">Register Now &raquo;</a></p>
       </div>	 
	 
        <div class="col-md-12">
          <h2 class=" text-center">Why is to join pageiz.com?</h2>
		  <div style="background-color: #89b0ff"> 
  <center><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/members2.png" /></center>
 </div>
 <hr/>
 <p>
			Join us to become our members, we are starting the cleanest and easiest Daily Deals section (Very soon) which is a go get model. Once you will 
login your will find a very limited deals of one kind only in your nearest location. As one day you will see mobile and tablets offers only 
and the other day you will find Home and Kitchen offers only. We will share schedules of offers also so that you could plan your 
visit to your nearest stores. We will not keep any inventory with us as most you us (Malaysian) love to buy from nearest shops/markets not live web store.
Only 1% to 2% of Malaysians are buy online where as 98% are buying from their nearest locations. In 2016 nearly 70% Malaysian population is using internet which makes internet
the best way to find offers comparing with other types of media as newspaper, magazines and TV.We are creating the module and will soon be live.</li>
</p>         
		 <p><a class="btn btn-default" href="#" role="button">Membership Opening Soon &raquo;</a></p>
       </div>		 