<style>
    .panel{
       box-shadow: 0 0 10px grey !important;
     }
     .panel-footer, .panel-header{ 
        background-color: #1B1C52;
        padding: 10px;
        color: #fff;
     }
     #btn-checkout {
        border: 0;
        padding: 5px 20px;
     }
     .panel-body {
        padding: 30px 40px;
     }
</style>
<div class="container" style="padding-top: 100px; padding-bottom:20px;">
     <div class="row">
       <div class="col-md-6 col-md-offset-3">  

    <div class="panel panel-info">
	
    <div class="panel-header">
        <strong>Register as a Marketer</strong>
    </div>
    
    <form action="" method="post" role="form">   
    <div class="panel-body">
        <div id="msg"><?php echo $this->msg;?></div>
            <div class="form-group">
                <?php echo $this->form->first_name;?>                
            </div>
            <div class="form-group">
                <?php echo $this->form->email;?>
            </div>
            <div class="form-group">
                <?php echo $this->form->pwd;?>
            </div>
            <div class="form-group">
                <?php echo $this->form->confirm_pass;?>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->form->submit;?>
                </div>
            </div>         
    </div>
    <div class="panel-footer">
        <div class="row">
            <div class="col-md-12" style="min-height: 46px;">
                
            </div>
        </div>
    </div>
    </form>
</div>
         </div> 
		 
       </div>  <!--main row div end-->
     </div>

<script type="text/javascript">
    $(function(){
        
    });
    
</script>