<div class="header container-fluid">
	<div class="container">
    <nav class="navbar navbar-default">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span> 
          </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/index/become-member">Become a Member</a></li>
                <li><a href="/index/packages">Create a Page</a></li>
                <li><a href="/index/poster-samples">Banner/Poster Samples</a></li>
                <?php if(isset($this->user_role) && isset($this->logged_user_id)) {?>
				<li><a href="<?php echo $this->baseUrl(); ?>/mem-pages/index"> <i class="fa fa-user fa-home"></i> Dashboard</a></li>
				<?php } else {?>
				<li><a href="<?php echo $this->baseUrl();?>/authentication/login">Login</a></li>
				<?php }?> 
                <li><a href="/marketer/index">Become a Marketer</a></li>
                <!-- li><a href="/categories/index">Resellers</a></li -->
                <li><a href="/blog">Blog <span class="sr-only">(current)</span></a></li>
          </ul>
        </div>
    </nav>
</div>
</div>

