<header>
    <div class="container text-center">
        <div class="col-md-8 col-md-offset-2">                     
            <img src="<?php echo $this->baseUrl();?>/images/newlanding/pageizlogo.png" class="img-responsive">
            <h2>Get, keep and grow more customers</h2>
            <form action="<?php echo $this->baseUrl(); ?>/index/search" method="get" role="search">
            <input type="text" autocomplete="off" name="q" id="q" placeholder="Search Business Pages..." class="form-control">
            <button type="submit">Pageiz Search</button>
			</form>
        </div>
    </div>
</header>
    <div class="second container text-center">
        <h1>TOP FEATURES TO HELP YOU GROW WHERE YOUR CUSTOMERS GO</h1>
        <div class="row">
            <div class="col-md-4">
                <img src="<?php echo $this->baseUrl();?>/images/newlanding/1.png" class="img-responsive">
                <h4>Mobile-Friendly Templates</h4>
                <p>Start building your page with hundreds of high-performing templates all of which work just as beautifully on a smartphone screen as they do on a desktop monitor.</p>
            </div>   
            <div class="col-md-4">
                <img src="<?php echo $this->baseUrl();?>/images/newlanding/2.png" style="" class="img-responsive">
                <h4>Drag-and-Drop Customization</h4>
                <p>Make every page your own by dropping new elements where you want them. Text, images, buttons, and even widgets such as countdown timers all snap into place with ease.</p>
            </div>        
            <div class="col-md-4">
                <img src="<?php echo $this->baseUrl();?>/images/newlanding/3.png" class="img-responsive">
                <h4>Pageiz Capture Pop-Ups</h4>
                <p>Add Leadboxes opt-in forms to any page or site to collect leads and automatically deliver your best content.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <img src="<?php echo $this->baseUrl();?>/images/newlanding/4.png" style="" class="img-responsive">
                <h4>1-Click Signup Links</h4>
                <p>Add Pageizlinks to your emails and let subscribers instantly change their email preferences, opt in for extra content, or sign up for Pageiz.</p>
            </div>   
            <div class="col-md-4">
                <img src="<?php echo $this->baseUrl();?>/images/newlanding/5.jpg" class="img-responsive">
                <h4>No Coding Needed</h4>
                <p>Edit, customize, clone, and publish pages just by clicking and typing. What you see is what your visitors get.</p>
            </div>        
            <div class="col-md-4">
                <img src="<?php echo $this->baseUrl();?>/images/newlanding/6.jpg" style="" class="img-responsive">
                <h4>Designed for Conversion</h4>
                <p>Pageiz templates are based on extensive research to discover what really prompts customers to take action.</p>
            </div> 
        </div>
        <div class="row">
            <div class="col-md-4">
                <img src="<?php echo $this->baseUrl();?>/images/newlanding/7.png" style="" class="img-responsive">
                <h4>Instant Feedback</h4>
                <p>You can be able to get feedback for your landing page and product from users using instant feedback.</p>
            </div>   
            <div class="col-md-4">
                <img src="<?php echo $this->baseUrl();?>/images/newlanding/8.png" class="img-responsive">
                <h4>Email Marketing</h4>
                <p>You can be able to do email marketing to them easily using our drag and drop email marketing system.</p>
            </div>        
            <div class="col-md-4">
                <img src="<?php echo $this->baseUrl();?>/images/newlanding/9.png" style="" class="img-responsive">
                <h4>Page Posts</h4>
                <p>You can be able to upload posts to your landing page where users can be able to comment on it, and can be able to share it as well.</p>
            </div> 
        </div>
    </div>
    <div class="third-fluid container-fluid">
        <div class="third container text-center">
        <h1>COMPLETE ONLINE MARKETING SYSTEM</h1>
        <h4>Improvize your marketing programs with integrated features from Pageiz.</h4>
        <div class="row">
            <div class="email_marketing col-md-6 text-left" style="padding: 0  50px;">
                <h2>Email Marketing</h2>
                <p><strong>Grow your lists, increase conversions, and optimise your audience engagement</strong> with beautiful emails and autoresponders, high-converting web forms, laser-sharp segmentation, and unique delivery tools.</p>
            </div>
            <div class="col-md-6">
                <figure class="screen">
                    <img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/newlanding/emailer1.png">
                </figure>
            </div>     
        </div>
        </div>
    </div>
    <div class="fourth-fluid container-fluid">
        <div class="fourth container text-center">
        <div class="row " style="margin-top: 100px;">
            <div class="col-md-6">
                <figure class="screen2">
                    <img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/newlanding/landing.png">
                </figure>
            </div>
            <div class="email_marketing col-md-6 text-left" style="padding: 0  50px;">
                <h2>Landing Pages</h2>
                <p><strong>Create and publish high-converting squeeze, video, and promo pages</strong> with our advanced optimization tools and integrations. You can be able to put slider popups on it as well to gather data from client so that you can use it for email marketing.</p>
            </div>     
        </div>
        </div>
    </div>
    
  <script type="text/javascript">
  $('document').ready(function(){
	  // var isShow = true;
	 // $(window).scroll(function() {
					// if ($(document).scrollTop() > 800) {
						// if(isShow){
						  // $('#myModal').modal('show');
						  // isShow=false;
						// }
						
					// } 
		  // });
		  $("#subscriber-form").submit(function(e){
			e.preventDefault();
			
			var formData = $(this).serialize();
			// alert(formData);return;
			$('#sub-btn').html('<i class="fa fa-spinner fa-spin"></i>');
			var name = $('#customer_name').val();
			var getURL = $('#base_url').val()+'/index/homepage-subscribers';
			console.log(getURL);
			$.ajax({
			type    : 'POST',
			data    : formData,
			async: true,
			url : getURL,
			success: function (result) {
				// alert(result);return;
				$('#email').val('');
				$('#sub-btn').html('<i class="fa fa-check" aria-hidden="true"></i> Subscribed');
				setTimeout(function() { $('#myModal').modal('hide'); }, 2000);
			return;

			},
			error:function (error) {
				alert('please try again!');
			}
			});
			
		  });
  });
	
  </script>