<style>
	body{
		background:#36465D;
	}
</style>
<div class="container">

	<div class="row" style="background:white;padding:40px;">
		<div class="col-md-6 text-center">
			<img src="../images/lmm.png" class="img-responsive">
		</div>
		<div class="col-md-6 text-center" style="padding-top:40px;">
			<?php
			if($this->package == '1'){ ?>
				<h3  style="    font-size: 3em;">1 Business Page</h3>
				<h4><strong>Price:</strong> <span style="color:#54D33F;font-size: 2em;">RM400</span></h4>
				<h4>Every page has a unique URL</h4>
				<a href="/index/checkout?p=<?php echo $this->package; ?>" class="btn btn-success btn-lg" style="background:#36465D;border:1px solid #36465D;border-radius:0;margin-top:10px;">Checkout</a>
			<?php
			}
			?>
			<?php
			if($this->package == '4'){ ?>
				<h3  style="    font-size: 3em;">4 Business Pages</h3>
				<h4><strong>Price: </strong><span style="color:#54D33F;font-size: 2em;">RM1500</span></h4>
				<h4>Every page has a unique URL</h4>
				<a href="/index/checkout?p=<?php echo $this->package; ?>" class="btn btn-success btn-lg" style="background:#36465D;border:1px solid #36465D;border-radius:0;margin-top:10px;">Checkout</a>
			<?php
			}
			?>
			<?php
			if($this->package == '8'){ ?>
				<h3  style="    font-size: 3em;">8 Business Pages</h3>
				<h5><strong>Price: </strong><span style="color:#54D33F;font-size: 2em;">RM2600</span></h5>
				<h4>Every page has a unique URL</h4>
				<a href="/index/checkout?p=<?php echo $this->package; ?>" class="btn btn-success btn-lg" style="background:#36465D;border:1px solid #36465D;border-radius:0;margin-top:10px;">Checkout</a>
			<?php
			}
			?>
		</div>
	</div>	
		<?php
			if($this->package == '1'){ ?>
			<div class="row"  style="padding:40px;background:#EEEEEE;">
				<div class="col-md-12 text-center">
					<div class="row text-center">
						<h2 style="margin:30px auto;">1 Business Page</h2>
						<div class="col-md-3">
							<div class="col-md-12"  style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);padding:20px;background:white;height:278px;">
								<img src="https://d30y9cdsu7xlg0.cloudfront.net/png/6437-200.png" class="img-responsive" style="width:60px;height:60px;margin:auto;margin-bottom:20px;">
								<h4>1 Interactive Landing Page</h4>
								<p>You will get an interactive landing page, with video, banner option on it. You can be able to share your page & post to social media as well</p>
							</div>
						</div>
						<div class="col-md-3" >
							<div class="col-md-12" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);padding:20px;margin-bottom:20px;background:white;height:278px;">
								<img src="https://maxcdn.icons8.com/Share/icon/User_Interface//content1600.png" class="img-responsive" style="width:60px;height:60px;margin:auto;margin-bottom:20px;">
								<h4>1500 Posts</h4>
								<p>You can be able to create 1500 posts on your business page timeline. You can be able to share your post to social media as well</p>
							</div>
							
						</div>
						<div class="col-md-3" >
						<div class="col-md-12" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);padding:20px;margin-bottom:20px;background:white;height:278px;">
							<img src="https://cdn0.iconfinder.com/data/icons/documents-and-folders-1/128/_multiple_text_documents-512.png" class="img-responsive" style="width:60px;height:60px;margin:auto;margin-bottom:20px;">
							<h4>1000 Words Contents</h4>
							<p>You will be provided 1000 words content per page posts on your business page timeline. You can be able to show or hide it on your page</p>
						</div>
							
						</div>
						<div class="col-md-3">
							<div class="col-md-12"  style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);padding:20px;margin-bottom:20px;background:white;height:278px;">
								<img src="https://maxcdn.icons8.com/Share/icon/Time_And_Date//calendar1600.png" class="img-responsive" style="width:60px;height:60px;margin:auto;margin-bottom:20px;">
								<h4>365 Days</h4>
								<p>You will get access to run your business page for 365 days. You can be able to manage your business page for 1 year.</p>
							</div>	
							
						</div>
						
					</div>
					<a href="/index/checkout?p=<?php echo $this->package; ?>" class="btn btn-success btn-lg" style="background:#61D64E;border:1px solid #61D64E;border-radius:0;margin-top:35px;">Checkout</a>
				</div>
			</div>
				
		<?php	
			}elseif($this->package == '4'){ ?>
				<div class="row"  style="padding:40px;background:#EEEEEE;">
				<div class="col-md-12 text-center">
					<div class="row text-center">
						<h2 style="margin:30px auto;">4 Business Pages</h2>
						<div class="col-md-3">
							<div class="col-md-12"  style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);padding:20px;background:white;height:278px;">
								<img src="https://d30y9cdsu7xlg0.cloudfront.net/png/6437-200.png" class="img-responsive" style="width:60px;height:60px;margin:auto;margin-bottom:20px;">
								<h4>4 Interactive Landing Pages</h4>
								<p>You will get an interactive landing page, with video, banner option on it. You can be able to share your page & post to social media as well</p>
							</div>
						</div>
						<div class="col-md-3" >
							<div class="col-md-12" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);padding:20px;margin-bottom:20px;background:white;height:278px;">
								<img src="https://maxcdn.icons8.com/Share/icon/User_Interface//content1600.png" class="img-responsive" style="width:60px;height:60px;margin:auto;margin-bottom:20px;">
								<h4>2000 Posts per Page</h4>
								<p>You can be able to create 1500 posts on your business page timeline. You can be able to share your post to social media as well</p>
							</div>
							
						</div>
						<div class="col-md-3" >
						<div class="col-md-12" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);padding:20px;margin-bottom:20px;background:white;height:278px;">
							<img src="https://cdn0.iconfinder.com/data/icons/documents-and-folders-1/128/_multiple_text_documents-512.png" class="img-responsive" style="width:60px;height:60px;margin:auto;margin-bottom:20px;">
							<h4>3500 Words Contents</h4>
							<p>You will be provided 1000 words content per page posts on your business page timeline. You can be able to show or hide it on your page</p>
						</div>
							
						</div>
						<div class="col-md-3">
							<div class="col-md-12"  style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);padding:20px;margin-bottom:20px;background:white;height:278px;">
								<img src="https://maxcdn.icons8.com/Share/icon/Time_And_Date//calendar1600.png" class="img-responsive" style="width:60px;height:60px;margin:auto;margin-bottom:20px;">
								<h4>365 Days</h4>
								<p>You will get access to run your business page for 365 days. You can be able to manage your business page for 1 year.</p>
							</div>	
							
						</div>
						
					</div>
					<a href="/index/checkout?p=<?php echo $this->package; ?>" class="btn btn-success btn-lg" style="background:#61D64E;border:1px solid #61D64E;border-radius:0;margin-top:35px;">Checkout</a>
				</div>
			</div>
		<?php		
			}elseif($this->package == '8'){ ?>
				<div class="row"  style="padding:40px;background:#EEEEEE;">
				<div class="col-md-12 text-center">
					<div class="row text-center">
						<h2 style="margin:30px auto;">8 Business Pages</h2>
						<div class="col-md-3">
							<div class="col-md-12"  style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);padding:20px;background:white;height:278px;">
								<img src="https://d30y9cdsu7xlg0.cloudfront.net/png/6437-200.png" class="img-responsive" style="width:60px;height:60px;margin:auto;margin-bottom:20px;">
								<h4>8 Interactive Landing Pages</h4>
								<p>You will get an interactive landing page, with video, banner option on it. You can be able to share your page & post to social media as well</p>
							</div>
						</div>
						<div class="col-md-3" >
							<div class="col-md-12" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);padding:20px;margin-bottom:20px;background:white;height:278px;">
								<img src="https://maxcdn.icons8.com/Share/icon/User_Interface//content1600.png" class="img-responsive" style="width:60px;height:60px;margin:auto;margin-bottom:20px;">
								<h4>2500 Posts per Page</h4>
								<p>You can be able to create 1500 posts on your business page timeline. You can be able to share your post to social media as well</p>
							</div>
							
						</div>
						<div class="col-md-3" >
						<div class="col-md-12" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);padding:20px;margin-bottom:20px;background:white;height:278px;">
							<img src="https://cdn0.iconfinder.com/data/icons/documents-and-folders-1/128/_multiple_text_documents-512.png" class="img-responsive" style="width:60px;height:60px;margin:auto;margin-bottom:20px;">
							<h4>7000 Words Contents</h4>
							<p>You will be provided 1000 words content per page posts on your business page timeline. You can be able to show or hide it on your page</p>
						</div>
							
						</div>
						<div class="col-md-3">
							<div class="col-md-12"  style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);padding:20px;margin-bottom:20px;background:white;height:278px;">
								<img src="https://maxcdn.icons8.com/Share/icon/Time_And_Date//calendar1600.png" class="img-responsive" style="width:60px;height:60px;margin:auto;margin-bottom:20px;">
								<h4>365 Days</h4>
								<p>You will get access to run your business page for 365 days. You can be able to manage your business page for 1 year.</p>
							</div>	
							
						</div>
						
					</div>
					<a href="/index/checkout?p=<?php echo $this->package; ?>" class="btn btn-success btn-lg" style="background:#61D64E;border:1px solid #61D64E;border-radius:0;margin-top:35px;">Checkout</a>
				</div>
			</div>
		<?php		
			}
		?>
		
	

</div>