<style>
    .panel{
      /* box-shadow: 0 0 10px grey !important;*/
     }
     .panel-footer, .panel-header{ 
        background-color: #404040;
        padding: 10px;
        color: #fff;
     }     
     .panel-header p{
        margin-bottom: 5px;
     }
     #btn-checkout, #btn-login {
        border: 0;
     }
     .panel-body {
        padding: 30px 40px;
     }
	 .errors{
	color: #ff0000;
}
</style>

<div class="container" style="padding: 40px 0;">
     <div class="row">
       <div class="col-md-6 col-md-offset-3">  
        <div class="alert alert-warning" style="color: #000;">
            <p style="font-size: 20px; font-weight: bold;">Order Information:</p>
            <strong>Order: <?php echo $this->package_name; ?> for 365 days</strong><br />
			<strong>Page(s): <?php echo $this->pages; ?></strong><br />
            <strong>Package Cost: RM<?php echo $this->package_price;?></strong>
            <?php if(isset($this->biz_name)) {?>
            <p style="font-size: 20px; font-weight: bold;">Banner/Poster Samples Information:</p>
            <strong>Business Name: <?php echo $this->biz_name; ?></strong><br />
            <strong>Business Requirements: <?php echo $this->biz_requirements; ?></strong><br />
            <strong>Sample Category: <?php echo $this->cat_name; ?></strong><br />
            <strong>Selected Samples: <?php echo $this->selected_samples; ?></strong>
            <?php }?>
        </div>
        
        <div id="msg"><?php echo $this->msg;?></div>
        
        <div class="panel panel-info">
    	
        <div class="panel-header">
            <p style="font-size: 20px;">Please Enter Contact Details</p>
        </div>
        
        <form action="" method="post" role="form">   
		<!--input type="hidden" name="package_name" value="<?php echo $this->package_name; ?>"/>
		<input type="hidden" name="package_price" value="<?php echo $this->package_price;?>" />
		<input type="hidden" name="pages" value="<?php echo $this->pages; ?>" /-->
        <div class="panel-body">
		        <div class="form-group">
        <p class="errors">All Fields are required</p>
		</div>
                <div class="form-group">
                    <?php echo $this->order_form->name;?>
                </div>
                <div class="form-group">
                    <?php echo $this->order_form->contact_number;?>
                </div>
				<div class="form-group">
                    <?php echo $this->order_form->email;?>
                </div>
				
        </div>
        <div class="panel-footer">
            <div class="row">
           
                <div class="col-md-12 text-center">
                    <input id="btn-login" type="submit" class="btn btn-lg btn-success" value="Submit Order"/>
                </div>
            </div>
        </div>
        </form>
        </div>
    </div>

		 
       </div>  <!--main row div end-->
     </div>

<script type="text/javascript">
    $(function(){
        <?php if(!isset($this->msg)){ ?>
			$('#msg').hide();			
		<?php  } else { ?>
			$('#msg').show().delay(10000).hide('slow');
		<?php } ?>
        
        $('#submit-label').remove();
        
        <?php if(isset($this->email)){?>
        $('#email').val('<?php echo $this->email;?>');
        $('#contact_number').val('<?php echo $this->contact_number;?>');
        <?php }?>
    });
</script>