<div class="container">

	<form method="method" action="https://www.sandbox.paypal.com/cgi-bin/webscr">
		<input type="hidden" name="business" value="hamza-facilitator@missyjubilee.com">
        
        <!-- Specify a Buy Now button. -->
        <input type="hidden" name="cmd" value="_xclick">
        
        <!-- Specify details about the item that buyers will purchase. -->
        <input type="hidden" name="item_name" value="package1">
        <input type="hidden" name="item_number" value="package1">
        <input type="hidden" name="amount" value="10">
        <input type="hidden" name="currency_code" value="USD">
        
        <!-- Specify URLs -->
        <input type='hidden' name='cancel_return' value='http://pageiz.com/index/cancel'>
        <input type='hidden' name='return' value='http://pageiz.com/index/success'>
        
        <!-- Display the payment button. -->
        <input type="image" name="submit" border="0"
        src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_LG.gif" alt="PayPal - The safer, easier way to pay online">
        <img alt="" border="0" width="1" height="1" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" >
	</form>

</div>