<div class="container panel-entry" style="min-height: 500px;">
 <div class="row" style="margin-top:100px;">
  <div class="col-lg-10 col-lg-offset-1">

   <div class="window flat shadow">
    <!--<div class="caption">
        <span class="icon icon-windows"></span>
        <div class="title">Join Us</div>
      <button class="btn-min"></button> 
        <button class="btn-max"></button> 
        <button class="btn-close"></button> 
  
			          		</div>
-->    <div class="content">
<div class="join-2">

<div class="row">
   
   <div class="col-md-10 col-md-offset-1 clearfix">
   
   <div class="panel panel-default">
           <div class="panel-heading colr" style="color:white; background-color:black; border-color:black;">
           <h1 class="panel-title">Recover Your Password</h1>
           </div>
          <div class="panel-body">
		  
       <div class="col-md-10 col-md-offset-1 clearfix">
        <form name="recover-password" id="recover-password" method="<?php echo $this->escape($this->form->getMethod()) ?>" 
        action="<?php echo $this->escape($this->form->getAction()) ?>">    
            
            <div id="msg"><?php echo $this->msg ?></div>
        	<div class="input-control text" data-role="input-control"><?php echo $this->form->email ?></div>
            <div style="margin-top: 20px;">
                <input type="submit" value="Recover Now" class="btn btn-success pull-right"/>
            </div>
        </form>
    </div>

	 </div>
	   </div>
		
 <!-- ./ content -->
        </div>
        </div> <!--row div end-->
		
		
		</div>  <!--join-us-div closed-->
		</div>
<!-- ./ window -->
</div>

<!-- ./ lg--->
</div>
<!-- ./ row-->
</div>


<!-- ./ container -->
</div>