<!-- div style="background-color:#eff4f7; padding: 10px; font-size: 1.2em ">
<h3>Popular Categories</h3>
<p id="categories-p">
 
            <li><a href="#">Accounting &amp; Bookkeeping</a></li>
            <li><a href="#">Administration</a></li>
            <li><a href="#">Cleaning</a></li>
            <li><a href="#">Design &amp; Print</a></li>
            <li><a href="#">Equipment, Fitouts &amp; Repairs</a></li>
            <li><a href="#">Events &amp; Exhibitions</a></li>
            <li><a href="#">Finance &amp; Insurance</a></li>
            <li><a href="#">Food</a></li>
            <li><a href="#">Home Based Businesses</a></li>
            <li><a href="#">Human Resources &amp; Payroll</a></li>
            <li><a href="#">Legal</a></li>
            <li><a href="#">Manufacturing</a></li>
            <li><a href="#">Marketing &amp; Communications</a></li>
            <li><a href="#">Photography &amp; Video</a></li>
            <li><a href="#">Premises &amp; Real Estate</a></li>
            <li><a href="#">Promotional Materials &amp; Gifts</a></li>
            <li><a href="#">Technology</a></li>
            <li><a href="#">Training &amp; Development</a></li>
            <li><a href="#">Transport</a></li>
            <li><a href="#">Warehousing, Storage &amp; Removalists</a></li>
            <li><a href="#">Wholesale</a></li>
</p>
</div -->