<style>
    .panel{
       box-shadow: 0 0 10px grey !important;
     }
     .panel-footer, .panel-header{ 
        background-color: #1B1C52;
        padding: 10px;
        color: #fff;
     }
     .panel-body {
        padding: 30px 40px;
     }
     .requires {
        color: #FF0000;
     }
</style>
<div class="container" style="padding-top: 80px; padding-bottom: 30px;">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-info">
            <div class="panel-header">
                <strong>Testimonial</strong>
            </div>
            <div class="panel-body">
            <div id="msg" style="display: none;"><?php echo $this->msg;?></div>
            
            <form class="form-horizontal" action="" method="post">
                
                <div class="form-group">
                    <label for="name" class="col-md-3"><span class="requires">*</span> Full Name:</label>
                    <div class="col-md-9">
                        <?php echo $this->form->name; ?>
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="email" class="col-md-3"><span class="requires">*</span> Email:</label>
                    <div class="col-md-9">
                        <?php echo $this->form->email; ?>
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="message" class="col-md-3"><span class="requires">*</span> Tetimonial:</label>
                    <div class="col-md-9">
                        <?php echo $this->form->message; ?>
                    </div>
                </div>

                <?php echo $this->form->submit; ?>
            </form>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-md-12" style="min-height: 46px;">
                        
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function(){
       <?php if(!isset($this->msg)){ ?>
			$('#msg').hide();
		<?php } else{ ?>
			$('#msg').show();
		<?php } ?> 
    });
</script>