<style>
	body{
		background:#36465D;
	}
	.form-control{
		margin:10px auto;
		border-radius: 0;
		border:2px solid #FFAC2D;
	}
	form{
		    margin-top: 40px;
	}
</style>
<div class="container text-center">

	<div class="row" style="background:white;padding:40px;">
	<i class="fa fa-check-circle-o" aria-hidden="true" style="font-size: 10em;color:green;"></i>
		<h1 style="font-weight: bold; font-size: 4em;">Thank You!</h1>
		<h3 style="font-weight: bold; font-size: 2em;margin-bottom:20px;">We have sent your account login details to your email.</h3>
		<a href="http://pageiz.com" class="btn btn-success btn-lg" style="border-radius:0;">Back To Home</a>
	</div>	
	
		
	

</div>
