<!-- Non form translator section starts-->
<?php

if(Zend_Registry::get("lang_id") == 1){
$adapter = new Zend_Translate(
    array(
        'adapter' => 'array',
        'content' => array('page_heading' => 'Adding Bulk Cites'),
        'locale'  => 'en'
    )
);
}
if(Zend_Registry::get("lang_id") == 2){
$adapter = new Zend_Translate(
    array(
        'adapter' => 'array',
        'content' => array('page_heading' => 'بلک صوبوں کو شامل کرنے سے','Select State' => 'ریاست کا انتخاب کریں' ),
        'locale'  => 'en'
    )
);
}
	?>

  <div id="content" class="clearfix">
            <div class="contentwrapper"><!--Content wrapper-->

                <div class="heading">
						<h3><?php 
						$translate = new Zend_View_Helper_Translate($adapter);
						print $translate->translate('page_heading');	?>
						</h3>

                    <div class="resBtnSearch">
                        <a href="#"><span class="icon16 brocco-icon-search"></span></a>
                    </div>

                    <div class="search">

                        <form id="searchform" action="#" />
                            <input type="text" class="top-search" placeholder="Search here ..." />
                            <input type="submit" class="search-btn" value="" />
                        </form>
                
                    </div><!-- End search -->
				</div><!-- End .heading-->
    			
				<div class="row-fluid">

                        <div class="span12">

                            <div class="box">

                                <div class="title">

                                    <h4>
                                        <span class="icon16 brocco-icon-grid"></span>
                                        <span><?php print $translate->translate('Cities')?></span>
                                    </h4>
                                    
                                </div>
                                <div class="content">
                                   
                                    <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data" >
                                        
                                       <table class="table">
											
											<?php echo ($this->form->country); ?>
									
											 <tr id="state_sel">
												<td><strong>* <?php 
												$translate = new Zend_View_Helper_Translate($adapter);
												print $translate->translate('Select State');	?>
                                                </strong>
                                                </td>
                                                <td>
												<div id='state'> </div><!--  Ajax will fill this div with listbox values for sub category for selected value in main category -->
												</td>
											</tr>
											
											<tr id='file_csv'>
											<td>Select A File(csv):</td>
											<td><?php echo $this->form->bulk_cities; ?></td>
											</tr>
											<table class="extra-fields" id="form-table" style="width:100%">               
											   <?php echo $this->form->___h;?>     
											</table>
											 
											<table id="form-table" style="width:100%" id="submitbutton">   
												   <tr><td colspan='2'><?php echo $this->form->Save; ?> </td>
												 </tr>          
											</table> 
										</table>
										<input type='hidden' name='country_id' id='country_id' />
										<input type='hidden' name='state_id' id='state_id' />
									</form>
							
    
                                </div>

                            </div><!-- End .box -->

                        </div><!-- End .span6 -->
						

                </div><!-- End .row-fluid -->
				
				
				<script language="Javascript" type="text/javascript">
window.onload = function () { 

	
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			$('tr#file_csv').hide();
			$('tr#state').hide();
			$('tr#state_sel').hide();
			<?php  } else{ ?>
		$('tr#msg').show();
		<?php } ?>
 }

			
			function getState(){
			var country_id = $('#country_id').val();//select item value from listbox
					$('#country_id').val(country_id);
			 if(country_id == "")return;
						$.post("<?php echo $this->baseUrl()?>/admin/country/get-state", {country_id: country_id},
						//this is response from controller
						function(data){
							$('div#state').html(data);
							$('tr#state_sel').show();
							$('div#state').show();
						});
			}
			
			
			
			function getCities(country_id){
			var state_id = $('select#state').val();//select item value from listbox
			//alert(state_id);
					$('#state_id').val(state_id);
					if(state_id == "")return;
					$('input#state_id').val(state_id);
					$('input#country_id').val(country_id);
					$('tr#file_csv').show();
					$('input#submitbutton').show();
						
			}
			
		</script>
			
			
