  <style>
/* custom class for form to control it*/
.space-post{
padding-top: 40px;
}
</style>     
		
		
		<!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
            <div class="col-lg-12">
			<div class="col-lg-9 col-md-16">
            <div class="row" style="height:50px; padding:0; margin:0">
                 <div class="col-xs-3">
                 	<table class="table">
                    <tr><td> <a href="<?php echo $this->baseUrl(); ?>/admin/postcodes/list"> <i class="fa fa-list  alert-primary"></i> List</a></td>
                    <td>  <a href="<?php echo $this->baseUrl(); ?>/admin/postcodes/new"> <i class="fa fa-plus alert-primary"></i> New</a></td>
                    </tr>
                    </table>
                 </div>
                 </div>
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-barcode fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Add Postcodes in Bulk</div>                            
                                </div>
                            </div>
                        </div>
                        
                            <div class="panel-body"> 
                                <span class="pull-left">Enter Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                  
                                    <form class="form-horizontal space-post" action="" method="POST" onsubmit="return validate()">
                                       	<table class="table table-striped table-bordered table-hover">
                                    	<tr id='msg'><td id='td_msg' colspan='2'><?php echo $this->msg ?></td></tr>
										<?php echo $this->form->country; ?>												
                                         	 
                                <tr>
			                 <td><strong id="set-state-val"> Select State </strong></td>
                            <td>
							 <select id="state" name="state_id" class="form-control">
                                 <option value="0">Select State</option>
                             </select>
                            </td>
                            </tr>
                                 
 <tr><td></td><td><button class="btn btn-lg btn-primary" name="save" value="1" onclick="savePostcode();">Save Bulk</button><?php //echo $this->form->Save; ?> </td>
												 </tr>    
												<tr><td colspan="2">Add List of postcode + cities name separated by commas</td></tr>
											<tr><td colspan="2"><textarea rows="30" cols="30" class="form-control" name="postcodes" id="postcodes"></textarea></td></tr>
											
                                                
                                       
												  
											</form>
	                              
                                </div>
                            </div>
							<!--
						<div class="panel-footer">
						</div>-->
							
							</div>
                     
						
                    </div>
                </div>
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
<script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }
			function getState(){
			var country_id = $('#country_id').val();//select item value from listbox
					$('#country_id').val(country_id);
			 if(country_id == "")return;
						$.post("<?php echo $this->baseUrl()?>/admin/countries/get-state", {country_id: country_id},
						//this is response from controller
						function(data){
							
							$('#state').html(data);
							
                            if($('#state option').size()>1){
                                $('#set-state-val').text('* Select State');
                            } else {
                                $('#set-state-val').text('Select State');
                            }
						});
			}
		
		
			function getCities(){
	
			var country_id = $('#country_id').val();//select item value from listbox
			var state_id = $('#state').val();//select item value from listbox
	
			 if(country_id == "")return;
			 if(state_id == "")return;
			 
	
						$.post("<?php echo $this->baseUrl()?>/admin/countries/get-cities", {country_id: country_id, state_id: state_id},
						function(data){
							
							$('#cities').html(data);
							
						});
			}
			
			
	function validate()
    {
            var country_id = $('#country_id').val();//select item value from listbox
            var state_id = $('#state').val();//select item value from listbox
            var postcodes = $('#postcodes').val();

		if(country_id == 0){
					$('tr#msg').show();
					$('td#td_msg').html("<div class='alert alert-danger'>Please Select Country</div>")
					$('tr#msg').hide(6000);
					return false;	
				}

        if($('#state option').size()>1){
    		if(state_id == 0){
    					$('tr#msg').show();
    					$('td#td_msg').html("<div class='alert alert-danger'>Please Select State</div>")
    					$('tr#msg').hide(6000);
    					return false;	
    		}
        }
        if(postcodes == ""){
					$('tr#msg').show();
					$('td#td_msg').html("<div class='alert alert-danger'>Add Postcodes with City/Area Name</div>")
					$('tr#msg').hide(6000);
					return false;	
		}

return true;
}
				
			
	
 </script>