<div class="row-fluid">

                    <div class="span12">
						<div class="box gradient">

                                <div class="title">
                                    <h4>
                                        <span>List of Cities </span>
                                    </h4>
                                </div>
                                <div class="content noPad clearfix">
								<div class="col-md-2">
								<a href="<?php echo $this->baseUrl(); ?>/admin/cities/new"><button class="form-control btn-primary">Add New Cities</button></a>
								</div> 
								


							<?php if (count($this->paginator)){ ?>
							<?php //echo  $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>
							<table cellpadding="0" cellspacing="0" border="0" class="responsive dynamicTable display table table-bordered" width="100%">
										<thead>
                                            <tr>
                                                <th>Cities Name</th>
                                                <th>Cities Code</th>
                                            </tr>
                                        </thead>
										<tbody>
						<?php foreach ($this->paginator as $item): ?>
										<tr><td>

										<?php echo $item['city_name'] ?>
										</td>
										<td>
											<?php echo $item['city_name'] ?>
										</td>

									<?php endforeach; ?>
									
										</tbody>
                                        
                                    </table>
							<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>
							<?php }else{?>
							No Cities
							<?php } ?>
							</div>
								
						</div><!-- End .box -->

                    </div><!-- End .span12 -->

                </div><!-- End .row-fluid -->




