<style>

.space-edit {
    margin-top: 40px;
}

</style>
	   <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                         <div class="col-lg-9 col-md-16">
                          <div class="row" style="height:50px; padding:0; margin:0">
                 <div class="col-xs-3">
                 	<table class="table">
                    <tr><td> <a href="<?php echo $this->baseUrl(); ?>/admin/postcodes/list"> <i class="fa fa-list  alert-primary"></i> List</a></td>
                    <td>  <a href="<?php echo $this->baseUrl(); ?>/admin/postcodes/new"> <i class="fa fa-plus alert-primary"></i> New</a></td>
                    </tr>
                    </table>
                 </div>
                   </div>      
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-globe fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Edit Postcode</div>
                            
                                </div>
                            </div>
                        </div>
                        <div class="panel-body">
                                <span class="pull-left">Enter Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                  
                                    <form class="form-horizontal space-edit" action="" method="POST" enctype="multipart/form-data" >
                                       	<table class="table table-striped table-bordered table-hover">
                                    	<tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
										<?php echo $this->form->postcode ?>
                                        <?php echo $this->form->area_name ?>
										<?php echo $this->form->areas ?>
										<?php echo $this->form->country ?>
                                        <tr><td>&nbsp;</td><td>
                                         <input type="submit" value="Save" class="btn btn-lg btn-primary float-right">
										
										</td></tr>
										</table>
									</form>
	                              
                                </div>
                            </div>
                             <a href="#">
                            <div class="panel-footer">
                            </div>
                        </a>
                    </div>
                </div>
                
                
          
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->


<script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }
			function getState(){
			var country_id = $('#country_id').val();//select item value from listbox
					$('#country_id').val(country_id);
			 if(country_id == "")return;
						$.post("<?php echo $this->baseUrl()?>/admin/countries/get-state", {country_id: country_id},
						//this is response from controller
						function(data){
							
							$('div#state').html(data);
							$('tr#state_sel').show();
							$('div#state').show();
						});
			}
		
		
			
			function getCities(){
	
			var country_id = $('#country_id').val();//select item value from listbox
			var state_id = $('select#state').val();//select item value from listbox
	
			 if(country_id == "")return;
			 if(state_id == "")return;
			
		/*alert(country_id + " " + state_id);
		return;	
	*/
						$.post("<?php echo $this->baseUrl()?>/admin/countries/get-cities", {country_id: country_id, state_id: state_id},
						function(data){
							
							$('div#cities').html(data);
							$('tr#city_sel').show();
							$('div#cities').show();
						});
			}
			
			
			
			
			
			function getPostcodes(){
			var country_id = $('#country_id').val();//select item value from listbox
			var state_id = $('select#state').val();//select item value from listbox
	       var city_id = $('select#city').val();
		  
			 if(country_id == "")return;
			 if(state_id == "")return;
			  if(city_id == "")return;
	

						$.post("<?php echo $this->baseUrl()?>/admin/countries/get-postcodes", {country_id: country_id, state_id: state_id, city_id: city_id},
						function(data){
							
							$('div#postcodes').html(data);
							$('tr#post_sel').show();
							$('div#postcodes').show();
						});
			}
			
			
			function savePostcode(){
				var postcode_id = $('select#postcode').val();
				var areas = $('#areas').val();
				
				if(postcode_id == 0){
					$('tr#msg').show();
					$('td#td_msg').html("<div class='alert alert-danger'>Please Select Postcode</div>")
					$('tr#msg').hide(6000);
					return;	
				}
				if(areas == ''){
					$('tr#msg').show();
					$('td#td_msg').html("<div class='alert alert-danger'>Please Enter Near By Postcodes separated by comma</div>")
					$('tr#msg').hide(6000);
					return;	
				}
					
				$.post("<?php echo $this->baseUrl()?>/admin/postcodes/save-near-postcode", {postcode_id: postcode_id, areas: areas},
						//this is response from controller
				function(data){
					$('tr#msg').show();
					$('td#td_msg').html(data)
					$('tr#msg').hide(6000);
					return;	
							
						});
				}
			
	
 </script>