  <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                         <div class="col-lg-12 col-md-26">
                                      <div class="row" style="height:50px; padding:0; margin:0"><!-- row 1-->
                                        <div class="col-xs-5">
                 	<table class="table">
                    <tr><td> <a href="<?php echo $this->baseUrl(); ?>/admin/postcodes/list"> <i class="fa fa-list  alert-warning"> List</i></a></td>
                    <td> <a href="<?php echo $this->baseUrl(); ?>/admin/postcodes/new"> <i class="fa fa-plus  alert-warning"> New</i></a></td>
					<td> <a href="<?php echo $this->baseUrl(); ?>/admin/postcodes/near-postcodes"> <i class="fa fa-plus  alert-warning"> NearByPostcode</i></a></td>
                    
					</tr>
                    </table>
                 </div>
                
                 </div>
                 </div><!-- ./ row 1-->
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-1">
                                    <i class="fa fa-cube fa-5x"></i>
                                </div>
                                <div class="col-xs-6">
                                 <form action="<?php echo $this->baseUrl(); ?>/admin/postcodes/list" action="post">
                                <div class="input-group custom-search-form col-xs-6 text-right" style="padding-top:20px">
                                <input type="text" name="query_string" id="query_string" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            </form>
                                </div>
                                <div class="col-xs-5 text-right">
                                    <div class="huge">Postcodes List
                        </div>
                                </div>
                            </div>
                        </div>
                     <div class="panel-body">
                        
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                          <form action="<?php echo $this->baseUrl(); ?>/admin/postcodes/list" action="post">
                                	<table cellpadding="0" cellspacing="0" border="0" class="responsive dynamicTable display table table-bordered" width="100%">
														<tbody>
                                                         	<tr id='msg'><td id='td_msg' colspan='2'><?php echo $this->msg ?></td></tr>
									
															<tr><td>
                               <?php echo $this->countries; ?>
                               </td></tr>
                               
                                <tr id="state_sel">
                                    <td>
												 <?php 
												//$translate = new Zend_View_Helper_Translate($adapter);
												echo $this->states;	?>
                                    <select id="state" name="state_id" class="form-control" onchange="getCities();">
                                        <option value="0">Select State</option>
                                    </select>
												
										</td>	
                                </tr>
                                <tr>
                                    <td>
												 <?php 
												//$translate = new Zend_View_Helper_Translate($adapter);
												echo $this->cities;	?>
                                    <select id="city" name="city_id" class="form-control">
                                        <option value="0">Select City</option>
                                    </select>
                                             	
										</td>	
                                </tr>
                                        
                                        <tr><td style="text-align: right"> <input type="submit" value="Search" />
                                         <!--<tr id="city_sel">
												<td><strong>* Select City
                                                </strong>
                                                </td>
                                                <td>
											    <div id='cities'> </div>
                                                </td></tr>--></tbody></table>
                                                
                                                </td>
                               
                               	<div id='result'></div>
				
                <div class="table-responsive">
                	<table cellpadding="0" cellspacing="0" border="0" class="dynamicTable display table table-bordered">
														<thead>
															<tr>
																<th>Poscode</th>
																<th>Main Area</th>
																<th>Areas </th>
																<th>City</th>
															 	<th>State</th>
															 	<th>Country</th>
																<th>Edit</th>
												                </tr>
														</thead>		
														<tbody>
                                          
														<?php if (count($this->paginator)){ ?>
													
														<?php foreach ($this->paginator as $item): ?>
														<tr class="odd gradeX">
															<td>
															<?php echo $item['postcode'] ?>
															</td>
                                                            <td>
															<?php echo $item['area_name'] ?>
															</td>
                                                        <td>
															<?php echo $item['areas'] ?>
															</td>
                                                        <td>
															<?php echo $item['city_name'] ?>
															</td>
                                                        <td>
															<?php echo $item['state_name'] ?>
															</td>
                                                        <td>
															<?php echo $item['country_name'] ?>
															</td>
														<td>
														    <a class="btn btn-sm btn-warning float-right" href="<?php echo $this->baseUrl();?>/admin/postcodes/edit/pc_id/<?php echo $item['pc_id'];?>">Edit</a>
															</td>   
                                                        </tr>
                                                            	
                                                                
                                                                
															<?php endforeach; ?>
															<tr><td colspan='9'>
															<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>
															</td>
															</tr><?php }else{ ?>
											
															<tr><td colspan="7"><h4>There are no postcode created! Please create one</h4></td></tr>
															<?php } ?>
														</tbody>

														</table>
									
                                 </div>
                
												</div>
                            </div>
                          
                        
                        <a href="#">
                        
                            <div class="panel-footer">
                             
                               </div>
                        </a>
                     </div>
                  
                    </div>
                </div>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    
  <script language="Javascript" type="text/javascript">
  window.onload = function () { 
			
			
/* <?php if(!isset($this->qs)){ ?>
			getAllPostcodes();
		$('div#qs').hide();

		<?php  } else{
		?>
$('div#result').hide();
$('div#qs').show();

		<?php } ?> */


<?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
					
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
			
 }

 function getAllPostcodes(){
  $.post("<?php echo $this->baseUrl()?>/admin/postcodes/get-all-postcodes", 
						//this is response from controller
						function(data){
							$('div#result').html(data);
							$('div#result').show();
							$('div#qs').hide();
							
						});
 }
 
 function getState(){
			var country_id = $('#country').val();//select item value from listbox
			
			 if(country_id == ""){
				 
				 getAllPostcodes();
				 return;
				 }
						$.post("<?php echo $this->baseUrl()?>/admin/countries/get-state", {country_id: country_id},
						//this is response from controller
						function(data){
							$('#state').html(data);
							
						});
						
						$.post("<?php echo $this->baseUrl()?>/admin/postcodes/get-countries-postcodes", {country_id: country_id},
						//this is response from controller
						function(data){
						$('div#result').empty();
						$('div#result').html(data);
							$('div#result').show();
							//$('div#state').show();
						});
			}
			
			
			
			function getCities(){
			
			var country_id = $('#country').val();//select item value from listbox
			var state_id = $('#state').val();//select item value from listbox
				//alert(state_id);
					$('#state_id').val(state_id);
					if(state_id == "")return;
					$.post("<?php echo $this->baseurl()?>/admin/countries/get-cities", {country_id: country_id,state_id: state_id},
						//this is response from controller
						function(data){
							$('#city').html(data);
						
						});
					
			}
	</script>