
  <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                         <div class="col-lg-12 col-md-26">
                         <div class="row" style="height:50px; padding:0; margin:0"><!-- row 1-->
                 <div class="col-xs-3">
                 	<table class="table">
                    <tr><td> <a href="<?php echo $this->baseUrl()?>/admin/postcodes/list-nearpost"> <i class="fa fa-list  alert-warning"> List</i></a></td>
                    <td>  <a href="<?php echo $this->baseUrl(); ?>/admin/postcodes/near-postcodes"> <i class="fa fa-plus alert-warning"> New</i></a></td>
                    </tr>
                    </table>
                 </div>
                 </div><!-- ./ row 1-->
                 
                 
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-1 set-glob">
                                    <i class="fa fa-globe fa-5x"></i>
                                </div>
                                <div class="col-xs-6 set-search">
                                <form action="<?php echo $this->baseUrl(); ?>/admin/postcodes/list-nearpost" action="post">
                                <div class="input-group custom-search-form col-xs-6 text-right sarch-widh" style="padding-top:20px">
                                <input type="text" name="query_string" id="query_string" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            
                            </div>
                            </form>
                                </div>
                                <div class="col-xs-5 text-right set-country">
                                    <div class="huge">Nearby Post Codes List
                        </div>
                                </div>
                            </div>
                        </div>
                   
                        
                             <div class="panel-body">
                         <span class="pull-left">Use buttons for operations</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                                
												<div class="table-responsive">
													<table cellpadding="0" cellspacing="0" border="0" class="dynamicTable display table table-bordered list-post-space" width="100%">
														<thead>
															<tr>
																<th>Area Name</th>
																<th>Edit</th>
																<th>Block</th>
															 	</tr>
														</thead>		
														<tbody>
                                          
														<?php if (count($this->paginator)){ ?>
													
														<?php foreach ($this->paginator as $item): ?>
														<tr class="odd gradeX">
															<td>
															<?php echo $item['area_name'] ?>
															</td>
                                                        
                                                            	<td><a class="btn btn-sm btn-warning float-right" href="<?php echo $this->baseUrl(); ?>/admin/postcodes/edit-nearpostcode/pc_nb_id/<?php echo $item['pc_nb_id'] ?>">Edit</a></td>
															<td><a class="btn btn-sm btn-info float-right" href="<?php echo $this->baseUrl(); ?>/admin/countries/confirm-block/pc_nb_id/<?php echo $item['pc_nb_id'] ?>">Block</a></td>
														</tr>
															<?php endforeach; ?>
															<tr><td colspan='9'>
															<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>
															</td>
															</tr><?php }else{ ?>
											
															<tr><td colspan="7"><h4>There are no nearby post codes created! Please create one</h4></td></tr>
															<?php } ?>
														</tbody>

														</table>
														</div><!--table-responsive div end-->
												</div>

                               
                                
                                </div>
                                
                               <a href="#">
                            <div class="panel-footer">
                             
                            </div>
                        </a>
                       
                    </div>
                </div>
                
          
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    
  <script language="Javascript" type="text/javascript">
  window.onload = function () { 
			$('tr#state_sel').hide();
			$('tr#city_sel').show();
			
/* <?php if(!isset($this->qs)){ ?>
			getAllPostcodes();
		$('div#qs').hide();

		<?php  } else{
		?>
$('div#result').hide();
$('div#qs').show();

		<?php } ?> */


<?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
					
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
			
 }

 function getAllPostcodes(){
  $.post("<?php echo $this->baseUrl()?>/admin/postcodes/get-all-postcodes", 
						//this is response from controller
						function(data){
							$('div#result').html(data);
							$('div#result').show();
							$('div#qs').hide();
							//$('div#state').show();
						});
 }
 
 function getState(){
			var country_id = $('#country').val();//select item value from listbox
			//alert(country_id);
			//$('#country_id').val(country_id);
			 if(country_id == ""){
				 $('div#state').hide();
				 $('tr#state_sel').hide();
				 getAllPostcodes();
				 return;
				 }
						$.post("<?php echo $this->baseUrl()?>/admin/countries/get-state", {country_id: country_id},
						//this is response from controller
						function(data){
							$('div#state').html(data);
							$('tr#state_sel').show();
							$('div#state').show();
						});
						
						$.post("<?php echo $this->baseUrl()?>/admin/countries/get-countries-postcodes", {country_id: country_id},
						//this is response from controller
						function(data){
							$('div#result').html(data);
							$('div#result').show();
							//$('div#state').show();
						});
			}
			
			
			
			function getCities(){
			
			var country_id = $('#country').val();//select item value from listbox
			var state_id = $('select#state').val();//select item value from listbox
				//alert(state_id);
					$('#state_id').val(state_id);
					if(state_id == "")return;
					$.post("<?php echo $this->baseUrl()?>/admin/countries/get-state-cities", {country_id: country_id,state_id: state_id},
						//this is response from controller
						function(data){
						
								$('div#result').html(data);
						
							$('div#result').show();
								$('tr#city_sel').show();
						});
						
			}
	</script>