 <!-- Page Content -->      
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-2.1.1.min.js"></script>	
<style>
.set-basic1{
margin-top:4%;
float:left;
}


</style>

	<div id="page-wrapper">
            <div class="row">
            <div class="col-lg-12">
			<div class="col-lg-11">
            <div class="row" style="height:50px; padding:0; margin:0">
                 <div class="col-xs-5">
 <!--                	<table class="table">
                    <tr><td> <a href="<?php echo $this->baseUrl(); ?>/members/bdlist"> <i class="fa fa-list  alert-primary"></i> List</a></td>
                    <td>  <a href="<?php echo $this->baseUrl(); ?>/members/manage-ad/id/<?php echo $this->id ?>"> <i class="fa fa-plus alert-primary"></i> Manage AD</a></td>
                    </tr>
                    </table>-->
                 </div>
                 </div>
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-user fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Manage Profile</div>
                            
                                </div>
                            </div>
                        </div>  
                       
                            <div class="panel-body">
                                <span class="pull-left"><ul class="nav nav-tabs" role="tablist">
 <li class="active"><a href="<?php echo $this->baseUrl(); ?>/members/basic-update/id/<?php echo $this->member_id ?>">Basics</a></li>
  <li ><a href="<?php echo $this->baseUrl(); ?>/members/delivery-address/id/<?php echo $this->member_id ?>">Delivery Address</a></li>
  <li><a href="<?php echo $this->baseUrl(); ?>/members/pass-update/id/<?php echo $this->member_id ?>">Password</a></li>
</ul></span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                  
                                    <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data" >
                                     
									   <table class="table table-striped table-bordered table-hover set-basic1">
                                    	 <tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
                                     
					
                                        <?php echo $this->form->first_name; ?>							
                                        <?php echo $this->form->last_name;?> 
                                      
                                        <?php echo $this->form->office_contact_number; ?>
                                        <?php echo $this->form->contact_number; ?>
						
                                        <tr><td>&nbsp;</td><td>
                                       <?php echo $this->form->submit?>
										</td></tr>
										</table>
									
									</form>
	                              
                                </div>
                            </div> 
                         <a href="#">
                         <div class="panel-footer">
                         </div>
                        </a>
                    </div>
                </div>
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

		<script language="Javascript" type="text/javascript">
		window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide(); 
			
			
		<?php  } else{
		?>
		/* alert('hi');
			$('tr#msg').show(); */
		<?php } ?>
 }
		
		</script>
