<style type="text/css">
    .row-even {
        background-color: #eee;
    }
    .row {
        padding: 8px;
    }
    .row-odd:hover, .row-even:hover{
        background-color: #ddd;
    }
    
</style>
<div id="page-wrapper" style="padding-top: 20px;">
    <div class="row">
        <div class="col-md-12">
            <h1>Campaign Detail</h1>
            
            <div class="row row-even">
                <div class="col-md-3">
                    Offered By
                </div>
                <div class="col-md-3">
                    Biz Member
                </div>
                <div class="col-md-3">
                    Offere End Date
                </div>
                <div class="col-md-3">
                    <strong>04/10/2016</strong>
                </div>
            </div>
            
            <div class="row row-odd">
                <div class="col-md-3">
                    Campaign Name
                </div>
                <div class="col-md-3">
                    Campaign One
                </div>
            
                <div class="col-md-3">
                    Campaign Type
                </div>
                <div class="col-md-3">
                    Product
                </div>
            </div>
            
            <div class="row row-even">
                <div class="col-md-3">
                    About Campaign
                </div>
                <div class="col-md-9">
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                </div>
            </div>
            
            <div class="row row-odd">
                <div class="col-md-3">
                    Budget
                </div>
                <div class="col-md-3">
                    <strong>RM220</strong>
                </div>
                <div class="col-md-6">
                    <a href="#" class="btn btn-success pull-right">Interested</a>
                </div>
            </div>
            
        </div>
    </div>
</div>