<div id="page-wrapper">
<div class="row">
    <div class="col-md-12">
        <h2>Campaign List</h2>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
				<tr>
				    <th>Campaign Name</th>
                    <th>Campaign Type</th>
				    <th>Budget</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                </tr>
				</thead>		
				<tbody>
                    <tr>
                        <td>Campaign One</td>
                        <td>Product</td>
                        <td>RM220</td>
                        <td>03/10/2016</td>
                        <td>03/15/2016</td>                        
                    </tr>
                    <tr>
                        <td>Campaign Two</td>
                        <td>Product</td>
                        <td>RM190</td>
                        <td>03/17/2016</td>
                        <td>03/21/2016</td>                        
                    </tr>
                    <tr>
                        <td>Campaign Three</td>
                        <td>Service</td>
                        <td>RM250</td>
                        <td>03/25/2016</td>
                        <td>03/30/2016</td>                        
                    </tr>
                    <tr>
                        <td>Campaign Four</td>
                        <td>Business</td>
                        <td>RM130</td>
                        <td>04/04/2016</td>
                        <td>04/06/2016</td>                        
                    </tr>
                </tbody>
                </table>
        </div>
    </div>
</div>
</div>

<script type="text/javascript">
    $(function(){
    $('#dataTables-example').dataTable(
           {
		      "aaSorting": [[ 4, "desc" ]],
              "iDisplayLength": 50,
              "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]]
	       }
        );
    });
 </script>