<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2/js/select2.min.js"></script>

<!-- Page Content -->
        <div id="page-wrapper" style="padding-top: 20px;">
            
            <div class="row">
            <div class="col-lg-10 col-lg-offset-1">
                
			   <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-file-o fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Create Pages</div>
                                    <strong>200 points will be deducted from your points on each page creation</strong>                            
                                </div>
                            </div>
                        </div>
                        
                        <div class="panel-body">
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                  
                                   <form id="create-page" method="post" action="">  
                                    <input type="hidden" id="points" name="points" value="200" />
                                       	<table class="table table-striped table-bordered table-hover">
                                    	   <tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
                                           <tr>
                                            <td colspan="2"><label class="text-success">Your balance: <?php echo $this->total_points;?></label></td>                                                                                       
                                           </tr>
                                           <tr>
                                           <td style="width: 200px;"><label for="member_id">Select Member</label></td>
                                           <td><?php echo $this->member_ddl;?></td>
                                           </tr>
                                           <tr>
                                            <td><label for="no_of_pages">No. of Pages</label></td>
                                            <td><?php echo $this->no_of_pages_ddl;?></td>
                                           </tr>                                           
                                           <tr><td colspan="2"><input type="submit" value="Create" class="btn btn-lg btn-primary pull-right" /></td></tr>
                                        </table>
                                   </form>
	                            </div>
                            </div>                      
                </div>
                
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
</div>


 <script type="text/javascript">
    window.onload = function () { 
     <?php if(!isset($this->msg)){ ?>
    			$('tr#msg').hide();
    			
    		<?php  } else{
    		?>
    			$('tr#msg').show().delay(7000).hide('slow');
    		<?php } ?>
            
        $('#create-page').submit(function() {
            var c = confirm("Are you sure, you want to create new page(s) for the selected member?");
            return c;
        });
     }
     
     $('#member_id').select2();
     $('#no_of_pages').select2();
     	
     $('#no_of_pages').change(function(){
        
        var points = ($(this).val() * 200);
        $('#points').val(points);
     });
        
 </script>