<div id="page-wrapper" style="padding-bottom: 20px;">
	
    <div class="row">        
        <div class="col-md-12">             
		
        <div id="msg">
			<?php echo $this->msg ?>
		</div>
        <h1 class="page-header">Dashboard</h1>
        <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
														<thead>
														<tr>
																<th class="grid-head"> Poster</th>
                                                                <th class="grid-head"> Title</th>
																<th class="grid-head"> Dates</th>
                                                                <th class="grid-head"> Manage</th>
																<th class="grid-head"> Comments</th>
																<th class="grid-head"> Likes</th>
																<!-- th class="grid-head"> Rating</th -->
																<th class="grid-head"> Views</th>																
																
                                                                <!--th class="grid-head"> Transfer Page</th-->
                                                        	</tr>
														</thead>		
														<tbody> 
                                          
														<?php if (count($this->data)){ 
														  foreach ($this->data as $item): ?>
														<tr class="odd gradeX">
															<td style="text-align:center; vertical-align: middle;">
															<a href="<?php echo $this->baseUrl(); ?>/members/manage-page/id/<?php echo $item['page_id'] ?>">
                                                                <?php if(isset($item['banner_img']) && (!empty($item['banner_img']))) {?>
                                                                <img class="img-responsive" src="<?php echo $this->baseUrl().'/images/uploads/'.$item['dir_name'].'/300X300/'.$item['banner_img']; ?>" alt="<?php echo $item['title'] ?>" />
                                                                <?php } else {?>
                                                                <img class="img-responsive" src="<?php echo $this->baseUrl().'/images/banner-placeholder-360X500.jpg'; ?>" alt="<?php echo $item['title'] ?>" style="width: 217px;" />
                                                                <?php }?>
                                                            </a>
															</td>
                                                            
                                                            <td>
															<a href="<?php echo $this->baseUrl(); ?>/<?php echo $item['url_slug'] ?>" target="_blank" title="View Page"><?php echo $item['title'] ?></a>
															</td>

                                                            <td style="text-align:center;">
                                                              <p>Activation: <?php echo date('d/m/Y', strtotime($item['start_date'])); ?></p>
                                                            
                                                               <p>Expirey: <?php echo date('d/m/Y', strtotime($item['expiry_date'])); ?></p>
															</td>
                                                            
                                                            <td style="text-align:center;">
                                                              	<?php if(strlen($item['url_slug']) > 0){ ?>
																  <a class="btn btn-sm btn-info " href="<?php echo $this->baseUrl(); ?>/members/manage-page/id/<?php echo $item['page_id'] ?>">
															   Manage   </a>
																<?php }else{ ?>
																  <a class="btn btn-sm btn-warning " href="<?php echo $this->baseUrl(); ?>/members/add-url/id/<?php echo $item['page_id'] ?>">
															   Publish  </a>
																<?php } ?>
														    </td>
															    <td style="text-align:center;">
                                                                <a class="btn btn-sm btn-success " href="<?php echo $this->baseUrl(); ?>/members/comments/id/<?php echo $item['page_id'] ?>"><span style="font-size: 15px"><?php echo $item['comments'] ?></span> <i class="fa fa-commenting-o fa-2x" aria-hidden="true"></i></a>
                                                            </td>
															    <td style="text-align:center;">
                                                                <a class="btn btn-sm btn-danger " href="<?php echo $this->baseUrl(); ?>/members/page-likes/id/<?php echo $item['page_id'] ?>"><span style="font-size: 15px"><?php echo $item['likes'] ?></span>  <i class="fa fa-thumbs-o-up fa-2x" aria-hidden="true"></i></a>
                                                            </td>
															    <!-- td style="text-align:center;">
                                                                <a class="btn btn-sm btn-info " href="<?php echo $this->baseUrl(); ?>/members/manage-page/id/<?php echo $item['page_id'] ?>"><span style="font-size: 15px"><?php echo $item['rating'] ?></span>  <i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i></a>
                                                            </td -->
															  <td style="text-align:center;">
                                                                <a class="btn btn-sm btn-warning " href="<?php echo $this->baseUrl(); ?>/members/manage-page/id/<?php echo $item['page_id'] ?>"><span style="font-size: 15px"><?php echo $item['views'] ?></span>  <i class="fa fa-eye" aria-hidden="true"></i></a>
                                                            </td>
                                                            <!--td style="text-align:center;">
                                                                <a class="btn btn-sm btn-info " href="<?php echo $this->baseUrl(); ?>/#">Transfer</a>
                                                            </td-->
														</tr>  
															<?php endforeach; } ?> 
														</tbody>
					 								</table>
							
                    </div><!-- div responsive end-->												
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
</div>

<?php
    function strip_single($tag, $string){
        $string = preg_replace('/<'.$tag.'[^>]*>/i', '', $string);
        $string = preg_replace('/<\/'.$tag.'>/i', '', $string);
        return $string;
    }
?>

  <script type="text/javascript">
 window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('#msg').hide();
			
		<?php  } else{
		?>
			$('#msg').show().delay(5000).hide('slow');
		<?php } ?>
        
        $('#dataTables-example').dataTable(
           {
		      "aaSorting": [[ 3, "asc" ]],
              "iDisplayLength": 50,
              "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
              "aoColumnDefs": [{'bSortable': false, 'aTargets': [4,5,6]}]
	       }
        );
 }
 
    function confirmDelete(id){
    	var r = confirm("Do you realy want to delete this Page?" );
    	if (r == true) {
    	   window.location.assign("<?php echo $this->baseUrl(); ?>/admin/page/delete-page/id/" + id);    
    	} else {
    	   return false;
    	}
	}
 </script>