<!-- Page Content -->
<div id="page-wrapper">

<div class="row">
                <div class="col-md-12">
                    <h1 class="page-header">Dashboard</h1>
                </div>
</div>
                <div class="col-md-5">
				   <div class="panel panel-yellow">
						<a href="<?php echo $this->baseUrl(); ?>/members/detail-pages" style="color:#fff">
						<div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-list fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">My Page(s)</div>
                                    <div>Manage Page(s)!</div>
                                </div>
                            </div>
                        </div>
						</a>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
					</div>
					    <div class="col-md-5">
           	   <div class="panel panel-green">
         				<a href="" style="color:#fff">
						<div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-thumbs-o-up fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">C&L</div>
                                    <div>Check all recent comments & likes!</div>
                                </div>
                            </div>
                        </div>
						</a>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
		        </div>
</div>