<div id="page-wrapper">
<div class="row">
    <div class="col-md-12">
        <h2>Interested Marketers</h2>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
				<tr>
				    <th>Campaign Name</th>
                    <th>Marketer Name</th>
				    <th>Marketer Profile</th>
                </tr>
				</thead>		
				<tbody>
                    <tr>
                        <td>Campaign One</td>
                        <td>Marketer Xyz</td>
                        <td><a href="#" class="btn btn-sm btn-info">View</a></td>
                    </tr>
                    <tr>
                        <td>Campaign Two</td>
                        <td>Marketer Abc</td>
                        <td><a href="#" class="btn btn-sm btn-info">View</a></td>                        
                    </tr>
                    <tr>
                        <td>Campaign Three</td>
                        <td>Marketer Xyz</td>
                        <td><a href="#" class="btn btn-sm btn-info">View</a></td>                        
                    </tr>
                    <tr>
                        <td>Campaign Four</td>
                        <td>Marketer Test</td>
                        <td><a href="#" class="btn btn-sm btn-info">View</a></td>                        
                    </tr>
                </tbody>
                </table>
        </div>
    </div>
</div>
</div>

<script type="text/javascript">
    $(function(){
    $('#dataTables-example').dataTable(
           {
		      "aaSorting": [[ 0, "asc" ]],
              "iDisplayLength": 50,
              "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]]
	       }
        );
    });
 </script>