<style>
.grid-head {
    text-align: center;
}
.menu-links {
padding: 0px;
margin-top: 20px !important;
list-style-type: none;
}
.menu-links li {
display: inline;
padding-right: 10px;
text-decoration: underline;
color: #618CA4;
}
</style>
<?php
// $str = '12345678';
// $encrypted = base64_encode($str);
// echo utf8_decode(base64_decode($encrypted));
// exit;
?>
<div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                   
                    <ul class="nav" id="side-menu" style="margin-top: -40px;">
                       <li>
                                <a href="<?php echo $this->baseUrl(); ?>/mem-pages/index"><i class="fa fa-user fa-home"></i> Dashboard</a>
                            </li>
							<li>
                                <a href="javascript:void(0)" onclick="contact_redirect()"><i class="fa fa-user fa-list"></i> Contacts </a>
                            </li>
							<li>
                                <a href="javascript:void(0)" onclick="contact_group_redirect()"><i class="fa fa-user fa-list"></i> Contact Groups </a>
                            </li>

							
                      				
                            <!--li>
                                <a href="<?php echo $this->baseUrl(); ?>/members/create-page"><i class="fa fa-file-o fa-fw"></i> Create Page</a>
                            </li-->
                            <?php if($this->role==3) {?>
                            <!-- li>
                                <a href="<?php echo $this->baseUrl(); ?>/members/page-transfer"><i class="fa fa-share-square-o fa-fw"></i> Transfer Page</a>
                            </li -->
                            <?php }?>
                            <!-- li>
                                <a href="<?php echo $this->baseUrl(); ?>/members/share-pages"><i class="fa fa-share fa-fw"></i> Share Your Page</a>
					        </li>
    				        <li>
                                <a href="<?php echo $this->baseUrl(); ?>/members/shared-pages"><i class="fa fa-share-alt fa-fw"></i> Pages Shared With You</a>
					        </li-->
                           
                         
						 <?php if($this->role==2) {?>
                            
							<!--li>
                                <a href="<?php echo $this->baseUrl(); ?>/mem-pages/detail-pages"><i class="fa fa-file-text-o fa-fw"></i> Home Page</a>
								
                            </li-->
							
                             <!--li>
                                 <a href="#"><i class="fa fa-file-text-o fa-fw"></i> Product/Service Pages</a>
                             </li>

                             <li>
                                 <a href="#"><i class="fa fa-file-text-o fa-fw"></i> Products/Services Price List</a>
                             </li>
                             <li>
                                 <a href="#"><i class="fa fa-file-text-o fa-fw"></i> Business Information</a>
                             </li-->
                       
                             <!--li>
                                 <a href="<?php echo $this->baseUrl(); ?>/members/upload-brochure"><i class="fa fa-upload fa-fw"></i> Upload Brochure</a>
                             </li>
                             <li>
                                 <a href="<?php echo $this->baseUrl(); ?>/members/brochure-list"><i class="fa fa-file-pdf-o fa-fw"></i> Brochures Details</a>
                             </li>
                              <li>
                                 <a href="<?php echo $this->baseUrl(); ?>/members/comments-details"><i class="fa  fa-commenting-o fa-fw"></i> Comments Details</a>
                             </li>
                              <li>
                                 <a href="<?php echo $this->baseUrl(); ?>/members/likes-details"> <i class="fa fa-thumbs-o-up fa-fw"></i> Likes Details</a>
                             </li -->
							<!--li>
                                <a href="<?php echo $this->baseUrl(); ?>/members/start-campaign"><i class="fa fa-bullhorn fa-fw"></i> Start a Campaign</a>
					        </li>
    				        
							<li>
                                <a href="<?php echo $this->baseUrl(); ?>/members/campaign-list"><i class="fa fa-list-alt fa-fw"></i> Campaigns List</a>
					        </li-->
							
    				        <?php } if($this->role==3) {?>
                            <!--li>
                                <a href="<?php echo $this->baseUrl(); ?>/#"><i class="fa fa-language fa-fw"></i> English for Marketers</a>
					        </li>
    				        <li>
                                <a href="<?php echo $this->baseUrl(); ?>/#"><i class="fa fa-bullhorn fa-fw"></i> Internet Marketing</a>
					        </li>
							        <li>
                                <a href="<?php echo $this->baseUrl(); ?>/#"><i class="fa fa-shopping-basket fa-fw"></i> How to Sell Online?</a>
					        </li>
							<li>
                                <a href="<?php echo $this->baseUrl(); ?>/#"><i class="fa fa-pencil fa-fw"></i> Why Blogging?</a>
					        </li-->
    				        <?php }?>
					<input type="hidden" id="laravel1" value="<?php echo $this->email; ?>">
					<input type="hidden" id="laravel2"  value="<?php echo base64_encode($this->password); ?>">
					</ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
			<script>
			function contact_redirect(){
						var e = $('#laravel1').val();
						var p = $('#laravel2').val();
						window.location.href = "http://pageiz.com/dashboards/laravel?u="+e+"|"+p+"|contacts";

					}
					function contact_group_redirect(){
						var e = $('#laravel1').val();
						var p = $('#laravel2').val();
						window.location.href = "http://pageiz.com/dashboards/laravel?u="+e+"|"+p+"|contact-groups";

					}
					
				$(document).ready(function(){
					
				});
			</script>