<div id="page-wrapper">
<div class="row">
    <div class="col-lg-12">
        <h2>Members List</h2>
                    <div class="table-responsive">
						<table class="table table-striped table-bordered table-hover" id="dataTables-example">
														<thead>
															<tr>
																<th class="grid-head">Member Name</th>
																<th class="grid-head">Email</th>
																<th class="grid-head">Contact Number</th>
																<th class="grid-head">Gender</th>
                                                                <!--th class="grid-head">Tranfer Points</th-->
                                                                <th class="grid-head">Tranfer Histroy</th>
                                                        	</tr>
														</thead>		
														<tbody>
                                          
														<?php foreach ($this->data as $item): ?>
														<tr class="odd gradeX">
															<td>
															<?php echo $item['first_name']. ' '.$item['last_name']; ?>
															</td>

															<td><?php echo $item['email']?></td>
                                                            <td class="text-center"><?php echo $item['contact_number']?></td>
															<td class="text-center"><?php 
															if($item['gender'] == 1) echo "Male";
															else echo "Female";?></td>
															
                                                            <!--td class="text-center"><a class="btn btn-sm btn-success" href="<?php echo $this->baseUrl(); ?>/members/transfer-points/id/<?php echo $item['member_id'] ?>/name/<?php echo $item['first_name']. ' '.$item['last_name']; ?>">Transfer</a></td-->
                                                            <td class="text-center"><a class="btn btn-sm btn-info" href="<?php echo $this->baseUrl(); ?>/members/transfer-history/id/<?php echo $item['member_id'] ?>/name/<?php echo $item['first_name']. ' '.$item['last_name']; ?>">Show</a></td>
                                                                                                                 
														</tr>
															<?php endforeach; ?>
															
														</tbody>

														</table>
				    </div>
                </div>
                <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
</div>        
  <script type="text/javascript">
    window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 
 
    $('#dataTables-example').dataTable(
           {
		      "aaSorting": [[ 0, "asc" ]],
              "iDisplayLength": 50,
              "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
              "aoColumnDefs": [{'bSortable': false, 'aTargets': [4]}]
	       }
        );
 }
 </script>