<div id="page-wrapper">
<div class="row">
    <div class="col-md-12">
        <h2>New Campaign Offers</h2>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
				<tr>
				    <th>Campaign Name</th>
                    <th>Campaign Type</th>
				    <th>Budget</th>
                    <th>Detail</th>
                    <th>Action</th>
                </tr>
				</thead>		
				<tbody>
                    <tr>
                        <td>Campaign One</td>
                        <td>Product</td>
                        <td>RM220</td>
                        <td><a href="<?php echo $this->baseUrl();?>/members/campaign-detail" class="btn btn-sm btn-info">View</a></td>
                        <td><a href="#" class="btn btn-sm btn-success">Interested</a></td>                        
                    </tr>
                    <tr>
                        <td>Campaign Two</td>
                        <td>Product</td>
                        <td>RM190</td>
                        <td><a href="<?php echo $this->baseUrl();?>/members/campaign-detail" class="btn btn-sm btn-info">View</a></td>
                        <td><a href="#" class="btn btn-sm btn-success">Interested</a></td>                        
                    </tr>
                    <tr>
                        <td>Campaign Three</td>
                        <td>Service</td>
                        <td>RM250</td>
                        <td><a href="<?php echo $this->baseUrl();?>/members/campaign-detail" class="btn btn-sm btn-info">View</a></td>
                        <td><a href="#" class="btn btn-sm btn-success">Interested</a></td>                        
                    </tr>
                    <tr>
                        <td>Campaign Four</td>
                        <td>Business</td>
                        <td>RM130</td>
                        <td><a href="<?php echo $this->baseUrl();?>/members/campaign-detail" class="btn btn-sm btn-info">View</a></td>
                        <td><a href="#" class="btn btn-sm btn-success">Interested</a></td>                        
                    </tr>
                </tbody>
                </table>
        </div>
    </div>
</div>
</div>

<script type="text/javascript">
    $(function(){
    $('#dataTables-example').dataTable(
           {
		      "aaSorting": [[ 4, "desc" ]],
              "iDisplayLength": 50,
              "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]]
	       }
        );
    });
 </script>