<style>
.errors {
    color: #ff0000;
    font-weight: bold;
}
</style>
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                         <div class="col-lg-9 col-md-16">
                         <h3></h3>
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-user fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Add New Marketer</div>
                                    <!--span>200 Points will be deducted from your points on member creation</span-->
                                </div>
                            </div>
                        </div>
                        
                            <div class="panel-footer">
                                <span class="pull-left">Enter Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                <form  action="" method="post"  enctype="multipart/form-data" role="form">
                                 <?php echo $this->form->csrf; ?>   
				                        <table class="table table-striped table-bordered table-hover">
												<tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
											         <tr><td><label>Photo (optional):</label></td>
                                                        <td><?php echo $this->form->photo ?></td>
                                                     </tr>
                                                     <?php echo $this->form->role_id; ?>
                                                     <?php echo $this->form->first_name; ?>
                                                    <?php echo $this->form->last_name; ?>
                                                    <?php echo $this->form->gender; ?>
                                                    <?php echo $this->form->email; ?>
                                                    <?php echo $this->form->contact_number; ?>
                                                    <?php echo $this->form->ic_passport; ?>
                                                    <?php echo $this->form->street_address; ?>
                                                    <!--tr>
                                                        <td><label for="points"> Points </label></td>
                                                        <td><input type="text" id="points" name="points" class="form-control" readonly="" value="200" />
                                                        Total Points: <?php echo $this->total_points; ?>&nbsp;|&nbsp; Balance: <?php echo $this->member_blc; ?> 
                                                        </td>                                                        
                                                    </tr-->
                                                    <!--input type="hidden" id="amount" name="amount" class="form-control" readonly="" value="0" /-->
                                                    <!--tr>
                                                        <td><label for="amount">* Amount RM </label></td>
                                                        <td></td>
                                                        
                                                    </tr-->
                                                  <tr>
                                                    <td  colspan='2'><?php echo $this->form->Save ?></td>				
                                                  </tr>
                                            </table>
                  	             </form>	
                                
                                
                                </div>
                            </div>
                        
                    </div>
                </div>
                
                
          
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->


<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-2.1.1.min.js"></script>
  <script type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show().delay(7000).hide('slow');
		<?php } ?>
 }
 
    /*$('#points').change(function(){
        var points = $(this).val();
        
        if(points==200){
            $('#amount').val(100);
        }
        
        if(points==400){
            $('#amount').val(200);
        }
        
        if(points==600){
            $('#amount').val(300);
        }
    });*/
    
 </script>