<div id="page-wrapper" style="padding-top: 10px;">
    
<div class="row">
    <div class="col-lg-12">
        <h2>Transfer Pages</h2>
        <div id="msg"><?php echo $this->msg;?></div>
            <form method="post" action="">
            
            <div class="row">
                <div class="col-lg-6"><?php echo $this->member_ddl;?></div>
                <div class="col-lg-6">
                    <input type="submit" class="btn btn-warning" id="submit" value="Transfer"/>
                </div>
            </div>
            <br />
                    <div class="table-responsive">
                    
						<table class="table table-striped table-bordered table-hover" id="dataTables-example">
														<thead>
															<tr>
																<th class="grid-head">Page Title</th>
																<th class="grid-head"> Status</th>
																<th class="grid-head"> Publish Date</th>
                                                                <th class="grid-head"> Activation Date</th>
                                                                <th class="grid-head"> Expire Date</th>
																<th class="grid-head">                                                                
                                                                <label><input type="checkbox" name="allbox" id="allbox" value="0" onclick="checkAll(this.value);" /> Select All</label>
                                                                </th>
                                                        	</tr>
														</thead>		
														<tbody>
                                          
														<?php $counter=0; foreach ($this->data as $item): ?>
														<tr class="odd gradeX">
															<td>
															<?php echo $item['title'];?>
															</td>
                                                            <td style="text-align:center;">
															     <?php if($item['is_in_draft'] > 0 ) echo "Drafted"; else echo "Published"; ?>
															</td>
															<td style="text-align:center;">
															     <?php if($item['is_in_draft'] > 0 ) echo ""; else echo date('m/d/Y h:i A', strtotime($item['date_published'])); ?>
															</td>
                                                            
                                                            <td style="text-align:center;">
                                                            
                                                            </td>
                                                            
                                                            <td style="text-align:center;">
															     <?php echo date('m/d/Y', strtotime($item['expiry_date'])); ?>
															</td>

															<td  style="text-align:center;"><input type="checkbox" name="bulk_share[]" id="check_<?php echo $counter++;?>" class="form-control" value="<?php echo $item['page_id'] ?>"/></td>
                                                                                                                
														</tr>
															<?php endforeach; ?>
															
														</tbody>

														</table>
                        
				    </div>
                    </form>
                </div>
                <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
</div>

  <script type="text/javascript">
    $(function(){
        <?php if(!isset($this->msg)){ ?>
			$('#msg').hide();			
		<?php } else{ ?>
			$('#msg').show().delay(5000).hide('slow');
		<?php } ?>
        
    $('#dataTables-example').dataTable(
           {
		      "aaSorting": [[ 4, "desc" ]],
              "iDisplayLength": 50,
              "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
              "aoColumnDefs": [{'bSortable': false, 'aTargets': [5]}]
	       }
        );
        
        $("form input[id='submit']").click(function() {  // triggred submit		
    		var count_checked = $("[name='bulk_share[]']:checked").length; // count the checked
    		if(count_checked == 0) {
    			alert("Please select a atleast one page to transfer.");
    			return false;
    		} 
    		 else {
    			return confirm("Are you sure, you want to transfer these pages?");	
    		  }		
    	});
    }); //ready function end
    
    function checkAll(a)
	{
	    var total = $('#dataTables-example tr:not(:has(th))').length;
        
		if(a == 0)
		{
			for(q=0;q<total;q++)
			{
                $('#check_'+q).prop('checked', true);
			}
            $('#allbox').val(1);
		}

		if(a == 1)
		{
			for(q=0;q<total;q++)
			{
                $('#check_'+q).prop('checked', false);
			}

            $('#allbox').val(0);
		}
	}
    
    
 </script>