        <!-- Page Content -->
<style>
.set-basic1{
margin-top:4%;
float:left;
}
</style>
     
	 <div id="page-wrapper">
            <div class="row">
            <div class="col-lg-12">
			<div class="col-lg-11">
            <div class="row" style="height:50px; padding:0; margin:0">
                 <div class="col-xs-5">
 <!--                	<table class="table">
                    <tr><td> <a href="<?php echo $this->baseUrl(); ?>/members/bdlist"> <i class="fa fa-list  alert-primary"></i> List</a></td>
                    <td>  <a href="<?php echo $this->baseUrl(); ?>/members/manage-ad/id/<?php echo $this->id ?>"> <i class="fa fa-plus alert-primary"></i> Manage AD</a></td>
                    </tr>
                    </table>-->
                 </div>
                 </div>
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-key fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Change Password</div>
                            
                                </div>
                            </div>
                        </div>
                       
                            <div class="panel-body">
                                <!--span class="pull-left"><ul class="nav nav-tabs" role="tablist">
                                  <li><a href="<?php echo $this->baseUrl(); ?>/members/basic-update/id/<?php echo $this->hop_id  ?>">Basics</a></li>
                                  <li><a href="<?php echo $this->baseUrl(); ?>/members/delivery-address/id/<?php echo $this->id ?>">Delivery Address</a></li>
                                  <?php /*?><li><a href="<?php echo $this->baseUrl(); ?>/members/billing-address/id/<?php echo $this->id ?>">Billing Address</a></li><?php */?>
                                  <li class="active"><a href="<?php echo $this->baseUrl(); ?>/members/pass-update/id/<?php echo $this->id ?>">Password</a></li>
                                </ul></span-->

<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
<div class="clearfix">
                                    <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data" >
                                       	
										<table class="table table-striped table-bordered table-hover set-basic1">
                                    	<?php if(isset($this->msg)){ ?>
                                        <tr id='msg'><td colspan='2'><div style="font-weight: bold; color: #060"><?php echo $this->msg ?></div></td></tr>
                                     <?php } ?>
							
                                           
										   <tr>
		    <td><label> Current Password </label></td>
				  <td colspan='2'>
				      <div class="input-control text" data-role="input-control">
                  <?php echo $this->form->pwd_current  ?>
                  </div>
                  </td></tr>
				  <input type="hidden" name="email" value="<?php echo $this->email;?>">
				  <input type="hidden" name="mamber_id" value="<?php echo $this->member_id;?>">
				  
				  
				     <tr>
		    <td><label> New Password </label></td>
				  <td colspan='2'>
				      <div class="input-control text" data-role="input-control">
                  <?php echo $this->form->pwd  ?>
                  </div>
                  </td></tr>
								
                     <tr>
		    <td><label> Confirm Password </label></td>
				  <td colspan='2'>
				      <div class="input-control text" data-role="input-control">
                  <?php echo $this->form->pwd_confirm  ?>
                  </div>
                  </td></tr>
               					</table>
								
					
				  <div class="col-md-2 col-md-offset-8">
    <?php echo $this->form->submit?>
   </div>
									</form>
	                              
                                </div>
                            </div>
                         <a href="#">
                         <div class="panel-footer">
                         </div>
                        </a>
                    </div>
                </div>
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



