        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
            <div class="col-lg-12">
			<div class="col-lg-11">
            <div class="row" style="height:50px; padding:0; margin:0">
                 <div class="col-xs-5">
 <!--                	<table class="table">
                    <tr><td> <a href="<?php echo $this->baseUrl(); ?>/members/bdlist"> <i class="fa fa-list  alert-primary"></i> List</a></td>
                    <td>  <a href="<?php echo $this->baseUrl(); ?>/members/manage-ad/id/<?php echo $this->id ?>"> <i class="fa fa-plus alert-primary"></i> Manage AD</a></td>
                    </tr>
                    </table>-->
                 </div>
                 </div>
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-user fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Manage Profile</div>
                            
                                </div>
                            </div>
                        </div>
                       
                            <div class="panel-body">
                                <span class="pull-left"><ul class="nav nav-tabs" role="tablist">
 <li  class="active"><a href="<?php echo $this->baseUrl(); ?>/members/profile/id/<?php echo $this->id ?>">Basics</a></li>
  <li><a href="<?php echo $this->baseUrl(); ?>/members/delivery-address/id/<?php echo $this->id ?>">Delivery Address</a></li>
 <?php /*?> <li><a href="<?php echo $this->baseUrl(); ?>/members/billing-address/id/<?php echo $this->id ?>">Billing Address</a></li><?php */?>
  <li><a href="<?php echo $this->baseUrl(); ?>/members/pass-update/id/<?php echo $this->id ?>">Password</a></li>
</ul></span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                  
                                    <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data" >
                                       	<table class="table table-striped table-bordered table-hover">
                                    	<tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
                                     <?php /*?>  <?php echo $this->form->first_name; ?>
                                        <?php echo $this->form->last_name; ?>
                                         <?php echo $this->form->telephone; ?>
                                          <?php echo $this->form->mobile; ?>
                                         <?php echo $this->form->website; ?>
                                           <?php echo $this->form->country; ?><?php */?>
                                           <tr id="state-reg"> 
                                          <td><strong>* Select State
                                                </strong>
                                                </td>
                                                <td><?php echo $this->state_name ?></td>
                                           </tr> 
                                              	 <tr id="state_sel">
												<td><strong>* Select State
                                                </strong>
                                                </td>
                                                <td>
												<div id='state'> </div>
                                                </td>
                                                </tr>
                                            
                                            <tr id="city_sel">
												<td><strong>* Select City
                                                </strong>
                                                </td>
                                                <td>
											    <div id='cities'> </div>
                                                </td></tr>
                                                 <tr id="post_sel">
												<td><strong>* Select Postcode
                                                </strong>
                                                </td>
                                                <td>
											    <div id='postcodes'> </div>
                                                </td></tr>
                                        <tr><td>&nbsp;</td><td>
                                 <?php /*?>       <?php echo $this->form->submit?><?php */?>
										</td></tr>
										</table>
									</form>
	                              
                                </div>
                            </div>
                         <a href="#">
                         <div class="panel-footer">
                         </div>
                        </a>
                    </div>
                </div>
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



 <script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }
			function getState(){
			$('tr#state-reg').hide();
		
			var country_id = $('#country_id').val();//select item value from listbox
					$('#country_id').val(country_id);
			 if(country_id == "")return;
						$.post("<?php echo $this->baseUrl()?>/admin/countries/get-state", {country_id: country_id},
						//this is response from controller
						function(data){
							
							$('div#state').html(data);
							$('tr#state_sel').show();
							$('div#state').show();
						});
			}
		
		
			
			function getCities(){
	
			var country_id = $('#country_id').val();//select item value from listbox
			var state_id = $('select#state').val();//select item value from listbox
	
			 if(country_id == "")return;
			 if(state_id == "")return;
			
		/*alert(country_id + " " + state_id);
		return;	
	*/
						$.post("<?php echo $this->baseUrl()?>/admin/countries/get-cities", {country_id: country_id, state_id: state_id},
						function(data){
							
							$('div#cities').html(data);
							$('tr#city_sel').show();
							$('div#cities').show();
						});
			}
			
			
			
			
			
			function getPostcodes(){
			var country_id = $('#country_id').val();//select item value from listbox
			var state_id = $('select#state').val();//select item value from listbox
	       var city_id = $('select#city').val();
		  
			 if(country_id == "")return;
			 if(state_id == "")return;
			  if(city_id == "")return;
	

						$.post("<?php echo $this->baseUrl()?>/admin/countries/get-postcodes", {country_id: country_id, state_id: state_id, city_id: city_id},
						function(data){
							
							$('div#postcodes').html(data);
							$('tr#post_sel').show();
							$('div#postcodes').show();
						});
			}
			
			
			function savePostcode(){
				var postcode_id = $('select#postcode').val();
				var areas = $('#areas').val();
				
				if(postcode_id == 0){
					$('tr#msg').show();
					$('td#td_msg').html("<div class='alert alert-danger'>Please Select Postcode</div>")
					$('tr#msg').hide(6000);
					return;	
				}
				if(areas == ''){
					$('tr#msg').show();
					$('td#td_msg').html("<div class='alert alert-danger'>Please Enter Near By Postcodes separated by comma</div>")
					$('tr#msg').hide(6000);
					return;	
				}
					
				$.post("<?php echo $this->baseUrl()?>/admin/postcodes/save-near-postcode", {postcode_id: postcode_id, areas: areas},
						//this is response from controller
				function(data){
					$('tr#msg').show();
					$('td#td_msg').html(data)
					$('tr#msg').hide(6000);
					return;	
							
						});
				}
			
	
 </script>