<div id="page-wrapper">
    <div class="row">
            <div class="col-md-12">
               <ul class="menu-links">
        	       <li><a href="<?php echo $this->baseUrl(); ?>/members/new" title="Create new member">New Member</a></li>
                   <li><a href="<?php echo $this->baseUrl(); ?>/members" title="View member list">Member List</a></li>
               </ul>
            </div>
    </div>
<div class="row">
    <div class="col-lg-12">
        <h2>Transacton Histroy of <?php echo ucwords($this->member_name);?></h2>
                    <div class="table-responsive">
						<table class="table table-striped table-bordered table-hover" id="dataTables-example">
														<thead>
															<tr>
																<th>Points</th>
																<th>Date</th>
                                                        	</tr>
														</thead>		
														<tbody>
                                          
														<?php foreach ($this->data as $item): ?>
														<tr class="odd gradeX">
															<td>
															<?php echo $item['points_debit'];?>
															</td>

															<td><?php echo date('m/d/Y h:i A', strtotime($item['trans_date'])); ?></td>
                                                                                                                
														</tr>
															<?php endforeach; ?>
															
														</tbody>

														</table>
				    </div>
                </div>
                <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
</div>

  <script type="text/javascript">
    $(function(){
    $('#dataTables-example').dataTable(
           {
		      "aaSorting": [[ 1, "desc" ]],
              "iDisplayLength": 50,
              "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]]
	       }
        );
    });
 </script>