<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2/js/select2.min.js"></script>
<!-- Page Content -->
            <div class="row" style="padding-top: 30px;">
            <div class="col-lg-10 col-lg-offset-1">
            <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-files-o fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Assign Pages</div>
                            
                                </div>
                            </div>
                        </div>
                            <div class="panel-body">

                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                
                                   <form id="add-pages" method="post" action="">  
                                       	<table class="table table-striped table-bordered table-hover">
                                    	   <tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
                                           
                                           <tr>
                                           <td><label>Assign to (member name)</label></td>
                                           <td><strong><?php echo ucwords($this->member_name);?></strong></td>
                                           </tr>
                                           <tr>
                                            <td>
                                                &nbsp;
                                            </td>
                                            <td>
                                                <label><input type="radio" class="status" name="status" value="FREE" checked="" />&nbsp;Free&nbsp;&nbsp;</label>
                                                <label><input type="radio" class="status" name="status" value="PAID" />&nbsp;Paid</label>
                                            </td>
                                           </tr>
                                           <tr>
                                            <td><label>* Activation Date</label></td>
                                            <td>
                                                <div class='input-group'>
                                                <input type="text" name="start_date" id="start_date" class="form-control" readonly="" placeholder="Select start date" required="" />
                                                    <span class="input-group-addon"><span class="fa fa-calendar"></span></span>
                                                </div>
                                            </td>
                                           </tr>
                                           <tr>
                                            <td><label>* Expire Date</label></td>
                                            <td>
                                                <div class='input-group'>
                                                <input type="text" name="end_date" id="end_date" class="form-control" readonly="" placeholder="Select end date" required="" />
                                                    <span class="input-group-addon"><span class="fa fa-calendar"></span></span>
                                                </div>
                                            </td>
                                           </tr>
                                           <tr>
                                                        <td><label for="pages">* No. of Pages</label></td>
                                                        <td>
                                                            <select id="pages" name="pages" class="form-control" style="width: 100%;">
                                                            <?php for($x=1; $x<=50; $x++): ?>
                                                            <option value="<?php echo $x;?>"><?php echo $x;?></option>
                                                            <?php endfor; ?>
                                                            </select>
                                                        </td>
                                           </tr>
                                           <tr>
                                                        <td><label for="amount">* Charges per page RM</label></td>
                                                        <td><input type="text" id="amount" name="amount" class="form-control" value="0" readonly="" required="" /></td>
                                           </tr>
                                           <tr><td colspan="2"><input type="submit" value="Save" class="btn btn-lg btn-primary pull-right" /></td></tr>
                                        </table>
                                   </form>	                            
                            </div>                      
                    </div>                       
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



 <script type="text/javascript">
    window.onload = function () { 
     <?php if(!isset($this->msg)){ ?>
    			$('tr#msg').hide();
    			
    		<?php  } else{
    		?>
    			$('tr#msg').show().delay(7000).hide('slow');
    		<?php } ?>
            
        $('#add-pages').submit(function() {
            var c = confirm("Do you realy want to assign page(s) to this member?");
            return c;
        });
        
        $('#start_date').datepicker({
            format: 'mm/dd/yyyy',
            autoclose: true
          
        }).datepicker("setDate", "0").on('changeDate', function (selected) {
            var startDate = new Date(selected.date.valueOf());
            $('#end_date').datepicker('setStartDate', startDate);
        }).on('clearDate', function (selected) {
            $('#end_date').datepicker('setStartDate', null);
        });
        
        var d = new Date();
        var currDay = d.getDate();
        var nextMonth = d.getMonth()+1;
        var nextYear = d.getFullYear()+1;
        
        var dateStr = nextMonth + "/" + currDay + "/" + nextYear;

        $('#end_date').datepicker({
            format: 'mm/dd/yyyy',
            autoclose: true,
          
        }).datepicker("setDate", dateStr).on('changeDate', function (selected) {
            var endDate = new Date(selected.date.valueOf());
            $('#start_date').datepicker('setEndDate', endDate);            
        }).on('clearDate', function (selected) {
            $('#start_date').datepicker('setEndDate', null);
        });
        
     } // load function end
     
     $('.status').change(function(){
        if($(this).val()=='FREE'){
            $('#amount').val(0).prop('readonly', true);
        } else {
            $('#amount').val(1).removeAttr('readonly');
        }
     });
     
     $('#pages').select2();
     
     /*$('#pages').change(function(){
        var pages = $(this).val() * 1;
        $('#amount').val(pages);
     });*/	
 </script>