        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                         <div class="col-lg-12 col-md-26">
                                      <div class="row" style="height:50px; padding:0; margin:0"><!-- row 1-->
                 <div class="col-xs-3">
                 	
                 </div>
                 </div><!-- ./ row 1-->
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-1">
                                    <i class="fa fa-user fa-5x"></i>
                                </div>
                                <div class="col-xs-6">
                                      <form>
                                <div class="input-group custom-search-form col-xs-6 text-right" style="padding-top:20px">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            </form>
                                </div>
                                <div class="col-xs-5 text-right">
                                
                                    <div class="huge">Business Listings</div>
                            
                                </div>
                            </div>
                        </div>
                       
                        <div class="panel-body">
                         <span class="pull-left"></span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                               
													<table cellpadding="0" cellspacing="0" border="0" class="responsive dynamicTable display table table-bordered" width="100%">
														<thead>
															<tr>
																<th>HO Name</th>
																<th>Description</th>
															   <th>R Price</th>
                                 <th>HO Price</th>
                                 <th>DD Price</th>
                                 <th>Expiry Date</th>
                                 
																                        		<th>Block</th>
                                                               <th>Delete</th>
                                                        	
                                                            </tr>
														</thead>	
                            <tbody>
<tr><td colspan="9">In development Mode</td></tr>
                            </tbody>
                            <?php /*	
														<tbody>
                                                   
                                                        <?php if(isset($this->msg)){ ?>
                                                             <tr id='msg'>
                                                        <td colspan="7"><div class="alert alert-success"><?php echo $this->msg ?></div></td></tr>
                                          <?php } ?>
														<?php if (count($this->paginator)){ ?>
													
														<?php foreach ($this->paginator as $item): ?>
														<tr class="odd gradeX">
															<td>
															<?php echo $item['business_name'] ?>
															</td><td>
															<?php echo $item['short_description']?></td>
															<td>
															<?php if($item['package'] == 1){ ?>
                              <a  class="btn btn-sm btn-default float-right"  href="#">
Free
                              </a>
                            <?php }elseif($item['package'] == 2){ ?>
    <a  class="btn btn-sm btn-warning float-right"  href="#">
A$25
                              </a>
                           <?php }elseif($item['package'] == 3){ ?>
    <a  class="btn btn-sm btn-danger float-right"  href="#">
A$150
                              </a>
                           <?php } ?>  
															</td>
                                                       
														                            
                              
													    
<td>
<?php if($item['is_blocked'] == 1){ ?>
<a class="btn btn-sm btn-success float-right" href="#" onclick="return confirmUnblock(<?php echo $item['member_id'] ?>,<?php echo $item['bd_list_id'] ?>)">Unblock</a>
<?php }else{ ?>
<a class="btn btn-sm btn-warning float-right" href="#" onclick="return confirmBlock(<?php echo $item['member_id'] ?>,<?php echo $item['bd_list_id'] ?>)">Block</a>
<?php } ?>

                                </td>
													    <td><a class="btn btn-sm btn-danger float-right" href="#" onclick="return confirmDelete(<?php echo $item['member_id'] ?>,<?php echo $item['bd_list_id'] ?>)">Delete</a></td>
														</tr>
															<?php endforeach; ?>
															<tr><td colspan='9'>
															<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>
															</td>
															</tr><?php }else{ ?>
											
															<tr><td colspan="7"><div class="panel"><h4>Member has Zero Business Lists, Send email to invite user for creating a business List</h4></div></td></tr>
															<?php } ?>
														</tbody>
 */?>
														</table>
												</div>

                                 </div>
                                 <a href="#">
                            <div class="panel-footer">
                                
                                 </div>
                        </a> 
                            </div>
                           
                        </div>
                    </div>
                </div>
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



<script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
		
$('#msg').fadeOut(5000);
 }
 
function confirmDelete(mid, id){
var r = confirm("Deleting will remove business list information permanently! Are you sure? ");
if (r == true) {
window.location.assign("<?php echo $this->baseUrl(); ?>/admin/members/delete-list/mid/"+ mid +"/id/" + id);
return false;
}
}


function confirmBlock(mid, id){
var r = confirm("Are you sure?");
if (r == true) {
window.location.assign("<?php echo $this->baseUrl(); ?>/admin/members/block-list/mid/"+ mid +"/id/" + id);    
} else {
return false;
}
}

function confirmUnblock(mid, id){
var r = confirm("Are you sure?");
if (r == true) {
window.location.assign("<?php echo $this->baseUrl(); ?>/admin/members/unblock-list/mid/"+ mid +"/id/" + id);    
} else {
return false;
}
}

</script>