<div class="row">
    <div class="col-lg-12">
    <h2>Member List</h2>
        <div class="table-responsive">
                         <table class="table table-striped table-bordered table-hover" id="dataTables-example">
														<thead>
															<tr>
																<!--th class="grid-head">Balance</th-->
                                                                <?php if($this->role==1) echo '<th class="grid-head">Role</th>'; ?>                                                                
                                                                <th class="grid-head">Member Name</th>
																<th class="grid-head">Email</th>
																<th class="grid-head">Contact Number</th>
																<th class="grid-head">Gender</th>
                                                                <!--th class="grid-head">Add Points</th>
                                                                <th class="grid-head">Tranfer Histroy</th-->
                                                                <th class="grid-head">Assign Pages</th>
                                                        	</tr>
														</thead>		
														<tbody>
                                          
													<?php foreach ($this->data as $item): ?>
														<tr class="odd gradeX">
                                                            <!--td class="text-center">
                                                                <?php //$debit_point_total =0; $credit_point_total =0; foreach($this->trans_list as $tl): if($tl['member_id']==$item['member_id']): 
                                                                    //$debit_point_total += $tl['points_debit'];
                                                                    //$credit_point_total += $tl['points_credit'];                                                                        
                                                                //endif; endforeach; echo ($debit_point_total - $credit_point_total); ?>
                                                            </td-->
                                                            
															<?php if($this->role==1){ ?>
                                                            <td class="text-center">
                                                                <?php if($item['role_id']==1) echo 'Free Member'; 
                                                                    if($item['role_id']==2) echo 'Business Owner'; 
                                                                    if($item['role_id']==3) echo 'Marketer'; ?>
                                                            </td><?php }?>
                                                            <td>
															<?php echo $item['first_name']. ' '.$item['last_name']; ?>
															</td>

															<td><?php echo $item['email']?></td>
                                                            <td class="text-center"><?php echo $item['contact_number']?></td>
															<td class="text-center"><?php 
															if($item['gender'] == 1) echo "Male";
															else echo "Female";?></td>
															
                                                            <!--td class="text-center"><a class="btn btn-sm btn-success" href="<?php echo $this->baseUrl(); ?>/admin/members/transfer-points/id/<?php echo $item['member_id'] ?>/name/<?php echo $item['first_name']. ' '.$item['last_name']; ?>">Add</a></td>
                                                            <td class="text-center"><a class="btn btn-sm btn-info" href="<?php echo $this->baseUrl(); ?>/admin/members/transfer-history/id/<?php echo $item['member_id'] ?>/name/<?php echo $item['first_name']. ' '.$item['last_name']; ?>">Show</a></td-->
                                                            <td class="text-center"><a class="btn btn-sm btn-info" href="<?php echo $this->baseUrl(); ?>/admin/members/add-pages/id/<?php echo $item['member_id'] ?>/name/<?php echo $item['first_name']. ' '.$item['last_name']; ?>">Assign</a></td>
														</tr>
															<?php endforeach; ?>
														</tbody>

					       </table>
                    </div>
                                
                </div>
                <!-- /.col-lg-12 -->
</div>
<!-- /.row -->


  <script type="text/javascript">
    window.onload = function () { 
    <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
        
        $('#dataTables-example').dataTable(
           {
                <?php if($this->role==1) { ?>
		      "aaSorting": [[ 0, "asc" ]],
              <?php } else { ?>
              "aaSorting": [[ 1, "asc" ]],
              <?php } ?>
              "iDisplayLength": 50,
              "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
              <?php if($this->role==1) { ?>
              "aoColumnDefs": [{'bSortable': false, 'aTargets': [5]}]
              <?php } else { ?>
              "aoColumnDefs": [{'bSortable': false, 'aTargets': [4]}]
              <?php } ?>
	       }
        );
    }
 </script>