        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                         <div class="col-lg-12 col-md-26">
                                      <div class="row" style="height:50px; padding:0; margin:0"><!-- row 1-->
                 <div class="col-xs-3">
                 	
                 </div>
                 </div><!-- ./ row 1-->
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-1">
                                    <i class="fa fa-user fa-5x"></i>
                                </div>
                                <div class="col-xs-6">
                                      <form>
                                <div class="input-group custom-search-form col-xs-6 text-right" style="padding-top:20px">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            </form>
                                </div>
                                <div class="col-xs-5 text-right">
                                
                                    <div class="huge">Members List</div>
                            
                                </div>
                            </div>
                        </div>
                       
                        <div class="panel-body">
                         <span class="pull-left"></span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                               
													<table cellpadding="0" cellspacing="0" border="0" class="responsive dynamicTable display table table-bordered" width="100%">
														<thead>
															<tr>
																<th>Name</th>
																<th>Email</th>
															   <th>Contact Number</th>
																<th>BLs</th>
                                                               <th>HOs</th>
                                                        		<th>Block</th>
                                                                <th>Edit</th>
                                                               <th>Delete</th>
                                                        	
                                                            </tr>
														</thead>		
														<tbody>
                                                   
                                                        <?php if(isset($this->msg)){ ?>
                                                             <tr id='msg'>
                                                        <td colspan="7"><div class="alert alert-success"><?php echo $this->msg ?></div></td></tr>
                                          <?php } ?>
														<?php if (count($this->paginator)){ ?>
													
														<?php foreach ($this->paginator as $item): ?>
														<tr class="odd gradeX">
															<td>
															<?php echo $item['first_name'] ?>
															&nbsp; 
															<?php echo $item['last_name']?></td>
															<td>
															<?php echo $item['email'] ?>
															</td>
                                                       
															<td>
															<?php echo $item['contact_number'] ?>
															</td>
                                                        <td>
                                                            <a  class="btn btn-sm btn-success float-right"  href="<?php echo $this->baseUrl(); ?>/admin/members/bl-list/id/<?php echo $item['member_id'] ?>">BLs</a></td>
                                                            	
															<td><a class="btn btn-sm btn-info float-right" href="<?php echo $this->baseUrl(); ?>/admin/members/ho-list/id/<?php echo $item['member_id'] ?>">HOs</a></td>
													    
<td>
<?php if($item['is_blocked'] == 1){ ?>
<a class="btn btn-sm btn-success float-right" href="#" onclick="return confirmUnblock('<?php echo $item['first_name'] ?>',<?php echo $item['member_id'] ?>)">Unblock</a>
<?php }else{ ?>
<a class="btn btn-sm btn-warning float-right" href="#" onclick="return confirmBlock('<?php echo $item['first_name'] ?>',<?php echo $item['member_id'] ?>)">Block</a>
<?php } ?>

                                </td>
													    <td><a class="btn btn-sm btn-warning" href="<?php echo $this->baseUrl(); ?>/admin/members/edit/id/<?php echo $item['member_id'] ?>">Edit</a></td>
                                                        <td><a class="btn btn-sm btn-danger float-right" href="#" onclick="return confirmDelete('<?php echo $item['first_name'] ?>',<?php echo $item['member_id'] ?>)">Delete</a></td>
														</tr>
															<?php endforeach; ?>
															<tr><td colspan='8'>
															<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>
															</td>
															</tr><?php }else{ ?>
											
															<tr><td colspan="7"><h4>There are no users created! Please create</h4></td></tr>
															<?php } ?>
														</tbody>

														</table>
												</div>

                                 </div>
                                 <a href="#">
                            <div class="panel-footer">
                                
                                 </div>
                        </a> 
                            </div>
                           
                        </div>
                    </div>
                </div>
                
                
          
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



<script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
		
$('#msg').fadeOut(5000);
 }
 
function confirmDelete(name, id){
var r = confirm("Deleting "+ name +" will remove all user records permanently! As Business Lists and Hot Offers also ");
if (r == true) {
window.location.assign("<?php echo $this->baseUrl(); ?>/admin/members/delete-all/id/" + id);
return false;
}
}


function confirmBlock(name, id){
var r = confirm("Blocking "+ name +" will block all his/her records!");
if (r == true) {
window.location.assign("<?php echo $this->baseUrl(); ?>/admin/members/block-all/id/" + id);    
} else {
return false;
}
}

function confirmUnblock(name, id){
var r = confirm("Unblocking "+ name +" will open all his/her records!");
if (r == true) {
window.location.assign("<?php echo $this->baseUrl(); ?>/admin/members/unblock-all/id/" + id);    
} else {
return false;
}
}

</script>