<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2/js/select2.min.js"></script>
<style>
.stepwizard-step p {
    margin-top: 10px;
}

.stepwizard-row {
    display: table-row;
}

.stepwizard {
    display: table;
    width: 100%;
    position: relative;
}

.stepwizard-step button[disabled] {
    opacity: 1 !important;
    filter: alpha(opacity=100) !important;
}

.stepwizard-row:before {
    top: 14px;
    bottom: 0;
    position: absolute;
    content: " ";
    width: 100%;
    height: 1px;
    background-color: #ccc;
    z-order: 0;

}

.stepwizard-step {
    display: table-cell;
    text-align: center;
    position: relative;
}

.btn-circle {
  width: 30px;
  height: 30px;
  text-align: center;
  padding: 6px 0;
  font-size: 12px;
  line-height: 1.428571429;
  border-radius: 15px;
}
div.mem_form{
	display:none;
}
.switch {
  position: relative;
  display: inline-block;
  width: 60px;
  height: 34px;
}

.switch input {display:none;}

.slider {
  position: absolute;
  cursor: pointer;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: #ccc;
  -webkit-transition: .4s;
  transition: .4s;
}

.slider:before {
  position: absolute;
  content: "";
  height: 26px;
  width: 26px;
  left: 4px;
  bottom: 4px;
  background-color: white;
  -webkit-transition: .4s;
  transition: .4s;
}

input:checked + .slider {
  background-color: #2196F3;
}

input:focus + .slider {
  box-shadow: 0 0 1px #2196F3;
}

input:checked + .slider:before {
  -webkit-transform: translateX(26px);
  -ms-transform: translateX(26px);
  transform: translateX(26px);
}

/* Rounded sliders */
.slider.round {
  border-radius: 34px;
}

.slider.round:before {
  border-radius: 50%;
}
</style>
<div class="row">
    <div class="col-lg-12">
    <h2>New Page</h2>
          <div class="container">
		  <div class="col-md-8 col-md-offset-2">
		<div class="stepwizard">
			<div class="stepwizard-row setup-panel">
				<div class="stepwizard-step">
					<a href="#step-1" type="button" class="btn btn-primary btn-circle">1</a>
					<p>Select Marketer</p>
				</div>
				<div class="stepwizard-step">
					<a href="#step-2" type="button" class="btn btn-default btn-circle" disabled="disabled">2</a>
					<p>Select Member</p>
				</div>
				<div class="stepwizard-step">
					<a href="#step-3" type="button" class="btn btn-default btn-circle" disabled="disabled">3</a>
					<p>Create New Page</p>
				</div>
			</div>
		</div>
		<?php
			if(isset($this->msg)){
				echo  $this->msg;
			}
		?>
		<form role="form" method="POST" action="">
			<div class="row setup-content" id="step-1">
				<div class="col-xs-12">
					<div class="col-md-12">
						<h3> Select Marketer</h3>
						<div class="form-group">
							<label class="control-label">Select Marketer</label>
							<select class="form-control" id="marketer" name="marketer_id" required>
								<option value="">Select Marketer</option>
								<?php
									foreach($this->marketers as $marketer){ ?>
										<option value="<?php echo $marketer['member_id'] ?>"><?php echo $marketer['first_name'] ?> <?php echo $marketer['last_name'] ?></option>	
								<?php
									}
								?>
							</select>
						</div>
						
						<button class="btn btn-primary nextBtn pull-right" type="button" id="first_btn">Next</button>
					</div>
				</div>
			</div>
			<div class="row setup-content" id="step-2">
				<div class="col-xs-12">
					<div class="col-md-12">
						<h3> Select Member </h3>
						<div class="form-group">
							<label class="control-label">Select Member</label>
							<select class="form-control" id="member" name="member" required>
								<option value="">Select Member</option>
								<?php
									foreach($this->members as $members){ ?>
										<option value="<?php echo $members['member_id'] ?>"><?php echo $members['first_name'] ?> <?php echo $members['last_name'] ?> (<?php echo $members['email'] ?>)</option>	
								<?php
									}
								?>
							</select>
						</div>
						<button class="btn btn-primary nextBtn pull-right" type="button" id="second_btn">Next</button>
					</div>
					<h3 class="text-center" style="font-size:10px;">OR</h3>
					<div class="text-center" style="    margin-top: 20px;">
						<a class="btn btn-primary" id="new_member">Create New Member</a>
					</div>
					<div id="message_panel" style="margin:10px;"></div>
					<div id="exist_panel" style="margin:10px;"></div>
					<div  style="margin-top:30px;" id="mem_form" class="mem_form">
					<div class="form-group">
					  <label for="pwd">Select Member Type: *</label>
					  
						<select name="role_id" id="mem_role_id" class="form-control">
							<option value="">Select Type</option>
							<option value="2">Demo</option>
							<option value="2">Business</option>
							<option value="3">Marketer</option>
							<option value="1">Free Member</option>
						</select>
						
					</div>
					<div class="form-group">
					  <label for="pwd">Name: *</label>
					  <input type="text" name="name" class="form-control" id="mem_name" placeholder="Enter Name" >
					</div>
					<div class="form-group">
					  <label for="email">Email: *</label>
					  <input type="email" name="email" class="form-control" id="mem_email" placeholder="Enter email" >
					</div>
					<div class="form-group">
					  <label for="pwd">Phone:</label>
					  <input type="number" name="phone" class="form-control" id="mem_phone" placeholder="Enter Phone" >
					</div>
					<button type="button" id="new_mem_btn" class="btn btn-default">Create</button>
					
					</div>
				</div>
			</div>
			<div class="row setup-content" id="step-3">
				<div class="col-xs-12">
					<div class="col-md-12">
						
						<div class="panel panel-primary">
						  <div class="panel-heading">Create Page</div>
						  <div class="panel-body">
							<table class="table table-striped table-bordered table-hover">
                                    	   
                                           <tr>
                                            <td>
                                                <label>* FREE OR PAID</label>
                                            </td>
                                            <td>
                                                <label><input type="radio" class="status" name="status" value="FREE" checked="" />&nbsp;Free&nbsp;&nbsp;</label>
                                                <label><input type="radio" class="status" name="status" value="PAID" />&nbsp;Paid</label>
                                            </td>
                                           </tr>
                                           <tr>
                                            <td><label>* Activation Date</label></td>
                                            <td>
                                                <div class='input-group'>
                                                <input type="text" name="start_date" id="start_date" class="form-control" readonly="" placeholder="Select start date" required="" />
                                                    <span class="input-group-addon"><span class="fa fa-calendar"></span></span>
                                                </div>
                                            </td>
                                           </tr>
                                           <tr>
                                            <td><label>* Expire Date</label></td>
                                            <td>
                                                <div class='input-group'>
                                                <input type="text" name="end_date" id="end_date" class="form-control" placeholder="Select end date" required="" />
                                                    <span class="input-group-addon"><span class="fa fa-calendar"></span></span>
                                                </div>
                                            </td>
                                           </tr>
                                           <tr>
                                                        <td><label for="pages">* No. of Pages</label></td>
                                                        <td>
                                                            <select id="pages" name="pages" class="form-control" style="width: 100%;">
                                                            <?php for($x=1; $x<=50; $x++): ?>
                                                            <option value="<?php echo $x;?>"><?php echo $x;?></option>
                                                            <?php endfor; ?>
                                                            </select>
                                                        </td>
                                           </tr>
										   <tr>
                                                        <td><label for="pages">* Posts per Page</label></td>
                                                        <td>
                                                            <input id="pages_post" name="pages_post" class="form-control" style="width: 100%;" placeholder="Posts per Page">
                                                        </td>
                                           </tr>
                                           <tr>
                                                        <td><label for="pages">* Price per Page</label></td>
                                                        <td>
                                                            <input id="page_price" name="page_price" class="form-control" style="width: 100%;" placeholder="Page Price">
                                                        </td>
                                           </tr>
                                           <tr>
                                                        <td><label for="pages">* Total Price</label></td>
                                                        <td>
                                                            <input id="total_price" name="total_price" class="form-control" style="width: 100%;" placeholder="Total Price">
                                                        </td>
                                           </tr>
										   <tr>
                                                        <td><label for="pages">* Notes</label></td>
                                                        <td>
                                                            <textarea id="notes" name="notes" class="form-control" placeholder="Notes"></textarea>
                                                        </td>
                                           </tr>
                                        </table>
						  </div>
						</div>
						<div class="panel panel-primary">
						  <div class="panel-heading">Page Settings</div>
						  <div class="panel-body">
							<table class="table table-striped table-bordered table-hover">
                                    	  
                                           
                                           <tr>
                                            <td><label>* Slider</label></td>
                                            <td>
                                                <label class="switch">
													  <input type="checkbox" value="off" name="slider">
													  <div class="slider round"></div>
													</label>
                                            </td>
                                           </tr>
                                           <tr>
                                            <td><label>* Video</label></td>
                                            <td>
                                                <label class="switch">
													  <input type="checkbox" value="off" name="video">
													  <div class="slider round"></div>
													</label>
                                            </td>
                                           </tr>
                                           <tr>
                                            <td><label>* Pop CTA</label></td>
                                            <td>
                                                <label class="switch">
													  <input type="checkbox" value="off" name="pop">
													  <div class="slider round"></div>
													</label>
                                            </td>
                                           </tr>
										   <tr>
                                            <td><label>* Inpage  CTA</label></td>
                                            <td>
                                                <label class="switch">
													  <input type="checkbox" value="off" name="inpage">
													  <div class="slider round"></div>
													</label>
                                            </td>
                                           </tr>
                                        </table>
						  </div>
						</div>
						<button class="btn btn-success pull-right" type="submit">Create Page</button>
					</div>
				</div>
			</div>
			<input type="hidden" value="<?php echo $this->baseUrl();?>" name="base_path" id="base_path" />
		</form>
</div>                   
	</div>   </div>                        <!-- /.col-lg-12 -->
</div>


<script type="text/javascript">
$(document).ready(function () {
	if($('.status').val() == 'FREE'){
		$('#page_price').val(0).prop('readonly', true);
		$('#total_price').val(0).prop('readonly', true);
	}else{
		$('#page_price').val(1).removeAttr('readonly');
		$('#total_price').removeAttr('readonly');
	}
	$('.status').change(function(){
        if($(this).val()=='FREE'){
            $('#page_price').val(0).prop('readonly', true);
			$('#total_price').val(0).prop('readonly', true);

        } else {
            $('#page_price').val(1).removeAttr('readonly');
			$('#total_price').val(1).removeAttr('readonly');

        }
     });
	$('#start_date').datepicker({
            format: 'yyyy-mm-dd',
            autoclose: true
          
        }).datepicker("setDate", "0").on('changeDate', function (selected) {
            var startDate = new Date(selected.date.valueOf());
            $('#end_date').datepicker('setStartDate', startDate);
        }).on('clearDate', function (selected) {
            $('#end_date').datepicker('setStartDate', null);
        });
        
        var d = new Date();
        var currDay = d.getDate();
        var nextMonth = d.getMonth()+1;
        var nextYear = d.getFullYear()+1;
        
        var dateStr = nextMonth + "/" + currDay + "/" + nextYear;

        $('#end_date').datepicker({
            format: 'yyyy-mm-dd',
            autoclose: true,
          
        }).datepicker("setDate", dateStr).on('changeDate', function (selected) {
            var endDate = new Date(selected.date.valueOf());
            $('#start_date').datepicker('setEndDate', endDate);            
        }).on('clearDate', function (selected) {
            $('#start_date').datepicker('setEndDate', null);
        });
	$('#new_member').click(function(){
		$('div.mem_form').fadeIn(400);
	});
	$('#new_mem_btn').click(function(){
		var role = $('#mem_role_id').val();
		var name = $('#mem_name').val();
		var email = $('#mem_email').val();
		var phone = $('#mem_phone').val();
		var url = $('#base_path').val()+'/admin/members/new-page-member';
		if(role !== '' && name !== '' && email !== ''){
			$('#new_mem_btn').html('<i class="fa fa-spinner fa-spin"></i> Creating');
			 $.ajax({
				type    : 'POST',
				data    : { 
							role: role,
							name : name,
							email : email,
							phone : phone
						},
				url     : url,
				success: function (result) {
					var response = $.parseJSON(result);
					
					$('#new_mem_btn').html('Create');
					$('#exist_panel').html(response.content).delay(400).fadeOut();
					if(response.mem_id){
						// alert(response.mem_id);
						$('#message_panel').html('<h4>Please refer to the login details</h4> <h4>Email: ' +response.email + '</h4> <h4>Password:' + response.password+'</h4>').css({"box-shadow": "0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22)", "padding": "20px", "margin-top": "30px"}).fadeIn(1000);
						$('#member')
						 .append('<option value='+response.mem_id+'  selected="selected">'+$('#mem_name').val()+'</option>');
						 $('#member').trigger('change'); 
						$('#second_btn').prop('disabled', false);
						$('div.mem_form').fadeOut(1000);
									}
					// $('#message_panel').text('Member created successfully!').delay(1000).fadeOut();
					$('#mem_role_id').val('');
					$('#mem_name').val('');
					$('#mem_email').val('');
					$('#mem_phone').val('');
				},
				error:function (error) {
					alert('err');
					returnResult = error;  
				}
				});
		}else{
			alert('Please enter details.');
		}
	});
	$('#first_btn').prop('disabled', true);
	$('#second_btn').prop('disabled', true);
	$('#marketer').on('change', function() {
	  if(this.value !== ''){
		  $('#first_btn').prop('disabled', false);
	  }else{
		  $('#first_btn').prop('disabled', true);
	  }
	});
	$('#member').on('change', function() {
	  if(this.value !== ''){
		  $('#second_btn').prop('disabled', false);
	  }else{
		  $('#second_btn').prop('disabled', true);
	  }
	});
    var navListItems = $('div.setup-panel div a'),
            allWells = $('.setup-content'),
            allNextBtn = $('.nextBtn');

    allWells.hide();

    navListItems.click(function (e) {
        e.preventDefault();
        var $target = $($(this).attr('href')),
                $item = $(this);

        if (!$item.hasClass('disabled')) {
            navListItems.removeClass('btn-primary').addClass('btn-default');
            $item.addClass('btn-primary');
            allWells.hide();
            $target.show();
            $target.find('input:eq(0)').focus();
        }
    });

    allNextBtn.click(function(){
        var curStep = $(this).closest(".setup-content"),
            curStepBtn = curStep.attr("id"),
            nextStepWizard = $('div.setup-panel div a[href="#' + curStepBtn + '"]').parent().next().children("a"),
            curInputs = curStep.find("input[type='text'],input[type='url']"),
            isValid = true;

        $(".form-group").removeClass("has-error");
        for(var i=0; i<curInputs.length; i++){
            if (!curInputs[i].validity.valid){
                isValid = false;
                $(curInputs[i]).closest(".form-group").addClass("has-error");
            }
        }

        if (isValid)
            nextStepWizard.removeAttr('disabled').trigger('click');
    });

    $('div.setup-panel div a.btn-primary').trigger('click');
});
$('#pages').select2();
$('#member').select2();
$('#marketer').select2();
</script>


  