<!--link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2/js/select2.min.js"></script-->
<style>
.errors {
    color: #ff0000;
    font-weight: bold;
}
</style>
    <div class="row" style="padding-top: 20px;">
                <div class="col-lg-12">
                         <div class="col-lg-9 col-md-6">
                         <h3></h3>
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-user fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">New Member</div>                                    
                                </div>
                            </div>
                        </div>
                        
                            <div class="panel-footer">
                                <span class="pull-left">Enter Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                <form  action="" method="post"  enctype="multipart/form-data" role="form">
                                 <?php echo $this->form->csrf; ?>   
				                        <table class="table table-striped table-bordered table-hover">
												<tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
											         <tr><td><label>Photo (optional):</label></td>
                                                        <td><?php echo $this->form->photo ?></td>
                                                     </tr>
                                                     <?php echo $this->form->role_id; ?>
                                                     <?php echo $this->form->first_name ?>
                                                    <?php echo $this->form->last_name ?>
													<?php echo $this->form->password ?>
												    <?php echo $this->form->gender ?>
                                                    <?php echo $this->form->email ?>
                                                    <?php echo $this->form->contact_number ?>
                                                    <?php echo $this->form->ic_passport ?>
                                                    <?php echo $this->form->street_address ?>
                                                    <!--tr>
                                                        <input type="hidden" name="amount" value="0" />
                                                        <td><label for="no_of_members">* Member Acc.</label></td>
                                                        <td>
                                                            <select id="no_of_members" class="form-control" style="width: 100%;">
                                                            <?php //for($x=1; $x<=1000; $x++): ?>
                                                            <option value="<?php //echo $x;?>"><?php //echo $x;?></option>
                                                            <?php //endfor; ?>
                                                            </select>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td><label for="points">* Points </label></td>
                                                        <td><input type="text" id="points" name="points" class="form-control" value="200" readonly="" /></td>
                                                    </tr-->
                                                  <tr>
                                                    <td colspan='2'><?php echo $this->form->Save ?></td>				
                                                  </tr>
                                            </table>
                  	             </form>	
                                
                                
                                </div>
                            </div>
                        
                    </div>
                </div>
                
                
          
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
       
  <script  type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show().delay(7000).hide('slow');
		<?php } ?>
 }
 
 $('#no_of_members').select2();
 
 $('#no_of_members').change(function(){
    var points = $(this).val() * 200;
    $('#points').val(points);  
 });
 
 </script>