<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2/js/select2.min.js"></script>
<!-- Page Content -->
        <div id="page-wrapper">
        <div class="row">
            <div class="col-md-12">
               <ul class="menu-links">
        	       <li><a href="<?php echo $this->baseUrl(); ?>/admin/members/new" title="Create new member">New Member</a></li>
                   <li><a href="<?php echo $this->baseUrl(); ?>/admin/members" title="View member list">Member List</a></li>
               </ul>
            </div>
        </div>
            <div class="row">
            <div class="col-lg-11">
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-star-half-o fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Transfer Points</div>
                            
                                </div>
                            </div>
                        </div>
                            <div class="panel-body">

                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                
                                  <div id="basic_info">
           
                                   <form id="add-points" method="post" action="">  
                                       	<table class="table table-striped table-bordered table-hover">
                                    	   <tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
                                           <!--tr>
                                            <td><label>No. of pages</label></td>
                                            <td>
                                                <input type="text" name="no_of_pages" class="form-control" />
                                            </td>
                                           </tr-->
                                           <tr>
                                           <td><label>Member Name</label></td>
                                           <td><strong><?php echo ucwords($this->member_name);?></strong></td>
                                           </tr>
                                           <tr>
                                                        <td><label for="points">* Points</label></td>
                                                        <td>
                                                            <select id="points" name="points" class="form-control" style="width: 100%;">
                                                            <?php for($x=200; $x<=10000; $x+=200){ ?>
                                                            <option value="<?php echo $x;?>"><?php echo $x;?></option>
                                                            <?php } ?>
                                                            </select>
                                                        </td>
                                           </tr>
                                           <!--tr>
                                                        <td><label for="points">Points </label></td>
                                                        <td><input type="text" id="points" name="points" class="form-control" value="200" readonly="" /></td>
                                           </tr-->
                                           <tr><td colspan="2"><input type="submit" value="Save" class="btn btn-lg btn-primary pull-right" /></td></tr>
                                        </table>
                                   </form>
	                            </div>
                            </div>
                      
                    </div>
                       <a href="#">
                         <div class="panel-footer">
                         </div>
                        </a>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



 <script type="text/javascript">
    window.onload = function () { 
     <?php if(!isset($this->msg)){ ?>
    			$('tr#msg').hide();
    			
    		<?php  } else{
    		?>
    			$('tr#msg').show().delay(7000).hide('slow');
    		<?php } ?>
            
      $('#add-points').submit(function() {
            var c = confirm("Do you realy want to add points for this member?");
            return c;
        });
     }
     
     $('#points').select2();
     
     $('#no_of_members').change(function(){
        var points = $(this).val() * 200;
        $('#points').val(points);  
     });	
 </script>