    <div class="row">
            <div class="col-lg-12">
			<div class="col-lg-9 col-md-offset-1">
                <div class="row">   
                    <div class="col-xs-3">
                     	<ul class="menu-links">
                        <li> <a href="<?php echo $this->baseUrl(); ?>/admin/categories/list-main-cat"> <i class="fa fa-list"></i> List</a></li>
                        <li>  <a href="<?php echo $this->baseUrl(); ?>/admin/categories/listing-main"> <i class="fa fa-plus"></i> New</a></li>
                        </ul>
                    </div>
                 </div>
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-gear fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Edit Category</div>
                            
                                </div>
                            </div>
                        </div>
						
						<div class="panel-body">
						 <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                  
<form name="cateogyr_form" id="cateogry_form1" action="" method="POST" enctype="multipart/form-data" onsubmit="return mainCatFormVal()"  role="form">
                               
                             <div class=" table-responsive">
							   <table class="table table-striped table-bordered table-hover">
<tr id='msg'><td id='td_msg' colspan='2'><?php echo $this->msg ?></td></tr>

<tr><td colspan="2"><Strong><a href="#">Edit Category Information:</a></Strong></td></tr>
						<?php echo $this->form->category_name ?>
                        <?php echo $this->form->code ?>
                        
						<tr><td><Strong><label>* Category Image</label></Strong></td><td>
						<img src="<?php echo $this->baseUrl(); ?>/images/categories/100X100/<?php echo $this->category_image ?>" alt="Category Image" /></td></tr>
<input type="hidden" name="id" value="<?php echo $this->category_id?>">
<tr>
<td><strong>Upload Image:</strong></td><td>
<?php echo $this->form->myfile ?>										

</td></tr>
<?php echo $this->form->is_main ?>
<?php echo $this->form->is_featured ?>
<td>&nbsp;</td>
<td>  <button class="btn btn-lg btn-primary" type="submit">Update</button>
</td></tr></table>
    </div>
          </form>  
	                              
                                </div>
								</div>   <!--panel body end-->
						
                        <a href="#">
                            <div class="panel-footer">
                            
                            </div> <!--footer pannl end-->
                        </a>
                    </div>
                </div>
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        
<script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }

 </script>