<style> 
.set-sub-cat{
margin-top:30px;
}      
</style>
	  <div class="row">
            <div class="col-lg-12">
			<div class="col-lg-9 col-md-offset-1">
            <div class="row" >
                 <div class="col-xs-12">
                 	<ul class="menu-links">
                    <li> <a href="<?php echo $this->baseUrl(); ?>/admin/categories/list-main-cat"> <i class="fa fa-list"></i> List</a></li>
                    <li>  <a href="<?php echo $this->baseUrl(); ?>/admin/categories/listing-sub"> <i class="fa fa-plus"></i> New</a></li>
                    </ul>
                 </div>
                 </div>
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-gear fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">New Sub-Category</div>
                            
                                </div>
                            </div>
                        </div>
						
						<div class="panel-body">
						 <span class="pull-left"><strong><a href="">Enter Details:</a></strong></span>
                         <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                               <div class="clearfix">
                                  
<form name="cateogyr_form" id="cateogry_form1" action="" method="POST" enctype="multipart/form-data" onsubmit="return FormVal()"  role="form">
                               	
								<div class="table-responsive set-sub-cat">
								<table class="table table-striped table-bordered table-hover">
<tr id='msg'><td id='td_msg' colspan='2'><?php echo $this->msg ?></td></tr>
<?php echo $this->form->category_name ?>		
<?php echo $this->form->code ?>		
								
<tr>
<td><strong>Upload Image:</strong></td><td>
<?php echo $this->form->myfile ?>		

</td></tr>
<?php echo $this->form->is_main ?>
<?php echo $this->form->is_featured ?>

<?php echo $this->form->parent_id ?>
<tr><td><strong>Sub-category level 1 </strong></td><td><div id="sub-cat1"> </div></td></tr>
<tr><td><strong>Sub-category level 2 </strong></td><td><div id="sub-cat2"> </div></td></tr>
<tr><td><strong>Sub-category level 3 </strong></td><td><div id="sub-cat3"> </div></td></tr>

<td>&nbsp;</td>
<td>  <button class="btn btn-lg btn-primary" type="submit">Save</button>
</td></tr></table>

          </div>  <!--table-responsive div end-->
          </form>  
	                              
                                </div>
								</div>  <!--panel body div end-->
						
                        <a href="#">
                            <div class="panel-footer">
  
                            </div>
                        </a>
                    </div>
                </div>
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        
<script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }


 function getSubCat1(){
	hideThreeBoxes();
	$('div#bottom-container').hide();
	var parent_id = $('#parent_id').val();//select item value from listbox
     if(parent_id == "")return;
$.post("<?php echo $this->baseUrl()?>/admin/categories/get-list-sub-cat1", {parent_id: parent_id, size: 1},
//this is response from controller
function(data){
	if(data == "true"){
		$('#next-button').show();
	}else{
		$('div#sub-cat1').html(data);
		$('div#sub-cat1').fadeIn("slow");
                       	}
        getCategoryInfo(parent_id);
	});
}

function getSubCat2(){
	var parent_id = $('select#sub-cat1').val();
	$('#next-button').hide();
        $('div#bottom-container').hide();
         $('#subcat_button').show();
         
	hideTwoBoxes();
	$.post("<?php echo $this->baseUrl()?>/admin/categories/get-list-sub-cat2", {parent_id: parent_id, size: 1},
	//this is response from controller
	function(data){
		if(data == "true"){
		$('#next-button').show();
		}else{
			$('div#sub-cat2').html(data);
			$('div#sub-cat2').fadeIn("slow");
        	$('#next-button').hide();
		}
                 getCategoryInfo(parent_id);
			});

}
//last sub category hirerchy..!
function getSubCat3(){
	var parent_id = $('select#sub-cat2').val();
	$('#next-button').hide();
        $('div#bottom-container').hide();
	$('div#sub-cat3').hide();
	$('div#sub-cat3').html("");
    $('#subcat_button').show();

	$.post("<?php echo $this->baseUrl()?>/admin/categories/get-list-sub-cat3", {parent_id: parent_id, size: 1},
	//this is response from controller
	function(data){
		if(data == "true"){
		$('#next-button').show();
		}else{
		$('div#sub-cat3').html(data);
		$('div#sub-cat3').fadeIn("slow");
               $('#next-button').hide();
		}
                 getCategoryInfo(parent_id);
                
		});
}
//not acctually for geting sub category but just for showing finished messaged
function getSubCat4(){
	$('#sub-cat1-container').hide();
       $('#subcat_button').hide();
         $('#sub-cat1-container').hide();
       var parent_id = $('select#sub-cat3').val();
getCategoryInfo(parent_id);
    
}



function hideThreeBoxes(){
	$('div#sub-cat1').hide();
	$('div#sub-cat2').hide();
	$('div#sub-cat3').hide();
	$('div#sub-cat1').html("");
	$('div#sub-cat2').html("");
	$('div#sub-cat3').html("");
}

function hideTwoBoxes(){
	$('div#sub-cat2').hide();
	$('div#sub-cat3').hide();
	$('div#sub-cat2').html("");
	$('div#sub-cat3').html("");

}

 </script>