<style>

@media only screen and (min-width : 768px) and (max-width : 890px) {

.table {
    table-layout: fixed; 
}

.table td {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
}
</style>        
    <div class="row">
               <div class="col-lg-12">
                
                    <div class="row" style="height:50px;"><!-- row 1-->
                         <div class="col-xs-5">
                         	<ul class="menu-links">
                            <li> <a href="<?php echo $this->baseUrl(); ?>/admin/categories/list-main-cat"> <i class="fa fa-list"> List</i></a></li>
                            <li> <a href="<?php echo $this->baseUrl(); ?>/admin/categories/listing-main"> <i class="fa fa-plus"> New Main Cat</i></a></li>
                            <li> <a href="<?php echo $this->baseUrl(); ?>/admin/categories/listing-sub"> <i class="fa fa-plus"> New Sub Cat</i></a></li>
                            </ul>
                         </div>
                    </div>
                 
                </div>
            </div>                 
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-1">
                                    <i class="fa fa-globe fa-5x"></i>
                                </div>
                                <div class="col-xs-6">
                                <form action="<?php echo $this->baseUrl(); ?>/admin/categories/list-main-cat" action="post">
                                <div class="input-group custom-search-form col-xs-6 text-right" style="padding-top:20px">
                                <input type="text" name="query_string" id="query_string" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            </form>
                                </div>
                                <div class="col-xs-5 text-right">
                                    <div class="huge">Categories List
                        </div>
                                </div>
                            </div>
                        </div>
                         <div class="panel-body">
                         
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                       
					                               <div class="table-responsive">
													<table cellpadding="0" cellspacing="0" border="0" class="dynamicTable display table table-bordered" width="100%">
														<thead>
											
														  	<tr id='msg'><td colspan='7'><?php echo $this->msg ?></td></tr>
															<tr>
																                                                            	<th>Category Name </th>
                                                                <th>Image</th>
                                                                <th>Code</th>
                                                                <th>Is Main</th>
															    <th>Is Frd</th>
																<th>Manage</th>
																<th>Delete</th>
																
                                                             	</tr>
														</thead>		
														<tbody>
                                          	<?php if (count($this->paginator)){ ?>
													
														<?php foreach ($this->paginator as $item): ?>
														<tr class="odd gradeX">
														<?php /*?>	<td>
															<?php if($item['status'] == 1){	 ?>
														<i class="fa fa-camera-retro fa-lg"></i>
                                                        	<?php }else{ ?>
														<i class="fa fa-camera-retro fa-lg"></i>
                                                        	<?php }?>
													    
                                                        
                                                        	</td><?php */?>
                                                        	<td>
																
                                                      	<?php echo $item['category_name'] ?>
															</td>
                                                            
															
                                                            <td>
<img src="<?php echo $this->baseUrl(); ?>/images/categories/100X100/<?php echo $item['category_image'] ?>" alt="Cateogry Image" />
															</td>
                                                             <td>
                                                            <?php echo $item['code'] ?>
															</td>
                                                             <td>
                                                            <?php echo $item['is_main'] ?>
															</td>
                                                             <td>
                                                            <?php echo $item['is_featured'] ?>
															</td>
                                          
                                          <td><a class="btn btn-sm btn-warning float-right" href="<?php echo $this->baseUrl(); ?>/admin/categories/edit-cat/id/<?php echo $item['category_id'] ?>"> Manage</a></td>
										  <td><a class="btn btn-sm btn-danger float-right"  href="<?php echo $this->baseUrl(); ?>/admin/categories/remove-cat/id/<?php echo $item['category_id'] ?>"> Delete</a></td>
															
                                                       												</tr>
                                                            	<?php endforeach; ?>
															<tr><td colspan='7'>
															<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>
															</td>
															</tr><?php }else{ ?>
											
															<tr><td colspan="7"><h4>No Categories found!</h4></td></tr>
															<?php } ?>
														</tbody>

														</table>
                            </div>  <!--responsive table div end-->
                     
                    </div>
               </div>
                <!-- /.col-lg-12 -->
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        
  <script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }
 </script>