        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
            <div class="col-lg-12">
			<div class="col-lg-11">
            <div class="row" style="height:50px; padding:0; margin:0">
                 <div class="col-xs-5">
                 	<table class="table">
         
                    </table>
                 </div>
                 </div>
                    
                    <div class="panel panel-danger">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-1">
                                  <?php if($this->category_id != 0){ ?>
                                    <i class="fa fa-close fa-5x"></i>
                                     <?php }else{ ?>
                                    <i class="fa fa-check fa-5x"></i>
                                      <?php }?>
                                </div>
                                <div class="col-xs-11 text-right">
                                    <div class="huge">
                                  <?php if($this->category_id != 0){ ?>
                                    Click Delete to Remove Category</div>
                                     <?php }else{ ?>
                                   Listing is removed from Category List</div>
                                      <?php }?>
                                </div>
                            </div>
                        </div> 
                            <div class="panel-body">

                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                
                                  <div id="basic_info">
            
                                   <form name="" id="" method="post" action="">  
                                       
									   <div class="table-responsive">
									   <table class="table table-striped table-bordered">
                                    	<tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
										<tr>
						<tr><td colspan="2"><Strong><a href="#">Category Information</a></Strong></td></tr>
									
						<tr><td><Strong><label>* Name</label></Strong></td><td>
						<?php echo $this->category_name ?></td></tr>
						<tr><td><Strong><label>* Category Image</label></Strong></td><td>
					<img src="<?php echo $this->baseUrl(); ?>/images/categories/100X100/<?php echo $this->category_image ?>" alt="Category Image" /></td></tr>

						<input type="hidden" name="id" value="<?php echo $this->category_id?>">
											
		 	                        	<?php if($this->category_id != 0){ ?>
                                        <tr><td><a href="<?php echo $this->baseUrl(); ?>/admin/categories/list-main-cat/" class="btn btn-md btn-primary">Cancel</a></td><td>
                                        <button class="btn btn-md btn-danger" type="submit"> Confirm Delete </button>
                                        </td></tr>   
                                        <?php }else{ ?>
                                        <tr><td colspan="2"><a href="<?php echo $this->baseUrl(); ?>/admin/categories/list-main-cat/" class="btn btn-md btn-warning">Back to Category List</a></td></tr>   
  
                                        <?php }?>
                                        </table>
										</div>
										
                                   </form>
	                            </div>
                            </div>
                      
                    </div>
                       <a href="#">
                         <div class="panel-footer">
                         </div>
                        </a>
                </div>
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

	<script language="Javascript" type="text/javascript">
	window.onload = function () { 
	 <?php if(!isset($this->msg)){ ?>
				$('tr#msg').hide();
				
			<?php  } else{
			?>
				$('tr#msg').show();
			<?php } ?>
	 }
	 </script>