<div class="row">
    <div class="col-md-12">
	<ul class="menu-links">
	<li><a href="<?php echo $this->baseUrl(); ?>/admin/page/new-page" title="Create new page"> New Page</a></li>       
    <li><a href="<?php echo $this->baseUrl(); ?>/admin/page/index" title="View page list">Page List</a></li>       
    <li><a href="<?php echo $this->baseUrl(); ?>/admin/page/member-pages" title="View member page list">Member Page List</a></li>
	</ul>
	</div>
</div>
								
<div class="row">
	<div class="col-md-12">
		<div id="msg">
			<?php echo $this->msg ?>
		</div>
		<div class="clearfix">
		</div>
        
		<div class="table-responsive">
			<table class="table table-striped table-bordered table-hover" id="dataTables-example">
														<thead>
														<tr>
																<th class="grid-head"> Page Title</th>
																<th class="grid-head">Name </th>
																<th class="grid-head">Email </th>
																<th class="grid-head">Comment </th>
																<th class="grid-head">Date </th>
																<th class="grid-head">Status </th>
																<th class="grid-head">Action</th>
																<th class="grid-head">View</th>
																<th class="grid-head">Delete</th>
                                                        	</tr>
														</thead>		
														<tbody> 
                                          
														<?php if (count($this->data)){ 
														  foreach ($this->data as $item): ?>
														<tr class="odd gradeX">
															<td> <?php echo $item['title'] ?> </td> 
															<td style="text-align:center;"> <?php echo $item['name'] ?> </td> 
															<td style="text-align:center;"> <?php echo $item['email'] ?> </td> 
															<td>
                                                                <?php if(strlen($item['comment'])>100) 
                                                                        echo substr($item['comment'], 0, strpos($item['comment'], ' ', 110)) .'<strong>...</strong>'; 
                                                                    else echo $item['comment'];
                                                                ?>
                                                            </td> 
															<td style="text-align:center;"> <?php echo date('m/d/Y h:i A', strtotime($item['comment_date'])) ?> </td> 
															<td style="text-align:center;">
															<?php if($item['status']== 1){?>
															Pending<?php }elseif($item['status']== 3){ ?>
															Rejected<?php }else{ ?>
															Approved<?php } ?>
															</td>
															<td style="text-align:center;">
    															<?php if($item['status']== 1 || $item['status']== 3){?>
    															<a class="btn btn-sm btn-success" href="#" onclick="return confirmApprove(<?php echo $item['comment_id'] ?> )" >Approve</a>
                                                                <?php } else { ?>
    															<a class="btn btn-sm btn-danger" href="#" onclick="return confirmReject(<?php echo $item['comment_id'] ?> )" >Reject</a> 
                                                                <?php } ?> 
                                                            </td>
                                                            <td style="text-align:center;"><a class="btn btn-sm btn-warning" href="<?php echo $this->baseUrl(); ?>/admin/comments/edit/id/<?php echo $item['comment_id'] ?>/p/<?php echo $item['title'] ?>/p_id/<?php echo $this->page_id;?>">View</a></td>
                                                            <td style="text-align:center;"><a class="btn btn-sm btn-danger" href="#" onclick="return confirmDelete(<?php echo $item['comment_id'] ?> )" >Delete</a></td>
														</tr>  
															<?php endforeach; } ?>
														</tbody>

						 								</table>
														</div><!-- div responsive end-->
												</div>

                                </div>

  <script type="text/javascript">
 window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('#msg').hide();
			
		<?php  } else{
		?>
			$('#msg').show().delay(3000).hide('slow');
		<?php } ?>
        
        $('#dataTables-example').dataTable(
           {
		      "aaSorting": [[ 4, "desc" ]] // 4th index or 5th column in descending order
	       }
        );
 }
 
 function confirmDelete(id){
	var r = confirm("Are you sure to Delete this Comment! " );
	if (r == true) {
	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/comments/delete/id/" + id);    
	} else {
	return false;
	}
	}
	
  function confirmApprove(id){
	var r = confirm("Are you sure to Approve this Comment! " );
	if (r == true) {
	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/comments/approve/id/" + id);    
	} else {
	return false;
	}
	}
	
  function confirmReject(id){
	var r = confirm("Are you sure to Reject this Comment! " );
	if (r == true) {
	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/comments/reject/id/" + id);    
	} else {
	return false;
	}
	}

 </script>