<div class="row">
    <div class="col-md-12">
	<ul class="menu-links">
	<li><a href="<?php echo $this->baseUrl(); ?>/admin/gallery/new-photo" title="Add new photo"> Add Photo</a></li>            
	<li><a href="<?php echo $this->baseUrl(); ?>/admin/photo-categories/new" title="Add new category"> Add New Category</a></li>       
	<li><a href="<?php echo $this->baseUrl(); ?>/admin/photo-categories" title="View category list">Category List</a></li>       
	</ul>
	</div>
</div>   
<!--div class="row">
 <div class="col-md-12">
  <div class="page-title">Photo Gallery List</div>
 </div>
</div><!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">
			<form method="post" name="data_table">
			<table class="table table-striped table-bordered table-hover" id="dataTables-example">
							<thead>
						     <tr>
							  <th class="grid-head">Image</th>
							  <th class="grid-head">Caption</th>
                              <th class="grid-head">Category</th>
							  <th class="grid-head">Description</th>
							  <th class="grid-head">Link</th>										
							  <th class="grid-head">Edit </th>
							  <th class="grid-head">Delete </th>
							  <th class="grid-head">
                              <input type="submit" name="submit" class="btn btn-danger btn-sm" id="submit" value="Delete"/>
                              <label><input type="checkbox" name="allbox" id="allbox" value="0" onclick="checkAll(this.value);" /> All</label>
                              </th>
							 </tr>
							</thead>		
							<tbody>
                              <?php if (count($this->data)){ ?>
								<?php $counter =0; foreach ($this->data as $item): ?>
									<tr class="odd gradeX">
									 <td style="text-align:center; vertical-align: middle;">
									  
                                      <?php if (isset($item['photo_name'])) { ?>
										<a  href="<?php echo $this->baseUrl(); ?>/admin/gallery/edit-photo/id/<?php echo $item['photo_id'] ?>">
                                        <img width="60" src="<?php echo $this->baseUrl(); ?>/images/photo_gallery/200X200/<?php echo $item['photo_name'] ?>" alt="photo-gallery" /></a>
									  <?php } else { ?>
                                        <a  href="<?php echo $this->baseUrl(); ?>/admin/gallery/edit-photo/id/<?php echo $item['photo_id'] ?>">
                                        <img width="60" src="<?php echo $this->baseUrl();?>/images/admin/placeholder200X200.png" alt="photo-gallery" /></a>
                                      <?php } ?>
									  </td>
									  <td style="text-align:center;vertical-align: middle;">
									   <?php echo $item['caption'] ?>
									  </td>  
                                      
                                      <td style="text-align:center;vertical-align: middle;">
                                        <?php echo $item['category_name'] ?>
                                      </td>
                                      
									  <td style="vertical-align: middle;">
									   <?php echo strip_tags($item['description']) ?>
									  </td>  
									  <td style="text-align:center;vertical-align: middle;">
									   <?php echo $item['link'] ?>
									  </td>                                                              
	                                  <td style="text-align:center;vertical-align: middle;"><a class="btn btn-sm btn-warning" href="<?php echo $this->baseUrl(); ?>/admin/gallery/edit-photo/id/<?php echo $item['photo_id'] ?>">Edit</a></td>
									  <td  style="text-align:center;vertical-align: middle;"><a class="btn btn-sm btn-danger" href="#" onclick="return confirmDelete(<?php echo $item['photo_id'] ?> )" href="">Delete </a></td>
									  <td  style="text-align:center;vertical-align: middle;"><input type="checkbox" name="bulkdata[]" id="check_<?php echo $counter++;?>" class="form-control" value="<?php echo $item['photo_id'] ?>"></td>
									</tr>
								<?php endforeach;  } ?>
                             </tbody>

						   </table>
						</div><!-- div responsive end-->
												    
                </div>
                 <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->

<script type="text/javascript">
    $(function () {
        
        $('#dataTables-example').dataTable(
            {
		      "aaSorting": [[ 2, "asc" ]], 
              "iDisplayLength": 50,
              "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
              "aoColumnDefs": [{'bSortable': false, 'aTargets': [5,6,7]}]
	       }
        );
    }); 

  function confirmDelete(id){
	var r = confirm("Are you sure to Delete this Photo! " );
	if (r == true) {
	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/gallery/delete-photo/id/" + id);    
	} else {
	return false;
	}
	}
    
    function checkAll(a)
	{
	    var total = $('#dataTables-example tr:not(:has(th))').length;
        
		if(a == 0)
		{
			for(q=0;q<total;q++)
			{
                $('#check_'+q).prop('checked', true);
			}
            $('#allbox').val(1);
		}

		if(a == 1)
		{
			for(q=0;q<total;q++)
			{
                $('#check_'+q).prop('checked', false);
			}

            $('#allbox').val(0);
		}
	}	
	
	jQuery(function($) {
	
	$("form input[id='submit']").click(function() {  // triggred submit
		
		var count_checked = $("[name='bulkdata[]']:checked").length; // count the checked
		if(count_checked == 0) {
			alert("Please select a Photos to delete.");
			return false;
		} 
		 else {
			return confirm("Are you sure you want to delete these Photos?");	
		  }		
	});
}); // jquery end

</script>