<style>
.top-bar{
	padding-top: 10px;
	margin-bottom: 28px;
}
.head-logo{
	padding-top: 20px !important;
}
.nav>li>a {
    position: relative;
    display: block;
    padding: 10px 15px !important;
} 
</style>
<header id="header">
        <nav id="main-menu" class="navbar navbar-default navbar-fixed-top" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand head-logo" href="<?php echo $this->baseUrl();?>/">
                        <!--img src="<?php echo $this->baseUrl();?>/images/user/image-blocks/<?php //echo $this->image_block[10]['block']; ?>" style="width: 250px; height: 60px;" alt="logo"/-->
                    <img src="<?php echo $this->baseUrl();?>/images/logo-new.png" class="img-responsive" alt="logo"/ style="margin-top: -14px; width: 90%;">
				         </a>
                </div>
				<?php //if($this->user_role == 1): ?>
                <!--div style="display: inline-block; padding-top: 70px;">
                    <a class="editor_link" href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/11" target="_blank">Edit Logo</a>
                </div-->
				<?php //endif ?>
                <div class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
					<li class="scroll active"><a href="<?php echo $this->baseUrl(); ?>/">Home</a></li>
					<li class="scroll"><a href="#">Business Pages</a></li>
					<li class="scroll"><a href="#">Daily Deals</a></li>
					<?php if(isset($this->user_role)) {?>
                    <li class="scroll"><a href="<?php echo $this->baseUrl(); ?>/members/index"> <i class="fa fa-user fa-home"></i> Dashboard</a></li>
					<?php } else {?>
                    <li class="scroll"><a href="<?php echo $this->baseUrl(); ?>/index/login">Login</a></li>
                    <?php } ?>
                    <li class="scroll"><a href="<?php echo $this->baseUrl(); ?>/index/about">About Us</a></li>
				
                    </ul>
                </div>
            </div><!--/.container-->
        </nav><!--/nav-->
    </header><!--/header-->