<div id="myCarousel" class="carousel slide" data-ride="carousel" style="margin-bottom: 5px"> 
  <!-- Indicators -->
  
  <!-- ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol -->
  <div class="carousel-inner">
    <div class="item active"> <img src="<?php echo $this->baseUrl(); ?>/slider/jssor/img/home/01.jpg" style="width:100%" alt="First slide">
      <div class="container">
       
		<!-- div class="carousel-caption">
          <h1>Slide 1</h1>
          <p>Aenean a rutrum nulla. Vestibulum a arcu at nisi tristique pretium.</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
        </div -->
      </div>
    </div>

    <div class="item"> <img src="<?php echo $this->baseUrl(); ?>/slider/jssor/img/home/02.jpg" style="width:100%" data-src="" alt="Second    slide">
      <div class="container">
      </div>
    </div>
 	<!--   <div class="item"> <img src="<?php echo $this->baseUrl(); ?>/slider/jssor/img/home/03.jpg" style="width:100%" data-src="" alt="Third slide">
      <div class="container">
      </div>
    </div>
  -->
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a> </div>
  