<style>
		/* custom class for form to control it*/
		.space-top{
		padding-top: 40px;
		}
		</style>       

	   <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                         <div class="col-lg-9 col-md-16">
                          <div class="row" style="height:50px; padding:0; margin:0">
                 <div class="col-xs-3">
                 	<table class="table">
                    <tr><td> <a href="<?php echo $this->baseUrl(); ?>/admin/cities/list"> <i class="fa fa-list  alert-primary"></i> List</a></td>
                    <td>  <a href="<?php echo $this->baseUrl(); ?>/admin/cities/new"> <i class="fa fa-plus alert-primary"></i> New</a></td>
                    </tr>
                    </table>
                 </div>
                   </div>      
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-globe fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Edit City</div>
                             
                                </div>
                            </div>
                        </div>
                        <div class="panel-body">
						
						
                                <span class="pull-left">Enter Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                  
                                    <form class="form-horizontal space-top" action="<?php echo $this->baseUrl(); ?>/admin/cities/edit/city_id/<?php echo $this->city_id;?>" method="POST" >
                                       	<table class="table table-striped table-bordered table-hover">
                                    	<tr><td colspan='2'><?php echo $this->msg ?></td></tr>
										
						<tr><td><Strong><label>* Country</label></Strong></td><td><?php echo $this->country_name;?></td></tr>
						<tr><td><Strong><label>* State</label></Strong></td><td><?php echo $this->state_name;?></td></tr>
						<tr><td><Strong><label>* City</label></Strong></td><td><?php echo $this->cities;?></td></tr>
						
						<tr><td colspan="2"><Strong><a href="#">Edit City</a></Strong></td></tr>
										<?php echo $this->form->country?>
										
										<tr>
												<td><strong id="set-state-val">Select State
                                                 </strong>
                                                </td>
                                                <td>
                                              
										  <select id="state" name="state_id" class="form-control">
                                             <option value="0">Select State</option>
                                         </select></td>
                                        </tr>
											
											<!-- <tr id="city_sel">
												<td><strong>* Select City
                                                 </strong>
                                                </td>
                                                <td>
											   <div id='city'></div></tr> -->
											   
											   
											 <?php echo $this->form->city_name?>
										<input type="hidden" name="state_id" value="<?php echo $this->city_id;?>">
                                        <tr><td>&nbsp;</td><td>
                                         <input type="submit" value="Save" class="btn btn-lg btn-primary float-right">
										
										</td></tr>
										</table>  
									</form>
	                               
                                </div>
                            </div>
                             <a href="#">
                            <div class="panel-footer">
                            </div>
                        </a>
                    </div>
                </div>
                
                
          
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

 

  <script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide(); 
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }
 
 			function getState(){
			var country_id = $('#country_id').val();//select item value from listbox
					$('#country_id').val(country_id);
			 if(country_id == "")return;
						$.post("<?php echo $this->baseUrl()?>/admin/countries/get-state", {country_id: country_id},
						//this is response from controller
						function(data){
							
							$('#state').html(data);
                            
                            if($('#state option').size()>1){
                                $('#set-state-val').text('* Select State');
                            } else {
                                $('#set-state-val').text('Select State');
                            }
						});
			}
			

 </script>