        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                         <div class="col-lg-12 col-md-26">
                                      <div class="row" style="height:50px; padding:0; margin:0"><!-- row 1-->
                 <div class="col-xs-3">
                               
					<table class="table">
                    <td><a href="<?php echo $this->baseUrl(); ?>/admin/cities/new"> <i class="fa fa-plus alert-primary"></i> Add New City</a></td>
                    </tr>
                    </table>	
					
                 </div>
                 </div><!-- ./ row 1-->
				
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-1">
                                    <i class="fa fa-cube fa-5x"></i>
                                </div>
                                <div class="col-xs-6">
                                      <form action="<?php echo $this->baseUrl()?>/admin/cities/list" action="post">
                                <div class="input-group custom-search-form col-xs-6 text-right" style="padding-top:20px">
                                <input type="text" name="query_string" id="query_string" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            </form>
                                </div>
                                <div class="col-xs-5 text-right">
                                    <div class="huge">Cities List
                        </div>
                                </div>
                            </div>
                        </div>
                     <div class="panel-body">
                        
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                       	<table cellpadding="0" cellspacing="0" border="0" class="responsive dynamicTable display table table-bordered" width="100%">
				            <tbody>
															<tr><td>
                               <?php echo $this->countries; ?>
                               </td>
                               <td>
			                     <?php echo $this->states;	?>
                                <select id="state" name="state_id" class="form-control">
                                     <option value="0">Select State</option>
                                 </select>				
				                </td>	
                            </tr>
                            </tbody></table>
                               <table id="list" cellpadding="0" cellspacing="0" border="0" class="responsive dynamicTable display table table-bordered" width="100%">
														<thead>
															<tr>
																<th>City Name</th>
																<th>Edit</th>
																<th>Block</th>
															 	</tr>
														</thead>		
														<tbody>
                                          
														<?php if (count($this->paginator)){ ?>
													
														<?php foreach ($this->paginator as $item): ?>
														<tr class="odd gradeX">
															<td>
															<?php echo $item['city_name'] ?>
															</td>
                                                        
                                                            	<td><a class="btn btn-sm btn-warning float-right" href="<?php echo $this->baseUrl(); ?>/admin/cities/edit/city_id/<?php echo $item['city_id'] ?>">Edit</a></td>
															<td><a class="btn btn-sm btn-info float-right" href="<?php echo $this->baseUrl(); ?>/admin/cities/confirm-block/city_id/<?php echo $item['city_id'] ?>">Block</a></td>
														</tr>
															<?php endforeach; ?>
															<tr><td colspan='9'>
															<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>
															</td>
															</tr><?php }else{ ?>
											
											
															<tr><td colspan="7"><h4>There are no cities created! Please create one</h4></td></tr>
															<?php } ?>
														</tbody>

														</table>
                               	<div id='result'>

								</div>
				              
												</div>
                            </div>
                          
                        
                        <a href="#">
                        
                            <div class="panel-footer">
                             
                               </div>
                        </a>
                     </div>
                  
                    </div>
                </div>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    
  <script type="text/javascript">
  window.onload = function () { 
			
 }

 function getAllCities(){
 $.post("<?php echo $this->baseUrl()?>/admin/countries/get-all-cities", 
						//this is response from controller
						function(data){
						$('#list').hide();
							$('#result').html(data);
							$('#result').show();
							
						});
 }
 
  function getState(){
			var country_id = $('#country').val();//select item value from listbox
			
             if(country_id == ""){
				 
				 getAllCities();
				 return;
		      }
			
            $.post("<?php echo $this->baseUrl()?>/admin/countries/get-state", {country_id: country_id},
						//this is response from controller
						function(data){
							$('#state').html(data);
							
						});
						
						$.post("<?php echo $this->baseUrl()?>/admin/countries/get-countries-cities", {country_id: country_id},
						//this is response from controller
						function(data){
						$('#list').hide();
						// $('#result').empty();
							$('#result').html(data);
							$('#result').show();
						});
			}
			
			
			
			function getCities(){
			
			var country_id = $('#country').val();//select item value from listbox
			var state_id = $('#state').val();//select item value from listbox
				
					$('#state_id').val(state_id);
					if(state_id == "")return;
					$.post("<?php echo $this->baseUrl()?>/admin/countries/get-state-cities", {country_id: country_id,state_id: state_id},
						//this is response from controller
						function(data){
						$('#list').hide();
						$('#result').empty();
						$('#result').html(data);
						$('#result').show();
						
							
						});
						
			}
	</script>