  <div id="content" class="clearfix">
            <div class="contentwrapper"><!--Content wrapper-->

               	<div class="row-fluid">

                        <div class="span6">

                            <div class="box">

									<h3>Cities Saved</h3> 
										<?php echo $this->msg; ?>
							</div><!-- End .box -->

                        </div><!-- End .span6 -->
						

					</div><!-- End .row-fluid -->
					
			</div><!-- End contentwrapper -->
  </div><!-- End #content -->
    
    