<style>
#title{
	font-size: 24px;	
}
.labels{
color: #444444;	
}
.btn-xs {
    padding: 1px 5px!important;
}
#page-wrapper {
    padding-bottom: 30px;
    padding-top: 10px;
}
.li_btn{
		border-radius:0;
		background:#1B1C52;
		border:1px solid #1B1C52;
		margin-top: 5px;   
	}
	.li_btn > a{
		color:white;
	}
	.nav>li>a:focus, .nav>li>a:hover {
    text-decoration: none;
    color:white;
		background:#1B1C52;
}
.banner.form-group, .video.form-group{
	display:none;
}
.edit-banner.form-group, .edit-video.form-group{
	display:none;
	    margin: 10px auto;
}
.nopadding {
   padding: 0 !important;
   margin: 0 !important;
}
.grid {
	position: relative;
	margin: 0 auto;
	padding: 1em 0 4em;
	max-width: 1000px;
	list-style: none;
	text-align: center;
}

/* Common style */
.grid figure {
	position: relative;
	float: left;
	overflow: hidden;
	margin: 10px 1%;
	// min-width: 320px;
	// max-width: 480px;
	// max-height: 360px;
	// width: 48%;
	background: #3085a3;
	text-align: center;
	cursor: pointer;
}

.grid figure img {
	position: relative;
	display: block;
	min-height: 100%;
	max-width: 100%;
	opacity: 0.8;
}

.grid figure figcaption {
	padding: 2em;
	color: #fff;
	text-transform: uppercase;
	font-size: 1.25em;
	-webkit-backface-visibility: hidden;
	backface-visibility: hidden;
}

.grid figure figcaption::before,
.grid figure figcaption::after {
	pointer-events: none;
}

.grid figure figcaption,
.grid figure figcaption > a {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
}

/* Anchor will cover the whole item by default */
/* For some effects it will show as a button */
.grid figure figcaption > a {
	z-index: 1000;
	text-indent: 200%;
	white-space: nowrap;
	font-size: 0;
	opacity: 1;
}

.grid figure h2 {
	word-spacing: -0.15em;
	font-weight: 300;
}

.grid figure h2 span {
	font-weight: 800;
}

.grid figure h2,
.grid figure p {
	margin: 0;
}

.grid figure p {
	letter-spacing: 1px;
	font-size: 68.5%;
}

/* Individual effects */


/*---------------*/
/***** Bubba *****/
/*---------------*/

figure.effect-bubba {
	background: #607D8B;
}
figure.effect-bubba iframe{
	max-width: 100%;
    height: 350px;
}

figure.effect-bubba iframe, figure.effect-bubba img {
	opacity: 0.1;
	-webkit-transition: opacity 0.35s;
	transition: opacity 0.35s;
}
#edit_box{
	display:none;
}
figure.effect-bubba:hover iframe, figure.effect-bubba img {
	opacity: 0.1;
}

figure.effect-bubba figcaption::before,
figure.effect-bubba figcaption::after {
	position: absolute;
	top: 30px;
	right: 30px;
	bottom: 30px;
	left: 30px;
	content: '';
	opacity: 0;
	-webkit-transition: opacity 0.35s, -webkit-transform 0.35s;
	transition: opacity 0.35s, transform 0.35s;
}

figure.effect-bubba figcaption::before {
	border-top: 1px solid #fff;
	border-bottom: 1px solid #fff;
	-webkit-transform: scale(0,1);
	transform: scale(0,1);
}

figure.effect-bubba figcaption::after {
	border-right: 1px solid #fff;
	border-left: 1px solid #fff;
	-webkit-transform: scale(1,0);
	transform: scale(1,0);
}

figure.effect-bubba h2 {
	padding-top: 30%;
	-webkit-transition: -webkit-transform 0.35s;
	transition: transform 0.35s;
	-webkit-transform: translate3d(0,-20px,0);
	transform: translate3d(0,-20px,0);
}

figure.effect-bubba p {
	padding: 20px 2.5em;
	opacity: 1;
	-webkit-transition: opacity 0.35s, -webkit-transform 0.35s;
	transition: opacity 0.35s, transform 0.35s;
	-webkit-transform: translate3d(0,20px,0);
	transform: translate3d(0,20px,0);
}

figure.effect-bubba:hover figcaption::before,
figure.effect-bubba:hover figcaption::after {
	opacity: 1;
	-webkit-transform: scale(1);
	transform: scale(1);
}
figure.effect-bubba button {
	-webkit-transition: opacity 0.35s, -webkit-transform 0.35s;
	transition: all 0.35s, transform 0.35s;
	-webkit-transform: translate3d(0,20px,0);
	transform: translate3d(0,20px,0);
	opacity:1;
	border:1px solid white;
	color:white;
	background:transparent;
	border-radius:0;
}
figure.effect-bubba button:hover {
	background:white;
	color:black;
}
figure.effect-bubba:hover h2,
figure.effect-bubba:hover p,
figure.effect-bubba:hover button {
	opacity: 1;
	-webkit-transform: translate3d(0,0,0);
	transform: translate3d(0,0,0);
}


@media screen and (max-width: 50em) {
	.content {
		padding: 0 10px;
		text-align: center;
	}
	.grid figure {
		display: inline-block;
		float: none;
		margin: 10px auto;
		width: 100%;
	}
}
</style>
<div id="page-wrapper" style="padding-top: 20px;">
<div class="row row-fluid">
    <div class="col-md-12">
    <?php //echo $this->render('/members/menu.phtml'); ?>
    
        <ul class="nav nav-pills">
          <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/manage-page/id/<?php echo $this->page_id ?>">Main Page</a></li>
		  <!--li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/upload-slider/id/<?php echo $this->page_id ?>">Upload Slider</a></li-->
          <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/new-product-post/id/<?php echo $this->page_id ?>">New Product Post</a></li>
		  <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/new-service-post/id/<?php echo $this->page_id ?>">New Service Post</a></li>
		  <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/new-social-post/id/<?php echo $this->page_id ?>">New Social Post</a></li>
		  <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/product-post/id/<?php echo $this->page_id ?>">Product Posts</a></li>
		  <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/service-posts/id/<?php echo $this->page_id ?>">Service Posts</a></li>
		  <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/social-posts/id/<?php echo $this->page_id ?>">Social Posts</a></li>
          <li class="li_btn" role="presentation"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/upload-brochure/id/<?php echo $this->page_id ?>">Upload Brochure</a></li>
		  <li class="li_btn" role="presentation"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/comments/id/<?php echo $this->page_id ?>">Comments</a></li>
		  <li class="li_btn" role="presentation"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/feedback/id/<?php echo $this->page_id ?>">Get Feedback</a></li>
		  <li class="li_btn" role="presentation"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/popup-design/id/<?php echo $this->page_id ?>">Customize CTA</a></li>
         <!--li class="li_btn" role="presentation"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/hide-ads/id/<?php echo $this->page_id ?>">Hide Page Ads/Description</a></li-->
		 
          <!--li role="presentation"><a href="<?php echo $this->baseUrl(); ?>/members/ad-image/id/<?php echo $this->page_id ?>">Advertisement Image block</a></li>
          <li role="presentation"><a href="<?php echo $this->baseUrl(); ?>/members/rbar-ads/id/<?php echo $this->page_id ?>">Right Bar Advertisments</a></li-->
        </ul>
    </div>
</div>
<?php
	if(isset($this->msg)){ ?>
		<div class="alert alert-success"><?php echo $this->msg ?></div>
	<?php }elseif(isset($this->err)){ ?>
		<div class="alert alert-danger"><?php echo $this->err ?></div>
	<?php }
?>
	
	<?php
		if(isset($this->feedback)){ ?>
		<div class="col-md-8 col-md-offset-2">
			<div class="content">
			
				<div class="grid">
					<figure class="effect-bubba">
					<?php 
						if($this->feedback['f_type'] == 1){ ?>
							<img src="<?php echo $this->baseUrl(); ?>/images/uploads/<?php echo $this->member_dir. '/' .$this->feedback['banner'];?>" alt="img02"/>
						<?php }else{ ?>
							<iframe width="692" height="350" src="<?php echo $this->feedback['video'] ?>" frameborder="0" allowfullscreen></iframe>
						<?php }
					?>
						<figcaption>
							<h3><?php echo $this->result['title']; ?>'s Feedback</h3>
							<p>Total Feedbacks: <span style="font-weight: bold; font-size: 20px;"><?php echo count($this->comments) ?></span></p>
							
							<button class="btn btn-info" id="show_comment">View Feedback</button>
							<button class="btn btn-info" id="show_edit">Edit Feedback</button>
						</figcaption>			
					</figure>
				</div>
			
				
			</div>
		</div>
		<div class="row" style="margin-top:30px;" id="comment_box">
		
		
		<div class="col-md-12">
			<h3><?php echo $this->result['title']; ?>'s Feedback</h3>
        
		<div class="table-responsive">
        <form method="post" name="data_table">
			<table class="table table-striped table-bordered table-hover" id="dataTables-example">
														<thead>
														<tr>
																<th class="grid-head"> Page Title</th>
																<th class="grid-head">Name </th>
																<th class="grid-head">Email </th>
																<th class="grid-head">Comment </th>
																<th class="grid-head">Date </th>
                                                        	</tr>
														</thead>		
														<tbody> 
                                          
														<?php if (count($this->comments)){ 
														 $counter=0; foreach ($this->comments as $item): ?>
														<tr class="odd gradeX">
															<td> <?php echo $this->result['title'] ?> </td> 
															<td style="text-align:center;"> <?php echo $item['Name'] ?> </td> 
															<td style="text-align:center;"> <?php echo $item['email'] ?> </td> 
															<td>
                                                                <?php if(strlen($item['comment'])>100) 
                                                                        echo substr($item['comment'], 0, strpos($item['comment'], ' ', 110)) .'<strong>...</strong>'; 
                                                                    else echo $item['comment'];
                                                                ?>
                                                            </td> 
															<td style="text-align:center;"> <?php echo date('m/d/Y h:i A', strtotime($item['comment_date'])) ?> </td> 
															
                                                        </tr>  
															<?php endforeach; } ?>
														</tbody>

						 								</table>
                                                        </form>
														</div><!-- div responsive end-->
												</div>
		</div>
		<div class="row" id="edit_box">
			<div class="col-md-8 col-md-offset-2">
			<h3>Edit Feedback Type</h3>
				<form method="POST" action="<?php echo $this->baseUrl()?>/mem-pages/update-feedback" enctype="multipart/form-data">
					<div class="form-group">
					  <label for="f_type">Select Feedback Type:</label>
					  <select class="form-control" id="edit_f_type" name="f_type" required>
						
						<option value="1" <?php if($this->feedback['f_type'] == 1) echo 'selected="selected"' ?>>Banner</option>
						<option value="2"  <?php if($this->feedback['f_type'] == 2) echo 'selected="selected"' ?>>Video</option>
					  </select>
					  <input type="hidden" name="feed_id" value="<?php echo $this->feedback['feed_id']; ?>">
					  <input type="hidden" name="page_id" value="<?php echo $this->page_id; ?>">
					</div>
					<div class="edit-banner form-group" style="display:block;">
					<div class="col-md-12 nopadding">
						<div class="col-md-6 nopadding"  style="padding-right: 15px !important;">
						<label for="email">Image</label>
						<input type="file" class="edit-file form-control" id="banner_image" name="edit_image" required>
					</div>
					<div class="col-md-6 nopadding">
					<?php
						if($this->feedback['banner'] !== ''){ ?>
							<img class="img-responsive" src="<?php echo $this->baseUrl(); ?>/images/uploads/<?php echo $this->member_dir. '/' .$this->feedback['banner'];?>" alt="img02"/>
						<?php }
					?>
						
					</div>
					</div>
					
					</div>
				  <div class="edit-video form-group">
					<label for="pwd">Video</label>
					<input type="text" class="edit-video-text form-control" id="video" name="video" placeholder="Youtube Embed Video URL" required>
					<div class="video-container" style="margin-top:10px;">
					<?php
						if($this->feedback['video'] !== ''){ ?>
						<iframe width="250" height="250" src="<?php echo $this->feedback['video'] ?>" frameborder="0" allowfullscreen></iframe>
					<?php }
					?>	
					</div>
				  </div>
				  <button type="submit" class="btn btn-default" style="margin-top:10px;">Update</button>
				</form>
			</div>
		</div>
		</div>
		<?php
		}else{ ?>
		<h3 style="margin-top:20px;" class="text-center">Feedback</h3>
			<form method="POST" action="" enctype="multipart/form-data">
				<div class="form-group">
				  <label for="f_type">Select Feedback Type:</label>
				  <select class="form-control" id="f_type" name="f_type" required>
					<option value="">Select Feedback Type</option>
					<option value="1">Banner</option>
					<option value="2">Video</option>
				  </select>
				</div>
				<div class="banner form-group">
				<label for="email">Image</label>
				<input type="file" class="file form-control" id="banner_image" name="banner_image" required>
				</div>
			  <div class="video form-group">
				<label for="pwd">Video</label>
				<input type="text" class="video-text form-control" id="video" name="video" placeholder="Youtube Embed Video URL" required>
			  </div>
			  <button type="submit" class="btn btn-default">Save</button>
			</form>
		<?php
		}
	?>
	

</div>
<input type="hidden" value="<?php echo $this->baseUrl(); ?>" id="base_url">
<script>
	$(document).ready(function(){
		$('#comment_box').hide();
		$('#show_comment').click(function(){
			$('#comment_box').fadeToggle(300);
			$('#edit_box').hide();
		});
		$('#show_edit').click(function(){
			$('#edit_box').fadeToggle(300);
			$('#comment_box').hide();
		});
		$('#dataTables-example').dataTable(
           {
		      "aaSorting": [[ 4, "desc" ]], // 4th index or 5th column in descending order
              "iDisplayLength": 50,
              "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
              "aoColumnDefs": [{'bSortable': false, 'aTargets': [2,3,4]}]
	       }
        );
		$('select').on('change', function() {
		 // alert( this.value );
		  if(this.value == 1){
			  $('.banner.form-group').show();
			  $('.video.form-group').hide();
			  $('.video-text.form-control').attr('required',false);
		  }else if(this.value == 2){
			  $('.video.form-group').show();
			  $('.banner.form-group').hide();
			  $('.file.form-control').attr('required',false);
		  }
		});
		if($('#edit_f_type').val() == 1){
			$('.edit-banner.form-group').show();
			  $('.edit-video.form-group').hide();
			  $('.edit-video-text.form-control').attr('required',false);
		}else if($('#edit_f_type').val() == 2){
				$('.edit-video.form-group').show();
			  $('.edit-banner.form-group').hide();
			  $('.edit-file.form-control').attr('required',false);
		}else if($('#edit_f_type').val() == ''){
			$('.edit-banner.form-group').hide();
			$('.edit-video.form-group').hide();
		}
		$('#edit_f_type').on('change', function() {
		 // alert( this.value );
		  if(this.value == 1){
			  $('.edit-banner.form-group').show();
			  $('.edit-video.form-group').hide();
			  $('.edit-video-text.form-control').attr('required',false);
		  }else if(this.value == 2){
			  $('.edit-video.form-group').show();
			  $('.edit-banner.form-group').hide();
			  $('.edit-file.form-control').attr('required',false);
		  }
		});
		$('#t_up').click(function(){
			var el = $(this).addClass('scaleup');
			setTimeout(function() {
				el.removeClass('scaleup');
			}, 1000);
			
		});
		$('#t_down').click(function(){
			var el = $(this).addClass('scaleup');
			setTimeout(function() {
				el.removeClass('scaleup');
			}, 1000);
		});
	});
	
	
</script>