<div id="page-wrapper" style="padding-bottom: 30px; padding-top: 10px; min-height: 400px;">
    <div class="row row-fluid">
        <div class="col-md-12">
            <ul class="nav nav-pills">
              <li role="presentation"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/manage-page/id/<?php echo $this->page_id ?>">Poster Page</a></li>
              <li role="presentation"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/product-service/id/<?php echo $this->page_id ?>">Page Products/Services</a></li>
              <li role="presentation"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/upload-brochure/id/<?php echo $this->page_id ?>">Upload Brochure</a></li>
              <li role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/hide-ads/id/<?php echo $this->page_id ?>">Hide Page Ads</a></li>              
            </ul>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
    			<table class="table table-striped table-bordered table-hover" id="dataTables-example">
    			 <thead>
        			 <tr>
            			 <th class="grid-head"> Poster</th>
                         <th class="grid-head"> Title</th>
                         <th class="grid-head"> Name</th>
                         <th class="grid-head"> Action</th>
                     </tr>
                 </thead>
                 <tbody>
                 <?php foreach ($this->data as $item): ?>
                     <tr>
                        <td class="text-center" style="vertical-align: middle;">
                            <img class="img-responsive" src="<?php echo $this->baseUrl().'/images/uploads/'.$this->dir_name.'/150X150/'.$item['banner_img']?>" alt="<?php echo $item['title']?>" />
                        </td>
                        <td><?php echo $item['title']?></td>
                        <td><?php echo $this->baseUrl().'/'.$item['url_slug'];?></td>
                        <td class="text-center" style="vertical-align: middle;">
                            <?php if($item['is_hidden']==0) {?>
                            <button type="button" class="btn btn-sm btn-danger" onclick="window.location.href='<?php echo $this->baseUrl();?>/mem-pages/hide-show-ads/pid/<?php echo $this->page_id; ?>/id/<?php echo $item['page_id']?>/type/hide'">Hide</button>
                            <?php } else { ?>
                            <button type="button" class="btn btn-sm btn-warning" onclick="window.location.href='<?php echo $this->baseUrl();?>/mem-pages/hide-show-ads/pid/<?php echo $this->page_id; ?>/id/<?php echo $item['page_id']?>/type/show'">Show</button>
                            <?php } ?>
                        </td>
                     </tr>
                 <?php endforeach; ?>
                 </tbody>
                 </table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function(){
       $('#dataTables-example').dataTable(
           {
		      "aaSorting": [[ 1, "asc" ]],
              "iDisplayLength": 50,
              "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
              "aoColumnDefs": [{'bSortable': false, 'aTargets': [3]}]
	       }
        ); 
    });
</script>