<div id="page-wrapper" style="padding-bottom: 20px;">
	
    <div class="row">        
        <div class="col-md-12">             
		
        <div id="msg">
			<?php echo $this->msg ?>
		</div>
        <h1 class="page-header">Dashboard</h1>
        <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
			<thead>
			<tr>
					
					<th class="grid-head"> Page Name</th>
					<th class="grid-head">New Post</th>
					<th class="grid-head">Posts</th>
					<th class="grid-head"> Manage</th>												
				</tr>
			</thead>		
			<tbody> 

			<?php if (count($this->data)){ 
			  foreach ($this->data as $item): ?>
			<tr class="odd gradeX">
				
				
				<td  style="text-align:center;">
				<?php if(strlen($item['url_slug']) > 0){ ?>
				<a href="<?php echo $this->baseUrl(); ?>/<?php echo $item['url_slug'] ?>" target="_blank" title="View Page"><?php echo $item['title'] ?></a>
				<?php }else{ ?>
					Not published yet!
				<?php } ?>
				</td>

				<td  style="text-align:center;">
				<?php if(strlen($item['url_slug']) > 0){ ?>
					<a class="btn btn-sm btn-info " href="<?php echo $this->baseUrl(); ?>/mem-pages/new-product-post/id/<?php echo $item['page_id'] ?>" style="background:#FFF176
;border-radius:0;border:1px solid #FFF176;color:black;">
				   Product   </a>
				   <a class="btn btn-sm btn-info " href="<?php echo $this->baseUrl(); ?>/mem-pages/new-service-post/id/<?php echo $item['page_id'] ?>" style="background:#FFF176
;border-radius:0;border:1px solid #FFF176;color:black;">
				   Service   </a>
				   <a class="btn btn-sm btn-info " href="<?php echo $this->baseUrl(); ?>/mem-pages/new-service-post/id/<?php echo $item['page_id'] ?>" style="background:#FFF176
;border-radius:0;border:1px solid #FFF176;color:black;">
				   Social   </a>
				   <a class="btn btn-sm btn-info " href="<?php echo $this->baseUrl(); ?>/mem-pages/new-video-post/id/<?php echo $item['page_id'] ?>" style="background:#FFF176
;border-radius:0;border:1px solid #FFF176;color:black;">
				   Video   </a>
				   <?php }else{ ?>
					Not published yet!
				<?php } ?>
				</td>
				
				<td  style="text-align:center;">
				<?php if(strlen($item['url_slug']) > 0){ ?>
					<a class="btn btn-sm btn-info " href="<?php echo $this->baseUrl(); ?>/mem-pages/product-post/id/<?php echo $item['page_id'] ?>" style="background:#3B5998;border-radius:0;border:1px solid #3B5998;color:white;">
				   Product   </a>
				   <a class="btn btn-sm btn-info " href="<?php echo $this->baseUrl(); ?>/mem-pages/social-posts/id/<?php echo $item['page_id'] ?>" style="background:#3B5998;border-radius:0;border:1px solid #3B5998;">
				   Social   </a>
				   <a class="btn btn-sm btn-info " href="<?php echo $this->baseUrl(); ?>/mem-pages/service-posts/id/<?php echo $item['page_id'] ?>" style="background:#3B5998;border-radius:0;border:1px solid #3B5998;">
				   Service   </a>
				   <a class="btn btn-sm btn-info " href="<?php echo $this->baseUrl(); ?>/mem-pages/video-posts/id/<?php echo $item['page_id'] ?>" style="background:#3B5998;border-radius:0;border:1px solid #3B5998;">
				   Video   </a>
				   <?php }else{ ?>
					Not published yet!
				<?php } ?>
				</td>
				
				<td style="text-align:center;">
					<?php if(strlen($item['url_slug']) > 0){ ?>
					  <a class="btn btn-sm btn-info " href="<?php echo $this->baseUrl(); ?>/mem-pages/manage-page/id/<?php echo $item['page_id'] ?>"  style="background:#009688;border-radius:0;border:1px solid #009688;">
				   Page   </a>
					<?php }else{ ?>
					  <a class="btn btn-sm btn-warning " href="<?php echo $this->baseUrl(); ?>/mem-pages/add-url/id/<?php echo $item['page_id'] ?>"  style="background:#009688;border-radius:0;border:1px solid #009688;">
				   Publish  </a>
					<?php } ?>
				</td>
					
			</tr>  
				<?php endforeach; } ?> 
			</tbody>
		</table>
							
                    </div><!-- div responsive end-->												
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
</div>

<?php
    function strip_single($tag, $string){
        $string = preg_replace('/<'.$tag.'[^>]*>/i', '', $string);
        $string = preg_replace('/<\/'.$tag.'>/i', '', $string);
        return $string;
    }
?>

  <script type="text/javascript">
 window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('#msg').hide();
			
		<?php  } else{
		?>
			$('#msg').show().delay(5000).hide('slow');
		<?php } ?>
        
        $('#dataTables-example').dataTable(
           {
		      "aaSorting": [[ 3, "asc" ]],
              "iDisplayLength": 50,
              "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]]
	       }
        );
 }
 
    function confirmDelete(id){
    	var r = confirm("Do you realy want to delete this Page?" );
    	if (r == true) {
    	   window.location.assign("<?php echo $this->baseUrl(); ?>/admin/page/delete-page/id/" + id);    
    	} else {
    	   return false;
    	}
	}
 </script>