<style>
	

/*
Author: Bootstrapthemes
Author URI: http://bootstrapthemes.co
*/


/* ==========================================================================
   Author's custom styles
   ========================================================================== */


.p-top-100{
    
}
.m-top-40{
    
}




/*=================================================
Pricint fiv
===================================================*/
.bs-five-area{
    width:100%;
    display: inline-block;
    box-shadow: 0px 0px 6px 0px #ddd;
    overflow: hidden;
    position: relative;
    font-family: 'Open Sans', sans-serif;
    text-align: center;
}

.bs-five-area.bs-radius{
    border-radius: 30px;
}
.bs-five-area > div{
    padding:0;
}


.bs-five-area .bs-five{
    position: relative;
    width: 100%;  
    margin: auto; 
    transition: all 0.4s;
    padding:20px 0px;
}
.bs-five-area .bs-five h6{
    font-weight: 700;
    letter-spacing: 2px;
}
.bs-five-area .bs-five h1{
    font-size:64px;
    font-weight: 100;
    line-height: 72px;
}
.bs-five-area .bs-five h1 sup{
    font-size:30px;
    top:-30px;
}
.bs-five-area .bs-five ul {
    margin:0;
    padding:0;
    list-style: none;
}
.bs-five-area .bs-five ul li{
    line-height: 45px;
    border-bottom:0px;
}


.bs-five-area .bs-five:hover{

    background: #179880; 
    transition: all 0.4s;

}

.bs-five-area .bs-five.active {
    background: #179880; 
    background: -webkit-linear-gradient(left, #179880 , #21A476); 
    background: -o-linear-gradient(right, #179880, #21A476); 
    background: -moz-linear-gradient(right, #179880, #21A476); 
    background: linear-gradient(to right, #179880 , #21A476);  
}

.bs-five-area .bs-five .btn-success{
    padding: 10px 50px;
    display: inline-block;
    border-radius: 30px;
    background-color: #179880;
    border-color: #21A476;
}


.bs-five-area .bs-five.active .btn.btn-success, 
.bs-five-area .bs-five:hover.bs-five .btn.btn-success{
    background: #E0FFF6 ; 
    color:#444 ;

}

.bs-five-area .bs-five.active,
.bs-five-area .bs-five.active ul li,
.bs-five-area .bs-five:hover.bs-five, 
.bs-five-area .bs-five:hover.bs-five ul li
{
    color:#fff;
}
















</style>
<div id="page-wrapper" style="padding-bottom: 20px;">
	
    <div class="row">        
        <div class="col-md-12">             
		
        <div id="msg">
			<?php echo $this->msg ?>
		</div>
        <h1 class="page-header text-center">Buy Packages</h1>
        	  <section id="bs-pricing-five" class="bs-pricing-five p-top-100 bg-white" style="    padding: 0 80px;">
            
                <div class="row">
                    <div class="bs-five-area bs-radius">
                        <div class="col-md-4 no-padding">
                            <div class="bs-five">
                                <h6 class="text-uppercase">1 Business Page</h6>
                                <h1 class="bs-caption"><sup>RM</sup>400</h1>
                                <p>1 Interactive Landing Page</p>
                                <ul>
                                    <li><b>1500 Posts</b></li>
                                    <li>1000 Words Contents</li>
                                    <li>365 Days</li>
                                    
                                </ul>
								<p><b>GST included</b></p>
								<p><b>Every page has a unique web address (URL)</b></p>
                                <form method="post" action="https://www.sandbox.paypal.com/cgi-bin/webscr" style="margin-top:15px;">
		<input type="hidden" name="business" value="valeedmehmood786-facilitator@gmail.com">
        
        <!-- Specify a Buy Now button. -->
        <input type="hidden" name="cmd" value="_xclick">
        
        <!-- Specify details about the item that buyers will purchase. -->
        <input type="hidden" name="item_name" value="package1">
        <input type="hidden" name="item_number" value="1">
        <input type="hidden" name="amount" value="400">
        <input type="hidden" name="currency_code" value="USD">
        
        <!-- Specify URLs -->
        <input type='hidden' name='cancel_return' value='http://pageiz.com/mem-pages/packages'>
        <input type='hidden' name='return' value='http://pageiz.com/mem-pages/success?p=1'>
        
        <!-- Display the payment button. -->
        <input type="image" name="submit" border="0"
        src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_LG.gif" alt="PayPal - The safer, easier way to pay online">
        <img alt="" border="0" width="1" height="1" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" >
	</form>
                            </div>
                        </div>
                        <div class="col-md-4 no-padding">
                            <div class="bs-five active">
                                <h6 class="text-uppercase">4 Business Page</h6>
                                <h1 class="bs-caption"><sup>RM</sup>1400</h1>
                                <p>4 Interactive Landing Page</p>
                                <ul>
                                    <li><b>2000 Posts per Page</b></li>
                                    <li>3500 Words Contents</li>
                                    <li>365 Days</li>
                                    
                                </ul>
								<p><b>GST included</b></p>
								<p><b>Every page has a unique web address (URL)</b></p>
                                <form method="post" action="https://www.sandbox.paypal.com/cgi-bin/webscr" style="margin-top:15px;">
		<input type="hidden" name="business" value="valeedmehmood786-facilitator@gmail.com">
        
        <!-- Specify a Buy Now button. -->
        <input type="hidden" name="cmd" value="_xclick">
        
        <!-- Specify details about the item that buyers will purchase. -->
        <input type="hidden" name="item_name" value="package2">
        <input type="hidden" name="item_number" value="4">
        <input type="hidden" name="amount" value="1500">
        <input type="hidden" name="currency_code" value="USD">
        
        <!-- Specify URLs -->
        <input type='hidden' name='cancel_return' value='http://pageiz.com/mem-pages/packages'>
        <input type='hidden' name='return' value='http://pageiz.com/mem-pages/success?p=4'>
        
        <!-- Display the payment button. -->
        <input type="image" name="submit" border="0"
        src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_LG.gif" alt="PayPal - The safer, easier way to pay online">
        <img alt="" border="0" width="1" height="1" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" >
	</form>
                            </div>
                        </div>
                        
                        <div class="col-md-4 no-padding">
                            <div class="bs-five">
                                <h6 class="text-uppercase">8 Business Page</h6>
                                <h1 class="bs-caption"><sup>RM</sup>2600</h1>
                                <p>8 Interactive Landing Page</p>
                                <ul>
                                    <li><b>2500 Posts  per Page</b></li>
                                    <li>7000 Words Contents</li>
                                    <li>365 Days</li>
                                   
                                </ul>
								<p><b>GST included</b></p>
								<p><b>Every page has a unique web address (URL)</b></p>
                                <form method="post" action="https://www.sandbox.paypal.com/cgi-bin/webscr" style="margin-top:15px;">
		<input type="hidden" name="business" value="valeedmehmood786-facilitator@gmail.com">
        
        <!-- Specify a Buy Now button. -->
        <input type="hidden" name="cmd" value="_xclick">
        
        <!-- Specify details about the item that buyers will purchase. -->
        <input type="hidden" name="item_name" value="package3">
        <input type="hidden" name="item_number" value="8">
        <input type="hidden" name="amount" value="2500">
        <input type="hidden" name="currency_code" value="USD">
        
        <!-- Specify URLs -->
        <input type='hidden' name='cancel_return' value='http://pageiz.com/mem-pages/packages'>
        <input type='hidden' name='return' value='http://pageiz.com/mem-pages/success?p=8'>
        
        <!-- Display the payment button. -->
        <input type="image" name="submit" border="0"
        src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_LG.gif" alt="PayPal - The safer, easier way to pay online">
        <img alt="" border="0" width="1" height="1" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" >
	</form>
                            </div>
                        </div>
                    </div>
                </div>
            
        </section>
        
          											
		</div>
		<!-- /.col-lg-12 -->
	</div>
            <!-- /.row -->
</div>



<script type="text/javascript">
	
</script>