<div id="page-wrapper">
    <div class="row">
	   <div class="col-md-12">
		<h2>Page Likes</h2>
        
		<div class="table-responsive">
			<table class="table table-striped table-bordered table-hover" id="dataTables-example">
			 <thead>
			 <tr>
			 <th class="grid-head"> Page Title</th>
             <th class="grid-head"> Liked By</th>
             <th class="grid-head"> Date</th>
             </tr>
             </thead>
             <tbody>
             <?php foreach ($this->data as $item): ?>
                 <tr>
                    <td><?php echo $item['title']?></td>
                    <td><?php echo $item['first_name']. ' '. $item['last_name'];?></td>
                    <td style="text-align:center;"> <?php echo date('m/d/Y h:i A', strtotime($item['date_created'])) ?> </td>
                 </tr>
             <?php endforeach; ?>
             </tbody>
             </table>
        </div>
        </div>
        </div>
</div>


<script type="text/javascript">
    $(function(){
       $('#dataTables-example').dataTable(
           {
		      "aaSorting": [[ 2, "desc" ]], // 4th index or 5th column in descending order
              "iDisplayLength": 50,
              "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]]
	       }
        ); 
    });
</script>