<style>
	.li_btn{
		border-radius:0;
		background:#1B1C52;
		border:1px solid #1B1C52;
		
	}
	.li_btn > a{
		color:white;
	}
	.nav>li>a:focus, .nav>li>a:hover {
    text-decoration: none;
    color:white;
		background:#1B1C52;
}
</style>
<div id="page-wrapper" style="padding-bottom: 30px; padding-top: 10px;">
    <div class="row row-fluid">
        <div class="col-md-12">
            <ul class="nav nav-pills">
          <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/manage-page/id/<?php echo $this->page_id ?>">Main Page</a></li>
		  <!--li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/upload-slider/id/<?php echo $this->page_id ?>">Upload Slider</a></li-->
          <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/new-product-post/id/<?php echo $this->page_id ?>">New Product Post</a></li>
		  <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/new-social-post/id/<?php echo $this->page_id ?>">New Social Post</a></li>
		  <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/product-post/id/<?php echo $this->page_id ?>">Product Posts</a></li>
		  <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/social-posts/id/<?php echo $this->page_id ?>">Social Posts</a></li>
          <li class="li_btn" role="presentation"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/upload-brochure/id/<?php echo $this->page_id ?>">Upload Brochure</a></li>
		  <li class="li_btn" role="presentation"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/comments/id/<?php echo $this->page_id ?>">Comments</a></li>
         <!--li class="li_btn" role="presentation"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/hide-ads/id/<?php echo $this->page_id ?>">Hide Page Ads/Description</a></li-->
		 
          <!--li role="presentation"><a href="<?php echo $this->baseUrl(); ?>/members/ad-image/id/<?php echo $this->page_id ?>">Advertisement Image block</a></li>
          <li role="presentation"><a href="<?php echo $this->baseUrl(); ?>/members/rbar-ads/id/<?php echo $this->page_id ?>">Right Bar Advertisments</a></li-->
        </ul>
        </div>
    </div>
    <hr />
    
    <div id="preview-area" class="row" style="margin-bottom: 10px;">
        <div class="col-md-4">
            <label id="title">Title: <?php echo $this->title;?></label>
        </div>
        <div class="col-md-8">
            <img id="img-brochure" class="img-responsive" src="<?php echo $this->src;?>" alt="Brochure Image" style="width: 300px;" />
        </div>
    </div>
    
    <div class="row">
            <div class="col-md-8 col-md-offset-1">
			        
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-upload fa-4x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge heading-top">Upload Brochure</div>                            
                                </div>
                            </div>
                        </div>
                       
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data" >
                                       	
										<table class="table table-striped table-bordered table-hover set-basic1">
                                    	
                                        <div id="msg" style="font-weight: bold; display: none;">
                                            <?php echo $this->msg ?>
                                        </div>
                                     
					<tr>
                        <td><label>Select a Brochure to Update:</label></td>
                        <td>
                            <select id="m_brochuer_id" name="m_brochuer_id" class="form-control">
                                <?php echo $this->brochure_ddl;?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td><label>Brochure Title:</label></td>
                        <td><?php echo $this->form->title;?></td>
                    </tr>
                     <tr>
                        <td><label>Brochure Image:</label></td>
                        <td><?php echo $this->form->image;?></td>
                    </tr>
                      <tr>
        		          <td style="vertical-align: middle;"><label> Select Brochure: </label></td>
        				  <td>
        				      <?php echo $this->form->brochure;?>
                              <span>Upload only pdf file</span>
                          </td>
                      </tr>
                  <tr>
    		          <td colspan='2'>
    				      <?php echo $this->form->submit;?>
                      </td>
                </tr>
            </table>
        </form>
       </div>
    </div>
    </div>
    </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-8 col-md-offset-1">
            <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-trash-o fa-4x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Delete Brochure</div>
                                </div>
                            </div>
                        </div>
                       
            <div class="panel-body">
                <table class="table table-striped table-bordered table-hover set-basic1">
               	    <div id="delete-msg" style="font-weight: bold; display: none;"></div>
                    <tr>
                        <td><label>Select Brochure:</label></td>
                        <td>
                            <select id="save_brochuer_id" class="form-control">
                                <?php echo $this->brochure_ddl;?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <a id="btn-delete" href="javascript:void(0);" class="btn btn-danger pull-right">Delete</a>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        
        </div>
                <!-- /.col-lg-12 -->
    </div>
            <!-- /.row -->
</div>
        <!-- /#page-wrapper -->
        
        <script type="text/javascript">
            $(function(){
               <?php if(!isset($this->msg)){ ?>
        			$('#msg').hide();			
        		<?php  } else{ ?>
        			$('#msg').show().delay(7000).hide('slow');
        		<?php } ?> 
                
                $('#submit').click(function(){
                    if($('#page_id').val()==0){
                        $('#msg').html('<div class="alert alert-warning">Please select a page</div>').show().delay(7000).hide('slow');
                        return false;
                    }
                });
                
                $('#btn-delete').click(function(){
                    if($('#save_brochuer_id').val()==0){
                        $('#delete-msg').html('<div class="alert alert-warning">Please select a brochure to delete</div>').show().delay(7000).hide('slow');
                        return false;
                    }
                    
                    var r = confirm("Do you realy want to delete this brochure?" );
                	if (r == true) {
                	   window.location.assign("<?php echo $this->baseUrl(); ?>/mem-pages/delete-brochure/page_id/<?php echo $this->page_id; ?>/m_brochuer_id/"+$('#save_brochuer_id').val());    
                	} else {
                	   return false;
                	}
                });
            
                <?php if(!isset($this->src)) {?>
                    $('#preview-area').hide();
                <?php }?>
                
            }); //ready function end
            
            $('#m_brochuer_id').change(function(){
               if($(this).val()>0){
                    $('#submit').val('Update Brochure');
                    $('.heading-top').text('Update Brochure');
               } else {
                    $('#submit').val('Upload Brochure');
                    $('.heading-top').text('Upload Brochure');
               }
               
               $.ajax({
                    type: 'GET',
                    url: '<?php echo $this->baseUrl();?>/mem-pages/show-brochure',
                    data: {m_brochuer_id:$(this).val() },
                    success: function(result){
                        result = JSON.parse(result);
                        
                        if(result.title==null && result.src==null){
                            $('#preview-area').hide();
                        } else {
                            $('#preview-area').show();
                        }
                        
                        if(result.title==null){
                            $('#title').hide();
                        } else {
                            $('#title').text((result.title!="")?('Title: ' + result.title):"").show();    
                        }
                        
                        if(result.src==null){
                            $('#img-brochure').hide();
                        }else{
                            $('#img-brochure').attr('src', result.src).show();   
                        }
                    },
                    error: function(e){
                        console.log(e);
                        $('#msg').html('<div class="alert alert-warning">Some error occur. Please try again.</div>').show().delay(7000).hide('slow');
                        $('#preview-area').hide();
                    }
               });
            });
        </script>