<?php

	function timeago($date) {
		$timestamp = strtotime($date);	

		$strTime = array("second", "minute", "hour", "day", "month", "year");
		$length = array("60","60","24","30","12","10");

		$currentTime = time();
		if($currentTime >= $timestamp) {
			$diff     = time()- $timestamp;
			for($i = 0; $diff >= $length[$i] && $i < count($length)-1; $i++) {
			$diff = $diff / $length[$i];
			}

			$diff = round($diff);
			return $diff . " " . $strTime[$i] . " ago ";
		}
}

?>
<style>
#title{
	font-size: 24px;	
}
.labels{
color: #444444;	
}
.btn-xs {
    padding: 1px 5px!important;
}
#page-wrapper {
    padding-bottom: 30px;
    padding-top: 10px;
}
#file-selector {
    margin-top: 10px;
    margin-left: 35px;
    position: absolute;
    background-color: #fff;
    opacity: .8;
    top: 0;
    padding: 5px;
	text-decoration: none !important;
}
#file-selector:hover {
    cursor: pointer;
    border: 1px solid;    
}
.li_btn{
		border-radius:0;
		background:#1B1C52;
		border:1px solid #1B1C52;
		margin-top: 5px;   
	}
	.li_btn > a{
		color:white;
	}
	.nav>li>a:focus, .nav>li>a:hover {
    text-decoration: none;
    color:white;
		background:#1B1C52;
}
.linkers.col-md-12 > p > a {
color:#263238;
transition:all 0.4s linear;
}
.linkers.col-md-12 > p > a:hover {
text-decoration:none;
}
.video-container {
	position: relative;
	padding-bottom: 56.25%;
	padding-top: 30px; height: 0; overflow: hidden;
	}
	 
	.video-container iframe,
	.video-container object,
	.video-container embed {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	}
</style>
<div id="page-wrapper" style="padding-top:20px;">
<div class="row row-fluid">
    <div class="col-md-12">
    <?php //echo $this->render('/members/menu.phtml'); ?>
    
        <ul class="nav nav-pills">
          <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/manage-page/id/<?php echo $this->page_id ?>">Main Page</a></li>
		  <!--li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/upload-slider/id/<?php echo $this->page_id ?>">Upload Slider</a></li-->
          <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/new-product-post/id/<?php echo $this->page_id ?>">New Product Post</a></li>
		  <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/new-service-post/id/<?php echo $this->page_id ?>">New Service Post</a></li>
		  <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/new-social-post/id/<?php echo $this->page_id ?>">New Social Post</a></li>
		  <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/product-post/id/<?php echo $this->page_id ?>">Product Posts</a></li>
		  <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/service-posts/id/<?php echo $this->page_id ?>">Service Posts</a></li>
		  <li class="li_btn" role="presentation" class="active"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/social-posts/id/<?php echo $this->page_id ?>">Social Posts</a></li>
          <li class="li_btn" role="presentation"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/upload-brochure/id/<?php echo $this->page_id ?>">Upload Brochure</a></li>
		  <li class="li_btn" role="presentation"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/comments/id/<?php echo $this->page_id ?>">Comments</a></li>
		  <li class="li_btn" role="presentation"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/feedback/id/<?php echo $this->page_id ?>">Get Feedback</a></li>
		  <li class="li_btn" role="presentation"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/popup-design/id/<?php echo $this->page_id ?>">Customize CTA</a></li>
         <!--li class="li_btn" role="presentation"><a href="<?php echo $this->baseUrl(); ?>/mem-pages/hide-ads/id/<?php echo $this->page_id ?>">Hide Page Ads/Description</a></li-->
		 
          <!--li role="presentation"><a href="<?php echo $this->baseUrl(); ?>/members/ad-image/id/<?php echo $this->page_id ?>">Advertisement Image block</a></li>
          <li role="presentation"><a href="<?php echo $this->baseUrl(); ?>/members/rbar-ads/id/<?php echo $this->page_id ?>">Right Bar Advertisments</a></li-->
        </ul>
    </div>
</div>

	<div style="width: 100%; height: 23px; border-bottom: 1px solid black; text-align: center;margin-top: 20px;">
      <span style="    font-size: 31px;background-color: white;padding: 0px 17px;">
        Video Post <!--Padding is optional-->
      </span>
    </div>
	<?php 
		if(isset($this->status)){
			echo $this->status;
		}
	
	?>
	<div id="product-service-list" style="margin-top:40px;">
                <div class="row" style="    margin: 0 208px;">
                    <?php 
					if(count($this->videos)>0){
					
					foreach(array_chunk($this->videos->toArray(),1) as $row): ?>
					<div class="row" id="search_products">
					<?php
					
					foreach ($row as $item): ?>
                        <div class="col-md-12" style="margin-bottom:40px;">
						<div class="linkers col-md-12"  style="box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);">
							
							<p class="" style="margin: 0 3px 10px;font-size: 11px;color:#4527A0"><?php echo timeago($item['date_created']) ?> <i class="fa fa-clock-o"></i> </p>
							<div class="video-container" style="margin:10px 0;">
								<iframe width="853" height="480" src="<?php echo  $item['video_url'] ?>" frameborder="0" allowfullscreen></iframe>
							</div>
                            <p>
								<input type="hidden" id="update_url_<?php echo $item['pp_id'] ?>" value="<?php echo  $item['video_url'] ?>">
								<input type="hidden" id="update_page_id_<?php echo $item['pp_id'] ?>" value="<?php echo $this->page_id ?>">
								<input type="hidden" value="<?php echo $item['pp_id'] ?>" id="update_pp_id_<?php echo $item['pp_id'] ?>">
                                <a href="javascript:void(0)" onclick="editmodal('<?php echo $item['pp_id'] ?>')">Edit</a>
								
                                <a href="#" onclick="doDelete(<?php echo $item['pp_id'];?>, <?php echo $this->page_id;?>);" class="pull-right">Delete</a>
								   
                            </p>
                            
						</div>
                            
                        </div>
                    <?php endforeach; ?>
					</div>
			<?php endforeach;
					}else{ ?>
						<h4 class="text-center">No Post Found!</h4>
				<?php	
				}
					?>	
				
				</div>
            </div>
</div>
<!-- Trigger the modal with a button -->


<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Edit Video Post</h4>
      </div>
      <div class="modal-body">
			<form method="post" action="">
                    
				<div class="row">
				 <input type="hidden" value="<?php echo $this->page_id  ?>" name="page_id">	
					<div class="col-md-12">
						
						 <div class="form-group">
							<label for="">Video</label>
							<input type="text" name="video_url" class="form-control" required id="video_url" placeholder="Youtube Embed Video URL">
							<input type="hidden" name="pp_id" id="pp_id"></input>
							<input type="hidden" name="page_id" id="page_id"></input>
						 </div> 
						
					</div>
					<div class="col-md-12">
						
						 <div class="video-container" id="video_modal">
							<iframe width="853" height="480" src="<?php echo  $this->list['video_link'] ?>" frameborder="0" allowfullscreen></iframe>
						</div>
						
					</div>
				</div>
				
				<input class="btn btn-success" type="submit" value="Update" style="margin-top:10px;">
			</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
<script>
$(document).ready(function(){
	// $('.details-box').hide();
	// $('#ck_image').children('img').attr('class','img-responsive');
	

});

	
	function doDelete(id, pId){
    	var r = confirm("Are you sure to Delete this post?");
    	if (r == true) {
    	   window.location.assign("<?php echo $this->baseUrl(); ?>/mem-pages/delete-video/id/" + id+"/page_id/"+pId);    
    	} else {
    	   return false;
    	}
	}
	function editmodal(id){
		var url = $('#update_url_'+id).val();
		var page_id = $('#update_page_id_'+id).val();
		var pp_id = $('#update_pp_id_'+id).val();
		$('#video_url').val(url);
		$('#page_id').val(page_id);
		$('#pp_id').val(pp_id);
		$('#video_modal').html('<iframe width="853" height="480" src="'+url+'" frameborder="0" allowfullscreen></iframe>');
		$('#myModal').modal({
			show: 'true'
		});
	}
</script>
