<style>
		/* custom class for form to control it*/
		.space-top{
		padding-top: 40px;
		}
		</style>       

	   <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                         <div class="col-lg-9 col-md-16">
                          <div class="row" style="height:50px; padding:0; margin:0">
                 <div class="col-xs-3">
                 	<table class="table">
                    <tr><td> <a href="<?php echo $this->baseUrl(); ?>/admin/countries/list"> <i class="fa fa-list  alert-primary"></i> List</a></td>
                    <td>  <a href="<?php echo $this->baseUrl(); ?>/admin/countries/new"> <i class="fa fa-plus alert-primary"></i> New</a></td>
                    </tr>
                    </table>
                 </div>
                   </div>      
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-globe fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Edit Country</div>
                            
                                </div>
                            </div>
                        </div>
                        <div class="panel-body">
                                <span class="pull-left">Enter Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                  
                                    <form class="form-horizontal space-top" action="" method="POST" enctype="multipart/form-data" >
                                       	<table class="table table-striped table-bordered table-hover">
                                    	<tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
										<?php echo $this->form->country_name?>
                                        <?php echo $this->form->country_code ?>
                                        <tr><td>&nbsp;</td><td>
                                         <input type="submit" value="Save" class="btn btn-lg btn-primary float-right">
										
										</td></tr>
										</table>
									</form>
	                              
                                </div>
                            </div>
                             <a href="#">
                            <div class="panel-footer">
                            </div>
                        </a>
                    </div>
                </div>
                
                
          
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



  <script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }
 </script>