<style>
/* css for setting panel head */
.list-post-space{
margin-top:40px;
}

@media only screen and (min-width : 318px) and (max-width : 979px) {
.set-glob{
margin-left:-19%;}

.set-search{
margin-left:40%;
}

.sarch-widh{
width:100%;
}
.set-country {
    margin-left: 22%;
}
}

@media only screen and (min-width : 980px) and (max-width : 1279px) {
.set-search{
margin-left:10%;
}
.set-country {
    float: right;
    margin-top: -9%;
}
}

@media only screen and (min-width : 602px) and (max-width : 967px) {
.set-search {
    margin-left: 24%;
}

.set-glob{
margin-left:0%;
}

.set-country {
    margin-left: 12%;
}
}
</style>       

	   <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                         <div class="col-lg-12 col-md-26">
                         <div class="row" style="height:50px; padding:0; margin:0"><!-- row 1-->
                 <div class="col-xs-3">
                 	<table class="table">
                    <tr><td> <a href="<?php echo $this->baseUrl(); ?>/admin/countries/list"> <i class="fa fa-list  alert-warning"> List</i></a></td>
                    <td>  <a href="<?php echo $this->baseUrl(); ?>/admin/countries/new"> <i class="fa fa-plus alert-warning"> New</i></a></td>
                    </tr>
                    </table>
                 </div>
                 </div><!-- ./ row 1-->
                 
                 
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-1 set-glob">
                                    <i class="fa fa-globe fa-5x"></i>
                                </div>
                                <div class="col-xs-6 set-search">
                                <form action="<?php echo $this->baseUrl(); ?>/admin/countries/list" action="post">
                                <div class="input-group custom-search-form col-xs-6 text-right sarch-widh" style="padding-top:20px">
                                <input type="text" name="query_string" id="query_string" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            
                            </div>
                            </form>
                                </div>
                                <div class="col-xs-5 text-right set-country">
                                    <div class="huge">Countries List
                        </div>
                                </div>
                            </div>
                        </div>
                   
                        
                             <div class="panel-body">
                         <span class="pull-left">Use buttons for operations</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                                
												<div class="table-responsive">
													<table cellpadding="0" cellspacing="0" border="0" class="dynamicTable display table table-bordered list-post-space" width="100%">
														<thead>
															<tr>
																<th>Country Name</th>
																<th>Country Code</th>
																<th>Edit</th>
																<th>Block</th>
															 	</tr>
														</thead>		
														<tbody>
                                          
														<?php if (count($this->paginator)){ ?>
													
														<?php foreach ($this->paginator as $item): ?>
														<tr class="odd gradeX">
															<td>
															<?php echo $item['country_name'] ?>
															</td>
                                                            <td>
															<?php echo $item['country_code'] ?>
															</td>
                                                        
                                                            	<td><a class="btn btn-sm btn-warning float-right" href="<?php echo $this->baseUrl(); ?>/admin/countries/edit/country_id/<?php echo $item['country_id'] ?>">Edit</a></td>
															<td><a class="btn btn-sm btn-info float-right" href="<?php echo $this->baseUrl(); ?>/admin/countries/confirm-block/country_id/<?php echo $item['country_id'] ?>">Block</a></td>
														</tr>
															<?php endforeach; ?>
															<tr><td colspan='9'>
															<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>
															</td>
															</tr><?php }else{ ?>
											
															<tr><td colspan="7"><h4>There are no country created! Please create one</h4></td></tr>
															<?php } ?>
														</tbody>

														</table>
														</div><!--table-responsive div end-->
												</div>

                               
                                
                                </div>
                                
                               <a href="#">
                            <div class="panel-footer">
                             
                            </div>
                        </a>
                       
                    </div>
                </div>
                
          
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



  <script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }
 </script>