<style>
	.container > .container{
		padding: 0;
	}
	.register,.texter,.register-panel{
		padding:40px;
	}
	.register > .row > .col-md-6 > img{
		width:60%;
		    margin: auto;
	}
	.texter > .row > .col-md-6 > img{
		width: 80%;
		margin: auto;
		margin-top: 35px;
	}
	.register > .row > .col-md-6 > .login{
		border-radius:0;
		background:#1B1C52;
		color:white;
		border:1px solid #1B1C52;
		    padding-left: 30px;
		padding-right: 30px;
		padding-top: 10px;
		padding-bottom: 10px;
	}
	.register > .row > .col-md-6 > .register-btn{
		border-radius:0;
		background:#54D33F;
		color:white;
		border:1px solid #54D33F;
		    padding-left: 30px;
			padding-right: 30px;
			padding-top: 10px;
			padding-bottom: 10px;
	}
	.register > .row > .login-detail{
		    padding-left: 30px;
    padding-right: 30px;
	padding-top: 18px;
	}
	.register > .row > .col-md-6 > h3{
		font-family: sans-serif;
    font-size: 30px;
	}
	.register > .row > .col-md-6 > h4{
		font-family: sans-serif;
    font-size: 25px;
	}
	.register > .row > .col-md-6 > p{
		font-family: sans-serif;
    font-size: 20px;
	}
	.texter > .row > .login-detail > h4{
		font-family: sans-serif;
    font-size: 30px;
	}
	.texter > .row > .login-detail > p{
		font-family: sans-serif;
    font-size: 20px;
	// text-align:justify;
	}.form-control{
		border-radius:0;
		// border:2px solid #FBB03B;
	}
	.register-panel > .row > .login-detail{    
	padding-left: 50px;
    padding-right: 50px;
	}
</style>

<div class="container-fluid" style="background-repeat: no-repeat; background-size: 100%; /* height: 600px; */ /* display: inline; */ background-image: url(../images/pageizbanner.png); /* position: absolute; */ width: 100%; /* display: block; */ /* height: 0; */ padding-top: 43.3%;">
	
</div>
<div class="register container">
	<div class="row">
		<div class="col-md-6 text-center">
			<img class="img-responsive" src="http://www.rightmixmarketing.com/wp-content/uploads/2015/05/social-media-statistics-2015.jpg">
		</div>
		<div class="login-detail col-md-6 text-center">
			
			<h4 style="color:#1B1C52;">BECOME A MARKETER</h4>
			<p>For selling pages you can make from RM100 to RM1400 from a single deal</p>
			<a href="/marketer/login" class="login btn btn-success">Login</a>
			<a href="/marketer/register" class="register-btn btn btn-success">Register</a>
		</div>
	</div>
</div>

<div class="texter container">
	<div class="row">
	<div class="login-detail col-md-6 text-center">
			
			<h4 style="color:#1B1C52;">ADVANTAGES</h4>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque imperdiet lorem eu arcu pellentesque, non vulputate nulla consequat. Fusce porttitor, dolor eu semper hendrerit, diam ligula faucibus magna, ac pharetra neque erat sit amet ante. Donec et ligula purus. Nam a enim volutpat, euismod felis vitae, posuere sem. Etiam vel orci vel lectus sollicitudin ultrices ut eu eros. Etiam sed aliquet tortor, at porttitor nunc. Donec faucibus arcu non metus vehicula, pretium pretium elit dictum. Donec auctor ultricies sapien et dapibus. 

</p>
			
		</div>
		<div class="col-md-6 text-center">
			<img class="img-responsive" src="../images/mark2.png">
		</div>
		
	</div>
</div>

<div class="register-panel container text-center"> 
	<div class="row">
	<div class="col-md-6 text-center">
		<img class="img-responsive" src="../images/mark1.png">
	</div>
	<div class="login-detail col-md-6 text-center">
	<h3 style="color:#1B1C52;font-family: sans-serif;
    font-size: 25px;padding-bottom:10px;">BECOME A MARKETER</h3>
		<form action="" method="post" role="form">   
		
        <div id="msg"><?php echo $this->msg;?></div>
            <div class="form-group">
                <input type="text" placeholder="Enter Your Name *" name="first_name" class="form-control"  required>             
            </div>
            <div class="form-group">
                <input type="email" placeholder="Enter Your Email *" name="email" class="form-control"  required>
            </div>
            <div class="form-group">
                <input type="number" placeholder="Enter Your Phone *" name="contact_number" class="form-control"  required>
            </div>
            <div class="form-group">
                <input type="address" placeholder="Enter Your Address *" name="street_address" class="form-control"  required>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <button class="btn btn-sucess btn-block" type="submit" style="background-color:#FBB03B;color:white;border-radius:0;border:1px solid #FBB03B">Register</button>
                </div>
            </div>      
    
        
    </form>
	</div>
		
		
	</div>
</div>
