<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.3.1/css/mdb.min.css">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css
">
<script src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.3.1/js/mdb.min.js
"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js
"></script>
<style>
    .panel{
       box-shadow: 0 0 10px grey !important;
     }
     .panel-footer, .panel-header{ 
        background-color: #1B1C52;
        padding: 10px;
        color: #fff;
     }
     #btn-checkout {
        border: 0;
        padding: 5px 20px;
     }
     .panel-body {
        padding: 30px 40px;
     }
</style>
<nav class="navbar  navbar-inverse" style="background:#333333;">
  <div class="container">
  <button type="button" class="navbar-toggle"
  data-toggle="collapse"
  data-target=".navbar-collapse"
  >
  <span class="sr-only"> Toggle navigation</span>
  <span class="icon-bar"> </span>
  <span class="icon-bar"> </span>
  <span class="icon-bar"> </span>
  </button>
  
   
   
       <div class="navbar-collapse collapse">
           <ul class="nav navbar-nav navbar-right">
				<li><a href="<?php echo $this->baseUrl(); ?>/index/become-member">Become a Member</a></li>
				<li><a href="<?php echo $this->baseUrl(); ?>/index/packages">Create a Page</a></li>
				<li><a href="<?php echo $this->baseUrl(); ?>/index/poster-samples">Banner/Poster Samples</a></li>
				<?php if(isset($this->user_role) && isset($this->logged_user_id)) {?>
				<li><a href="<?php echo $this->baseUrl(); ?>/mem-pages/index"> <i class="fa fa-user fa-home"></i> Dashboard</a></li>
				<?php } else {?>
				<li><a href="<?php echo $this->baseUrl();?>/authentication/login">Login</a></li>
				<?php }?>           
			    <li><a href="<?php echo $this->baseUrl(); ?>/marketer/index">Become a Marketer</a></li>
				<!-- li><a href="<?php echo $this->baseUrl(); ?>/categories/index">Resellers</a></li -->
				<li><a href="<?php echo $this->baseUrl(); ?>/blog">Blog <span class="sr-only">(current)</span></a></li>
		   </ul>
       </div>
  </div>
</nav>
<div class="container" style="padding-top: 100px; padding-bottom:100px;">
	<div class="row">
       <div class="col-md-6 col-md-offset-3"> 
			<!--Form with header-->
<div class="card" style="box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);">
    <div class="card-block" style="padding:40px;">

        <!--Header-->
        <div class="form-header blue-gradient">
            <h3><i class="fa fa-user"></i> Become a Marketer</h3>
        </div>
		<form action="" method="post" role="form">   
        <!--Body-->
        <div class="md-form">
			<i class="fa fa-user prefix"></i>
			<input type="text" id="form3" class="form-control" name="first_name" required>
			<label for="form3">Your name</label>
		
        <div class="md-form">
            <i class="fa fa-envelope prefix"></i>
            <input type="text" id="email" name="email" class="form-control" required>
            <label for="form2">Your Email</label>
        </div>
		<div class="md-form">
            <i class="fa fa-user prefix"></i>
            <input type="text" id="phone" name="contact_number" class="form-control" required>
            <label for="form3">Your Phone</label>
        </div>
		<div class="md-form">
        <i class="fa fa-pencil prefix"></i>
        <textarea type="text" id="form8" class="md-textarea"></textarea>
        <label for="form8">Address</label>
		</div>
        <div class="text-center">
            <button type="submit" class="btn btn-indigo ">Register</button>
            
        </div>
		</form>
    </div>
</div>
<!--/Form with header-->
<!--/Form with header-->
<!--/Form without header-->
	   </div>
	</div>   
</div>
</div>
<input type="hidden" value="<?php echo $this->msg; ?>" id="msg_alert">
<div class="navbar  navbar-inverse"> 
     <div class="container">
       <div class="navbar-text pull=left">
	    <p>&copy; Pageiz.</p>
	   </div>
	      
	 </div>
</div>
<script type="text/javascript">
	
    $(function(){
		var data = $('#msg_alert').val()
		if(data !== ''){
			toastr.info(data);
		}
			
		
        
    });
    
</script>