<div class="row" style="margin-top: 50px;">
    <div id="msg"><?php echo $this->msg; ?></div>
    <div class="col-lg-12">
        <div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title" style="color: #337AB7;">
					Reset Site Front-end to default
				</h3>
			</div>
			<div class="panel-body">
				<a href="<?php echo $this->baseUrl(); ?>/admin/reset-default/index/x/200" id="reset-site" class="btn btn-primary" style="width: 20%;">Reset to default</a>
			</div>
        </div>
    </div>
</div>

<script language="Javascript" type="text/javascript">
$(function() {
 <?php if(!isset($this->msg)){ ?>
      $('#msg').hide();
    <?php  } else{ ?>
      $('#msg').show().delay(3000).hide('slow');
    <?php } ?>
 });
</script>