<?php
if(Zend_Registry::get("lang_id") == 1){
$adapter = new Zend_Translate(
    array(
        'adapter' => 'array',
        'content' => array('page_heading' => ' Register a new State'),
        'locale'  => 'en'
    )
);
}
if(Zend_Registry::get("lang_id") == 2){
$adapter = new Zend_Translate(
    array(
        'adapter' => 'array',
        'content' => array('page_heading' => 'نئے شہر کا اندراج کریں','Select State' => 'ریاست کا انتخاب کریں','Cities' => 'شہر' ),
        'locale'  => 'en'
    )
);
} 

	$translate = new Zend_View_Helper_Translate($adapter);
	?>
				<div class="heading">
						<h3><?php 
						print $translate->translate('page_heading');	?>
						</h3>

                    <div class="resBtnSearch">
                        <a href="#"><span class="icon16 brocco-icon-search"></span></a>
                    </div>

                    <div class="search">

                        <form id="searchform" action="#" />
                            <input type="text" class="top-search" placeholder="Search here ..." />
                            <input type="submit" class="search-btn" value="" />
                        </form>
                
                    </div><!-- End search -->
				</div><!-- End .heading-->
    			