   <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/index"><i class="fa fa-tachometer"></i> Dashboard</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/setting/index"><i class="fa fa-trash-o"></i> Clean Cache</a>
                            </li>
                            
                            </ul>
                         </li>-->
                   
                      </ul>

   </div>