<ul class="menu-links">
	       <li><a href="<?php echo $this->baseUrl(); ?>/admin/page/new-page" title="Create new page">New Page</a></li>
           <li><a href="<?php echo $this->baseUrl(); ?>/admin/page/create-for-member" title="Create For Member">Create New Page for Member</a></li>
		   <li><a href="<?php echo $this->baseUrl(); ?>/admin/comments/index" title="View Recent Comments">Recent Comments</a></li>
		   
       </ul>