<div class="row">
    <div class="col-md-12">
    	<ul class="menu-links">
		<li><a href="<?php echo $this->baseUrl(); ?>/admin/edit-design" title="Template Editor">Back to Page Editor </a></li>
    	   <li><a href="<?php echo $this->baseUrl(); ?>/admin/sliders/index" title="View slider list"> list</a></li>            
    	</ul>
	</div>
</div><!-- /.row -->

<div id="msg"><?php echo $this->msg ?></div>
<div class="clearfix"></div>
	<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
<div class="row">
    <div class="col-md-4">
        <?php echo $this->form->name; ?>
		</div>
		<div class="col-md-2">
        <input type="submit" class="btn btn-middium btn-primary" value="Update Slider">
		</div>
</div>
 <div class="clearfix"><br/></div>
 
 <div class="row">
 
 <div class="col-md-4">
<table class="table">
<tr><td>
 <img src="<?php echo $this->baseUrl();?>/images/user/slides/500X500/<?php echo $this->slide1; ?>" alt="<?php echo $this->slide1;?>" style="float:left; width:300px;"/>
</td></tr>
<tr><td>
 <?php echo $this->form->slide1; ?>
</td></tr>
<tr><td>
 <?php echo $this->form->link1; ?>
</td></tr>
</table>
 </div>
 
 <div class="col-md-4">
<table class="table">
<tr><td>
 <img src="<?php echo $this->baseUrl();?>/images/user/slides/500X500/<?php echo $this->slide2; ?>" alt="<?php echo $this->slide2?>" style="float:left; width:300px;"/>
</td></tr>
<tr><td>
 <?php echo $this->form->slide2; ?>
</td></tr>
<tr><td>
 <?php echo $this->form->link2; ?>
</td></tr>
</table>
 </div>
 
 <div class="col-md-4">
<table class="table">
<tr><td>
 <img src="<?php echo $this->baseUrl();?>/images/user/slides/500X500/<?php echo $this->slide3; ?>" alt="<?php echo $this->slide3;?>" style="float:left; width:300px;"/>
</td></tr>
<tr><td>
 <?php echo $this->form->slide3; ?>
</td></tr>
<tr><td>
 <?php echo $this->form->link3; ?>
</td></tr>
</table>
 </div>
 </div><!-- /.row  -->

<!-- sliders row 2 -->
 <div class="row">

 <div class="col-md-4">
<table class="table">
<tr><td>
 <img src="<?php echo $this->baseUrl();?>/images/user/slides/500X500/<?php echo $this->slide4; ?>" alt="<?php echo $this->slide4;?>" style="float:left; width:300px;"/>
</td></tr>
<tr><td>
 <?php echo $this->form->slide4; ?>
</td></tr>
<tr><td>
 <?php echo $this->form->link4; ?>
</td></tr>
</table>
 </div>
 
 <div class="col-md-4">
<table class="table">
<tr><td>
 <img src="<?php echo $this->baseUrl();?>/images/user/slides/500X500/<?php echo $this->slide5; ?>" alt="<?php echo $this->slide5 ?>" style="float:left; width:300px;"/>
</td></tr>
<tr><td>
 <?php echo $this->form->slide5; ?>
</td></tr>
<tr><td>
 <?php echo $this->form->link5; ?>
</td></tr>
</table>
 </div>
 
 <div class="col-md-4">
<table class="table">
<tr><td>
 <img src="<?php echo $this->baseUrl();?>/images/user/slides/500X500/<?php echo $this->slide6; ?>" alt="<?php echo $this->slide6;?>" style="float:left; width:300px;"/>
</td></tr>
<tr><td>
 <?php echo $this->form->slide6; ?>
</td></tr>
<tr><td>
 <?php echo $this->form->link6; ?>
</td></tr>
</table>
 </div>
 </div><!-- /.row  -->

 </form>

<script type="text/javascript">
	
window.onload = function () {
 <?php if(!isset($this->msg)){ ?>
      $('#msg').hide();

    <?php  } else{
    ?>
      $('#msg').show().delay(3000).hide('slow');

    <?php } ?>
 }
 
</script>