<div class="row">
    <div class="col-md-12">
    	<ul class="menu-links">
    	   <li><strong><a href="<?php echo $this->baseUrl(); ?>/admin/sliders/index" title="View slider list">List</a></strong></li>            
    	</ul>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div id="msg">
			<?php echo $this->msg; ?>
		</div>
		<div class="clearfix">
		</div>
        
		<div class="table-responsive">
			<table class="table table-striped table-bordered table-hover" id="dataTables-example">
				<thead>
					<tr>
						<th class="grid-head">
							No.
						</th>
						<th class="grid-head">
							Slider Name
						</th>
						<th class="grid-head">
							Slide 1
						</th>
						<th class="grid-head">
							Slide 2
						</th>
						<th class="grid-head">
							Slide 3
						</th>
						<th class="grid-head">
							Slide 4
						</th>
						<th class="grid-head">
							Slide 5
						</th>
                        <th class="grid-head">
							Slide 6
						</th>
                        <th class="grid-head">
							Edit
						</th>
					</tr>
				</thead>
				<tbody>
					<?php if (count($this->slider_data)){ 
					   foreach ($this->slider_data as $item): ?>
							<tr>
                                <td style="text-align:center; vertical-align: middle;">
                                    <?php echo $item['slider_id'] ?>
                                </td>
                                <td style="text-align:center; vertical-align: middle;">
                                    <?php echo $item['name'] ?>
                                </td>
                                <td style="text-align:center;">  
                                <?php if(isset($item['slide1'])) { ?>                                  
    									<a href="<?php echo $this->baseUrl(); ?>/admin/sliders/edit/id/<?php echo $item['slider_id'] ?>"><img width="60" src="<?php echo $this->baseUrl(); ?>/images/user/slides/200X200/<?php echo $item['slide1'] ?>" alt="<?php echo $item['slide1'] ?>" /></a>    								
                                <?php } else { ?>
                                        <a href="<?php echo $this->baseUrl(); ?>/admin/sliders/edit/id/<?php echo $item['slider_id'] ?>"><img width="60" src="<?php echo $this->baseUrl(); ?>/images/user/slides/200X200/placeholder.png" alt="placeholder.png" /></a>
                                <?php }  ?>
                                </td>
                                <td style="text-align:center;">
                                <?php if(isset($item['slide2'])) { ?>
    									<a href="<?php echo $this->baseUrl(); ?>/admin/sliders/edit/id/<?php echo $item['slider_id'] ?>"><img  width="60" src="<?php echo $this->baseUrl(); ?>/images/user/slides/200X200/<?php echo $item['slide2'] ?>" alt="<?php echo $item['slide2'] ?>" /></a>
    							<?php } else { ?>
                                        <a href="<?php echo $this->baseUrl(); ?>/admin/sliders/edit/id/<?php echo $item['slider_id'] ?>"><img width="60" src="<?php echo $this->baseUrl(); ?>/images/user/slides/200X200/placeholder.png" alt="placeholder.png" /></a>
                                <?php }  ?>
                                </td>
                                <td style="text-align:center;">
                                <?php if(isset($item['slide3'])) { ?>
    									<a href="<?php echo $this->baseUrl(); ?>/admin/sliders/edit/id/<?php echo $item['slider_id'] ?>"><img  width="60" src="<?php echo $this->baseUrl(); ?>/images/user/slides/200X200/<?php echo $item['slide3'] ?>" alt="<?php echo $item['slide3'] ?>" /></a>
    							<?php } else { ?>
                                        <a href="<?php echo $this->baseUrl(); ?>/admin/sliders/edit/id/<?php echo $item['slider_id'] ?>"><img width="60" src="<?php echo $this->baseUrl(); ?>/images/user/slides/200X200/placeholder.png" alt="placeholder.png" /></a>
                                <?php }  ?>
                                </td>
                                <td style="text-align:center;">
                                <?php if(isset($item['slide4'])) { ?>
    									<a href="<?php echo $this->baseUrl(); ?>/admin/sliders/edit/id/<?php echo $item['slider_id'] ?>"><img  width="60" src="<?php echo $this->baseUrl(); ?>/images/user/slides/200X200/<?php echo $item['slide4'] ?>" alt="<?php echo $item['slide4'] ?>" /></a>
    							<?php } else { ?>
                                        <a href="<?php echo $this->baseUrl(); ?>/admin/sliders/edit/id/<?php echo $item['slider_id'] ?>"><img width="60" src="<?php echo $this->baseUrl(); ?>/images/user/slides/200X200/placeholder.png" alt="placeholder.png" /></a>
                                <?php }  ?>
                                </td>
                                <td style="text-align:center;">
                                <?php if(isset($item['slide5'])) { ?>
    									<a href="<?php echo $this->baseUrl(); ?>/admin/sliders/edit/id/<?php echo $item['slider_id'] ?>"><img  width="60" src="<?php echo $this->baseUrl(); ?>/images/user/slides/200X200/<?php echo $item['slide5'] ?>" alt="<?php echo $item['slide5'] ?>" /></a>
    							<?php } else { ?>
                                        <a href="<?php echo $this->baseUrl(); ?>/admin/sliders/edit/id/<?php echo $item['slider_id'] ?>"><img width="60" src="<?php echo $this->baseUrl(); ?>/images/user/slides/200X200/placeholder.png" alt="placeholder.png" /></a>
                                <?php }  ?>
                                </td>
                                <td style="text-align:center;">
                                <?php if(isset($item['slide6'])) { ?>
    									<a href="<?php echo $this->baseUrl(); ?>/admin/sliders/edit/id/<?php echo $item['slider_id'] ?>"><img width="60"  src="<?php echo $this->baseUrl(); ?>/images/user/slides/200X200/<?php echo $item['slide6'] ?>" alt="<?php echo $item['slide6'] ?>" /></a>
    							<?php } else { ?>
                                        <a href="<?php echo $this->baseUrl(); ?>/admin/sliders/edit/id/<?php echo $item['slider_id'] ?>"><img width="60" src="<?php echo $this->baseUrl(); ?>/images/user/slides/200X200/placeholder.png" alt="placeholder.png" /></a>
                                <?php }  ?>
                                </td>
                                <td style="text-align:center; vertical-align: middle;">
                                   <a class="btn btn-sm btn-warning float-right" href="<?php echo $this->baseUrl(); ?>/admin/sliders/edit/id/<?php echo $item['slider_id'] ?>">Edit</a>
                                </td>
							</tr>
							<?php endforeach; }?>
				</tbody>
			</table>
		</div>
		<!-- div responsive end-->
	</div>
</div>
<!-- /.row -->
<script type="text/javascript">
	
    $(function () {

        <?php if(!isset($this->msg)){ ?>
            $('#msg').hide();

        <?php  } else{
        ?>
            $('#msg').show().delay(3000).hide('slow');
        <?php } ?>
        
        $('#dataTables-example').dataTable(
            {
            "aaSorting": [[ 0, "asc" ]],
            "iDisplayLength": 50,
              "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
              "aoColumnDefs": [{'bSortable': false, 'aTargets': [8]}]
            }
        );
    });        

</script>