<div class="row">
    <div class="col-md-12">
    	<ul class="menu-links">
		<li><a href="<?php echo $this->baseUrl(); ?>/admin/gallery/new-photo" title="Add new photo"> Add Photo</a></li>
		<li><a href="<?php echo $this->baseUrl(); ?>/admin/gallery/index">Gallery List</a></li> 
        	<li><a href="<?php echo $this->baseUrl(); ?>/admin/photo-categories/new">Add New</a></li>  
    	</ul>
	</div>
</div>

<!--div class="row">
 <div class="col-md-12">
 <div class="page-title">Photo Categories List</div>
 </div>
</div><!-- /.row -->
             <div class="row" style="min-height: 550px;">
                         <div class="col-md-12">
                        <div id="msg"><?php echo $this->msg; ?></div>
                        
                                       <div class="table-responsive">
                                       <form method="post" action="" name="data_table">
                                                     <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                                        <thead>
                                                        
                                                            <tr>
                                                                <th class="grid-head">Banner</th>
                                                                <th class="grid-head">Name</th>
                                                                <th class="grid-head">Edit</th>
                                                                <th class="grid-head">Delete </th>
                                                                <th class="grid-head">
                                                                <input type="submit" name="submit" class="btn btn-danger btn-sm" id="submit" value="Delete"/>
                                                                <label><input type="checkbox" name="allbox" id="allbox" value="0" onclick="checkAll(this.value);" /> All</label>
                                                                </th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>

                                                        <?php if (count($this->data)){ ?>

                                                        <?php $counter=0; foreach ($this->data as $item): ?>

                                                        <tr class="odd gradeX">
                                                       
                                                        <td style="text-align:center; vertical-align: middle;">
                                                         <?php if(isset($item['banner']) && (!empty($item['banner']))) {?>
													     <img width="100" src="<?php echo $this->baseUrl(); ?>/images/photo_gallery/categories/200X200/<?php echo $item['banner'] ?>" alt="block-image" />
														 <?php } else {?>
                                                         <img width="100" src="<?php echo $this->baseUrl();?>/images/admin/placeholder200X200.png" alt="photo-category" /></a>
                                                         <?php } ?>
                                                        </td>
                                                        <td style="text-align:center; vertical-align: middle;">
                                                        <?php echo $item['category_name'] ?>
                                                        </td>
                                                        <td style="text-align:center; vertical-align: middle;">
                                                        <a class="btn btn-sm btn-warning float-right"
                                                        href="<?php echo $this->baseUrl(); ?>/admin/photo-categories/edit/id/<?php echo $item['pg_cat_id'] ?>">
                                                        Edit</a></td>
                                                        <td  style="text-align:center; vertical-align: middle;"><a class="btn btn-danger btn-sm" href="#" onclick="return confirmDelete(<?php echo $item['pg_cat_id'] ?> )" >Delete </a></td>
                                                        <td  style="text-align:center;"><input type="checkbox" name="bulkdata[]" id="check_<?php echo $counter++;?>" class="form-control" value="<?php echo $item['pg_cat_id'] ?>"/></td>
                                                        </tr>
                                                            <?php endforeach;  } ?>
                                                        </tbody>

                                                        </table>
                                                        </form>
                                                        </div><!-- div responsive end-->

                                </div>

                    </div>
                 <!-- /.row -->

<script type="text/javascript">
    function confirmDelete(id){
        var r = confirm("Are you sure to Delete this Category?" );
        if (r == true) {
                window.location.assign("<?php echo $this->baseUrl(); ?>/admin/photo-categories/delete-category/id/" + id);    
        } else {
            return false;
        }
    }
    
    function checkAll(a)
	{
	    var total = $('#dataTables-example tr:not(:has(th))').length;
        
		if(a == 0)
		{
			for(q=0;q<total;q++)
			{
                $('#check_'+q).prop('checked', true);
			}
            $('#allbox').val(1);
		}

		if(a == 1)
		{
			for(q=0;q<total;q++)
			{
                $('#check_'+q).prop('checked', false);
			}

            $('#allbox').val(0);
		}
	}
	
    $(function () {
        
        <?php if(isset($this->msg)){?>
            $('#msg').show().delay(5000).hide('slow');
        <?php } else { ?>
            $('#msg').hide();
        <?php } ?>
        
        $('#dataTables-example').dataTable(
            {
		      "aaSorting": [[ 0, "asc" ]], // 4th index or 5th column in descending order
              "iDisplayLength": 50,
              "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
              "aoColumnDefs": [{'bSortable': false, 'aTargets': [2,3,4]}]
	       }
        );
        
        $("form input[id='submit']").click(function() {  // triggred submit
    		
    		var count_checked = $("[name='bulkdata[]']:checked").length; // count the checked
    		if(count_checked == 0) {
    			alert("Please select a Posts to delete.");
    			return false;
    		} 
    		 else {
    			return confirm("Are you sure you want to delete these posts?");	
    		  }		
    	});
    });        

</script>