<style type="text/css">
#wrapper {
    padding-left: 0px !important;
	padding-top: 40px;
}
.border-black{
	border: 2px solid black; 
}
a { font: 14px sans-serif; color: #0066CC; text-decoration: none; }

#fixed { position: relative; float: left; }
#fluid { position: relative; }

#fixed a { position: absolute; background-color: #FFFDA0; opacity: .4;}
#fluid a { position: absolute; background-color: rgba(0, 0, 0, 0.5); }

#fixed img { vertical-align: bottom; }
#fluid img { display: block; width: 100%; height: auto; }

.clear { clear: both; }
.navbar-brand {
    float: left;
    height: 0px !important;
    padding: 22px 15px;
    font-size: 18px;
    line-height: 20px;
}
</style>
  <div class="row">
 <div class="col-md-12">
  <div id="fixed">
		  <img src="http://netefct.com/demo/images/admin/netefct-demo.png" width="1212px" />
		  <!-- img src="netefct-demo.png" width="1212px" /-->
		  
		  
		    <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/11" style="left: 100px; width: 260px; height: 60px; top:0px; margin-top:10px">  
    </a>
	  
		  
		<a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/sliders/edit/id/1" style="width: 1214px;
 height: 413px; top: 87px; left: -2px;">  
	</a>
	
    <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/1" style="width: 196px;
 height: 49px; top: 605px; left: 510px;">  
	</a>
	
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/gallery/edit-photo/id/1" style="left: 115px; width: 322px; height: 266px; top:651px; margin-top:10px">  
    </a>
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/gallery/edit-photo/id/2" style="left: 446px; width: 322px; height: 266px; top:650px; margin-top:10px">  
    </a>
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/gallery/edit-photo/id/11" style="left: 115px; width: 322px; height: 331px; top:939px; margin-top:10px">  
    </a>
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/gallery/edit-photo/id/10" style="left: 784px; width: 322px; height: 266px; top:648px; margin-top:10px">  
    </a>
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/gallery/edit-photo/id/6" style="left: 446px; width: 322px; height: 329px; top:937px; margin-top:10px">  
    </a>
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/gallery/edit-photo/id/7" style="left: 783px; width: 322px; height: 330px; top:936px; margin-top:10px">  
    </a>
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/videos" style="left: 117px; width: 487px; height: 292px; top:1464px; margin-top:10px">  
    </a>
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/testimonial" style="left: 610px; width: 472px; height: 293px; top:1464px; margin-top:10px">  
    </a>
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/44" style="left: 117px; width: 485px; height: 44px; top:1418px; margin-top:10px">  
    </a>
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/5" style="left: 179px; width: 137px; height: 44px; top:1771px; margin-top:10px">  
    </a>
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/45" style="left: 610px; width: 471px; height: 44px; top:1417px; margin-top:10px">  
    </a>
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/6" style="left: 323px; width: 109px; height: 44px; top:1770px; margin-top:10px">  
    </a>
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/7" style="left: 436px; width: 120px; height: 44px; top:1770px; margin-top:10px">  
    </a>
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/8" style="left: 559px; width: 99px; height: 44px; top:1769px; margin-top:10px">  
    </a>
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/9" style="left: 665px; width: 113px; height: 44px; top:1769px; margin-top:10px">  
    </a>
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/10" style="left: 787px; width: 137px; height: 44px; top:1768px; margin-top:10px">  
    </a>
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/2" style="left: 196px; width: 812px; height: 44px; top:1933px; margin-top:10px">  
    </a>
	   
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/1" style="left: 109px; width: 488px; height: 325px; top:2770px; margin-top:10px">  
    </a>
	<a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/12" style="left: 618px; width: 475px; height: 335px; top:2775px; margin-top:10px">  
    </a>
	  
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/3" style="left: 109px; width: 483px; height: 42px; top:3100px; margin-top:10px">  
    </a>
	
    
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/social-link/edit" style="left: 784px; width: 408px; height: 36px; top:3869px; margin-top:10px">  
    </a>
	
    
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/46" style="left: 96px; width: 1076px; height: 206px; top:3279px; margin-top:10px">  
    </a>
	
    
  <a class="border-black" href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/7" style="left: 68px; width: 475px; height: 36px; top:3868px; margin-top:10px">  
    </a>
	 
</div>
</div>
</div>